### ISSUE TITLE
Save as .obo results in .owl format

### ISSUE THREAD

**Issue by reliscu** [protegeproject/protege#1012]
Hi there,

I'm trying to save an ontology I made as .obo using "Save as...", but the extension is stubbornly stuck on .owl.

I am using Protege version 5.5.0. Any help is much appreciated!

Ontology attached.

[hs_dev_epoch.owl.zip](https://github.com/protegeproject/protege/files/6618184/hs_dev_epoch.owl.zip)

**Comment by matthewhorridge** [comment]
Closes by #1016
