### ISSUE TITLE
Should Protege recognize .nt files?

### ISSUE THREAD

**Issue by rpgoldman** [protegeproject/protege#1015]
I just stumbled trying to load an [n-triples file](https://www.w3.org/TR/n-triples/) using Protege.  Protege did not recognize a file with the `.nt` extension as being openable.

I believe it should since n-triples is described as

> This document defines N-Triples, a concrete syntax for RDF. N-Triples is an easy to parse line-based subset of Turtle. 

When I renamed the file to `.n3`, Protege was able to load it successfully. So shouldn't `.nt` be an OK file extension?

Thanks!

**Comment by matthewhorridge** [comment]
Yes, it should.  This looks like an omission!

**Comment by matthewhorridge** [comment]
Closed by #1016

**Comment by gouttegd** [comment]
Closing as the fix is now in the released Protégé 5.6.0.
