### ISSUE TITLE
ORCiDs should be compiled to https rather than http when auto-generating annotations

### ISSUE THREAD

**Issue by matentzn** [protegeproject/protege#1045]
Currently, when setting `ORCID` to the numeric code representing your orcid, Protege will translate that value to the ORCiD IRI with http rather than https, which seems to be what is recommended:

https://orcid.org/0000-0002-7356-1779

![image](https://user-images.githubusercontent.com/7070631/154567004-c9c3d6cf-9563-4fa7-ab80-ce252997b980.png)

**Comment by cthoyt** [comment]
Relevant line of code to change:
https://github.com/protegeproject/protege/blob/8cd47190928769c1321bc13f1bfd5aaf667b62f3/protege-editor-owl/src/main/java/org/protege/editor/owl/model/user/Orcid.java#L19

**Comment by matentzn** [comment]
@hkir-dev could you make this PR perhaps?

**Comment by cthoyt** [comment]
I'll do it if protege accepts external PRs

**Comment by matentzn** [comment]
It does, go ahead then :) Thanks @cthoyt

**Comment by matentzn** [comment]
Tag me in PR as well

**Comment by cthoyt** [comment]
@matentzn haven't got any feedback on #1053, it looks like Protege hasn't been updated for a year... is this project dead?

**Comment by matentzn** [comment]
There are no primary funds for protege desktop anymore, but @matthewhorridge keeps it going. He will probably merge all of the open PRs and do some minor fixes (migrate to latest 4,x OWLAPI) at some point this month. See ongoing discussion in OBO slack protege channel.

**Comment by matthewhorridge** [comment]
@cthoyt the project isn't dead...  @matentzn is correct in that there is no primary funding at the moment.  I'll get to the PR asap.

**Comment by dickersonlj** [comment]
Is there a way to receive these updates without subscribing to the OBO Slack?  Is that where most Protégé updates are posted?

Thank you.

**Comment by matentzn** [comment]
@dickersonlj 

I would not say there is a lot of updating going on in the OBO slack - its more like a support group for Protege users in our community. Unfortunately, the only way to be really sure you stay updated with everything is by subscribing to the issue tracker here! Something like a monthly digest to obo-tools or obo-discuss mailinglist (or protege mailing list!) would be great, but I doubt there is any funding right now to do such reporting - maybe I am wrong though (@matthewhorridge)
