### ISSUE TITLE
Bug in "equivalent to" based reasoning (use of max/exactly with data properties)

### ISSUE THREAD

**Issue by ASH-SYSTEMS** [protegeproject/protege#1054]
When using max/exactly (instead of min) to denote expected cardinality, the reasoners miss the class definition.
For example, say I have a class called Key and data property called Date. I want to define a class called DatedKey, which is a Key with a single Date data property; and a class called UndatedKey which has no Date data property.
If I use "Key and Date min 1" as the description of "equivalent to" of DatedKey, any key with a Date property is correctly tagged by reasoners as DatedKey, whereas if I use "Key and Date exactly 1" it does not.
Also, if I use "Key and Date max 0" or "Key and Date exactly 0" to describe UndatedKey, it does not work.

**Comment by matthewhorridge** [comment]
This isn't a bug (if I have understood your description correctly) – it is in accordance with the OWL semantics.  To be certain I would need to see an ontology with this information in and a description of the inferences that you expect.

I'm going to close this issue because it isn't a bug with Protege.  If you'd like to discuss this further please post this issue to the Protege mailing list.

**Comment by ASH-SYSTEMS** [comment]
Thank you. That's a bit strange since I saw OWL related tutorials that
describe such behaviors. Perhaps there is a specific case with zero/null
multiplicity.

How do I join/post on the mailing list?

Best regards,
Avi

**Comment by danielbakas** [comment]
Hi @matthewhorridge thank you for this answer. I was mind blown after trying to get something as simple as this to work, until I came across this.

Could you explain why it's not possible to do this in OWL? I have a concrete example: Composite and Prime integers.

* Integer: `have_factor some xsd:integer`
* Composite: `have_factor min 3 xsd:integer[> 0]` (this works)
* Prime: `have_factor exactly 2 xsd:integer[> 0]` (this doesn't work)

Thank you so much! 🙏🏽
