### ISSUE TITLE
v5.5.0 not compatible with linux-kernel 5.15.0-46

### ISSUE THREAD

**Issue by StroemPhi** [protegeproject/protege#1066]
Hi Protégé dev team,
I just happend to encounter that Protégé stopped showing the content of the entities tap after upgrading the linux kernel on my Lubuntu VM (running in Hyper-V on Win10) from 5.13.0-51 to 5.15.0-46. When booting in the old kernel using the Grub advanced menu, everything was fine again.
![Protege-5 5 0_5 15_Kernel](https://user-images.githubusercontent.com/56996739/185624177-feb8cbcb-f637-4f16-b2ee-a31ea9f7a1df.jpg)

**Comment by KonradHoeffner** [comment]
Just to add another datapoint: It works fine on 5.19.5, can you try upgrading to that and test if that works?
Anyways it is really strange that the Linux kernel version changes the behaviour of a Java program as it runs inside the JVM.
If you start it on the console, does the log output differ and/or show any errors or warnings?

**Comment by StroemPhi** [comment]
Sorry for not getting back to this earlier. I have not upgraded to the latest kernel, as I ditched the Lubuntu VM setup in favor of a Windows Linux Subsystem one. But as it seems to not be a problem for anyone else, I'll close this issue.
