### ISSUE TITLE
Choice of the next Java version we support

### ISSUE THREAD

**Issue by gouttegd** [protegeproject/protege#1071]
(This is a follow-up to the mail exchange earlier this week between @matentzn, @hkir-dev, @matthewhorridge, Harold Solbrig, and myself.)

Protégé currently runs under Java 8. I believe it is uncontroversial that we should support more recent versions.

Considering only the LTS releases, the choice is between Java 11 (supported by AdoptOpenJDK until “at least October 2024”) and Java 17 (“at least October 2027”).

If we opt for Java 11, we already have a branch (#1036) which appears to be working, though of course more thorough testing will be needed, especially with various plugins.

If we opt for Java 17, @hkir-dev has a branch (https://github.com/hkir-dev/protege/tree/jre_17) which also appears to be working (with the same reserves regarding thorough testing).

Does anyone have thoughts or reasons to prefer one version over another?

**Comment by fragosog** [comment]
I'm curious, does the java 11 version run as is under java 17, or are there spots that need to be rewritten for java 17?

**Comment by gouttegd** [comment]
Not directly.

The main problem is that several Java classes considered as “internal”, but that are used by Protégé, are no longer directly usable in Java 17. So we need to, either:

- pass some extra options to the JVM to make those classes usable;
- rewrite some portions of code to avoid using those classes.

The second option should be preferred, as it is a more “future-resistant” approach (“internal classes” could change or even be removed entirely in future Java versions without notice).

**Comment by gouttegd** [comment]
Closing here, as the decision to go for Java 11 has actually been taken weeks ago already.
