### ISSUE TITLE
Protege 5.0b15 not showing inferred types

### ISSUE THREAD

**Issue by tsarkov** [protegeproject/protege#109]
How to reproduce:

- Create class A
- Create class B as a subclass of A
- Create individual x of a type B
- Classify the ontology.
- Choose the class A. There would be no individuals under 'Members' in the Description of that class.

Protege 4.3 correctly shows that x is an inferred member of A.

**Comment by matthewhorridge** [comment]
Reproduced as described.  This is the desired behaviour.  The "members" section now shows direct instances.  This was to address issue #15.

**Comment by tsarkov** [comment]
Is there any way to see *all* members of a class, not only direct one (besides DLQuery tab)?

**Comment by matthewhorridge** [comment]
I don't think there is.  Perhaps this should be configurable.

**Comment by tsarkov** [comment]
I think it should be configurable. There is a request for this in the
StackOverflow list.

**Comment by matthewhorridge** [comment]
Closing this particular issue as it is the desired behaviour.  There are other issues for the enhancements described above.
