### ISSUE TITLE
Change "Members" in the Class Description view to something better

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/protege#110]
The Class Description view instances section is currently called "Members".  This is a funny non-standard bit of terminology.  I think "Direct instances" or something of this ilk would be better.

**Comment by matthewhorridge** [comment]
Also, see #109

**Comment by csnyulas** [comment]
If we want to support Issue #111 in the future, I would suggest that we use the label "Instances" instead of "Direct instances" to replace "Members".
