### ISSUE TITLE
Any chance of making 5.6 compatible with MacOS Catalina (10.15.7)

### ISSUE THREAD

**Issue by alanruttenberg** [protegeproject/protege#1101]
Congrats on the release! Unfortunately I can't use it as it says I need MacOS 11 and I'm on 10.15.7, without plans to upgrade.

**Comment by gouttegd** [comment]
Yes, it should be possible to lower the requirement down to macOS 10.12.

Supporting any even lower version is completely impossible as the Java11 runtime environment itself can’t run on macOS < 10.12.

**Comment by gouttegd** [comment]
Will be fixed with Protégé 5.6.1, which I plan to release in the coming days once OWL API 4.5.25 is available.

**Comment by alanruttenberg** [comment]
Thanks!

**Comment by gouttegd** [comment]
No, it’s not signed. The previous release was not signed either.

Sorry, but I won’t pay Apple $99 a year just to get a Developer Certificate and to make GateKeeper happy.

I only sign with my OpenPGP certificate; the signatures are available alongside the release archives.

**Comment by alanruttenberg** [comment]
Totally understand. Apple pisses me off too. Mentioned it in case it was an oversight. Thanks again for doing this.
