### ISSUE TITLE
UI on Windows: Tabs have lost their boundaries? Release 5.6.1

### ISSUE THREAD

**Issue by dlutz2** [protegeproject/protege#1114]
In the 5.6.1 release on Windows 10, the tabs seem to have lost the edges/boundaries that separate them from other tabs and the background. Same issue in all Look and Feels.
Attached image: Protege Look and Feel - Release 5.5 (left), Release 5.6.1 (right) 
![ProtegeGui](https://user-images.githubusercontent.com/4239052/226961349-90024573-5482-4173-934f-b2cb4de6a6f0.png)

**Comment by matthewhorridge** [comment]
This is just a flatter look and feel, which is intentional.  Whether it's to everyone's taste or not, or is a good idea or not is another matter.

**Comment by dlutz2** [comment]
Ah, aesthetics. I would vote for a bit too flat. If I hadn't used Protege before and knew what tabs to expect, I would be unsure how many tabs there actually were.
