### ISSUE TITLE
The relative location of OWLAPI versions used by protege WRT the shop is : all-over

### ISSUE THREAD

**Issue by sesuncedu** [protegeproject/protege#114]
What gets Downloaded? 
--------------------
1. ```mvn clean``` from the protege  top-level.
2. ```rm -rf  ~/.m2/repository/net/sourceforge/owlapi```
3. ```mvn package```

Results in downloading the following package versions

Package     | Versions
----------------|------------
owlapi-api   | 3.4.3, 3.4.10 , 3.5.0 , 3.5.1
owlapi-apibinding| 3.4.3 , 3.4.5 , 3.4.10 , 3.5.0 , 3.5.1
owlapi-contract   | 3.4.3 , 3.4.10 , 3.5.0
owlapi-distribution |  3.4.3 , 3.4.5 ,  3.4.9 , 3.4.10 , 3.5.0
owlapi-impl | 3.4.3, 3.4.10, 3.5.0 , 3.5.1
owlapi-oboformat | 3.4.10 , 3.5.0 , 3.5.1
owlapi-osgidistribution | 3.5.1
owlapi-parent | 3.4.3 , 3.4.5 ,  3.4.9 , 3.4.10 , 3.5.0 , 3.5.1 
owlapi-parsers | 3.4.3 , 3.4.10 , 3.5.0 , 3.5.1 
owlapi-tools |  3.4.3 , 3.4.10 , 3.5.0 , 3.5.1 

What is used at runtime?
----------------------------------
owlapi-osgidistribution version **3.5.1**  is used at runtime.  This is a shaded jar, but the mvn central POM is not dependency reduced.   This is the source of all **3.5.1** downloads.

What causes other downloads at build time?
-------------------------------------------------- 
* org.protege.editor.owl depends on 
    * edu.stanford.protege:protege-owlapi-extensions:3.2.6 , which depends on 
         * owlapi-distribution:**3.5.0**
         * jfact:1.0.0,  which depend on
               * owlapi-distribution:**3.4.3** 

* protege-parent depends on
     * org.protege.editor.owl.diff:4.1.1 which depends on 
         * org.protege.owl.diff:1.0.1 which depends on 
            * owlapi-distribution: **3.4.10**
     * org.protege.integration.hermit:1.0.0 which depends on 
        *  org.semanticweb.hermit:1.3.8.3 which depends on 
            * owlapi-distribution: **3.4.9**
       * owlapi-distribution: **3.4.5**
   * org.coode.dlquery:1.1.4 which depends on 
      * org.protege.editor.owl:4.3.0 which depends on 
             * owlapi-distribution:**3.4.3**
             * protege-owlapi-extensions:3.2.4 , which depends on 
                   * owlapi-distribution:**3.4.3**

Quite a few plugins have dependencies on ```org.protege.editor.owl:4.3.0```

**Comment by sesuncedu** [comment]
The absence of owlapi-contract:3.5.1 is related to owlapi issue https://github.com/owlcs/owlapi/issues/334 , which is in turn related to https://github.com/protegeproject/protege/issues/100

**Comment by sesuncedu** [comment]
Here's an unhelpful graph of version subsets.

![owlapi-protege-versions](https://cloud.githubusercontent.com/assets/411675/5949017/c02c401a-a717-11e4-9f4a-b36d3d1fe50d.png)

**Comment by matthewhorridge** [comment]
FYI I've started to fix some of these.

**Comment by sesuncedu** [comment]
I'm beginning to wonder if it might be worth making some of the
sub-projects that now live in their own repositories become part of the
main project (basically, everything that is Protégé specific and part of
the protégé distribution).

Obviously this doesn't apply to things that are shared with Web Protégé.

Also obviously this is not a use case for git submodules, because
UseCaseForGitSubmodules ⊑ ⊥

**Comment by matthewhorridge** [comment]
Trying to keep things in step is somewhat painful.  Are you suggesting all of the plugins that form the current distribution?

**Comment by sesuncedu** [comment]
Or as a possible subset, the ones that are under protegeproject umbrella,
 and which have a dependency on an artifact generated by a child of
```edu.stanford.protege:protege-parent:```

The idea would be to have more things inherited (and also to build against
the versions of libraries that will be used at runtime).  If it complicates
things then consider the suggestion withdrawn :)

**Comment by ignazio1977** [comment]
> jfact:1.0.0, which depend on
> owlapi-distribution:3.4.3


This can be almost fixed by referring JFact 1.2.3 (which relies on 3.5.0)
JFact 1.2.4 should be released with 3.5.2 dependency (maybe 3.5.3?)
I need to learn how to specify a range of dependencies rather than one strict selection.

**Comment by sesuncedu** [comment]
It's standard interval notation.  The real bugger are the non numeric bits
:)


On Mon, Mar 16, 2015 at 4:46 PM, Ignazio Palmisano <notifications@github.com

**Comment by matthewhorridge** [comment]
Closing this.  I think things have got somewhat better since we split of the plugins from the core build.
