### ISSUE TITLE
Bug: MacOS double clicking ontology to open Protege fails to open ontology

### ISSUE THREAD

**Issue by alanruttenberg** [protegeproject/protege#1149]
Protege not running.

Double click on an owl file, expecting that Protege will start and my ontology will be opened.

Instead I get a new blank ontology, and then have to go to the finder and double click the ontology I want to get it to open. When that opens the original blank ontology goes away.

MacOS 10.15.7 Protege 5.6.1

**Comment by matthewhorridge** [comment]
Duplicate of #1102
