### ISSUE TITLE
UHD resolution support

### ISSUE THREAD

**Issue by rawmatt** [protegeproject/protege#115]
The GUI doesn't scale to UHD resolution. At UHD resolution Protege is too small to use.

I am running 3840x2160 on Windows 8.1, on an ordinary Lenovo laptop. This resolution is increasingly mainstream nowadays.

Changing the font size makes the text content grow to be readable, but not the screens and their labels.

Please support scaling to UHD.

**Comment by matthewhorridge** [comment]
Protege default look and feel hard codes the font size to 11pt (which also renders horribly on a retina display).  I'll see if we can just use the look and feel default.  Hopefully this will help.

**Comment by pfps** [comment]
Hi:

What did you do to get the text size changed?

peter

**Comment by matthewhorridge** [comment]
Reopening as this is still a problem.  One possible work around is to change the look and feel to Windows, but some more investigation is needed.

**Comment by 28controls** [comment]
Hi,

Has there been found a solution for this issue as I have this in the latest 5.2 version with a 4K display.
I would really appreciate the help!
The tabs' text is sizeable with the font setting in the preferences but the content of the tabs is not.

Kind regards,

Marc.

**Comment by csnyulas** [comment]
Relevant issues #251 and #752.

**Comment by cenguix** [comment]
Hi:
It is a problem of the properties associated to the Protege.exe file. Right Click on properties, change compatibility settings for high resolution system. Same problem happened when installing Oracle sqldeveoper. This setting affects all java-based installations.

**Comment by yoyou446** [comment]
bumping this

**Comment by neurorepro** [comment]
A solution for Windows 10 i found looking at [this post](https://github.com/protegeproject/protege/issues/752#issuecomment-379234435) and [that one](https://github.com/protegeproject/protege/issues/752#issuecomment-469839145) is:
* Search for Protege in Windows Search bar, right click on it and choose `Open File Location`
* Right click on Protege exe, click on `Properties`
* In `Compatibility` tab, click on `Change High DPI settings` button
* In the `High DPI scaling override` section, tick `Override high DPI scaling behavior` and choose `System (enhanced)` in the menu

**Comment by joestubbs** [comment]
For those who might be looking for a Linux solution, adding `-Dsun.java2d.uiScale=2.0` to the java command in `run.sh` worked for me (see this [thread](https://stackoverflow.com/questions/58699877/how-to-fix-scaling-of-a-java-based-application-on-a-high-dpi-display-in-linux) for details)

**Comment by TTiannaiTT** [comment]
> A solution for Windows 10 i found looking at [this post](https://github.com/protegeproject/protege/issues/752#issuecomment-379234435) and [that one](https://github.com/protegeproject/protege/issues/752#issuecomment-469839145) is:
> 
> * Search for Protege in Windows Search bar, right click on it and choose `Open File Location`
> * Right click on Protege exe, click on `Properties`
> * In `Compatibility` tab, click on `Change High DPI settings` button
> * In the `High DPI scaling override` section, tick `Override high DPI scaling behavior` and choose `System (enhanced)` in the menu

Thanks a lot! Really helps!
