### ISSUE TITLE
Protege.exe does not pass arguments to the 'main' method

### ISSUE THREAD

**Issue by jmkeil** [protegeproject/protege#1162]
*This issue has similar symptoms as #547, but it has another root cause.*

Opening an ontology file with Protege.exe by associating the file type with Protege.exe or with the "Open with …" dialog does not work. Using `run.but` instead is a workaround, but with some disadvantages (additional console window, no icon associated, ambiguous name in "open with …" dialog). As i understood, the problem is, that `Protege.exe` does not pass the arguments to the `main` method. According to the [documentation](https://launch4j.sourceforge.net/docs.html#Configuration_file) of the maven [plugin generating the EXE file](https://github.com/Disassem/protege/blob/bbb28c2b7b4210d84e9a7f385d55485d989e4910/protege-desktop/pom.xml#L151-L203), it is a known limitation of the plugin:

> Missing features:
> * […]
> * Command line arguments cannot be passed to the executable.
> * […]

Solving this problem would therefore require to switch the maven plugin (if there is a sufficient alternative).

**Comment by gouttegd** [comment]
> According to the [documentation](https://launch4j.sourceforge.net/docs.html#Configuration_file) of the maven [plugin generating the EXE file](https://github.com/Disassem/protege/blob/bbb28c2b7b4210d84e9a7f385d55485d989e4910/protege-desktop/pom.xml#L151-L203), it is a known limitation of the plugin:

You’re looking at an old version of Protégé, we are no longer using this plugin to generate the Windows launcher. We use a custom launcher instead.

The good news is that this launcher does allow us to pass command line arguments to the `main` method – it’s merely an oversight that we did not do so. I’ll fix that shortly.

**Comment by gouttegd** [comment]
The launcher has been updated to pass command line arguments. The issue will be fixed in the next Protégé release.

**Comment by jmkeil** [comment]
Thanks for fixing. Looking forward for the next release.
