### ISSUE TITLE
Look and Feel selection is not highlighted in the menu in Linux

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#150]
Current Look & Feel selection should be highlighted in the menu, just like reasoner selection and other menu selections under the "View" menu are shown, but this is not happening when running Protégé in Ubuntu (with Unity):
![protege look and feel menu ubuntu](https://cloud.githubusercontent.com/assets/2441046/6609405/295da56c-c80e-11e4-96dc-cc909ad0c330.png)

This is how other menu selections are shown:
![protege view menu ubuntu](https://cloud.githubusercontent.com/assets/2441046/6609421/6108562e-c80e-11e4-9eef-54ee8eabf0c0.png)

and this is how the Look & Feel menu selection is shown in Windows:
![protege look and feel menu windows](https://cloud.githubusercontent.com/assets/2441046/6609462/130c6dba-c80f-11e4-9506-fa5c00851141.png)

**Comment by matthewhorridge** [comment]
This could be because you have a look and feel that was set in a previous version of Protege and that is no longer visible via the Look and Feel menu.  Does this problem persist if you select one of the look and feels on the menu?

**Comment by csnyulas** [comment]
Yes. Whatever L&F I select, the change to the look and feel takes effect (after I restart Protege), but the selection is not shown. It is rather strange.
