### ISSUE TITLE
Cmd+R overload (Mac, P5 b16)

### ISSUE THREAD

**Issue by tsarkov** [protegeproject/protege#156]
On Mac Cmd+R used to run the reasoner on current ontology. Now it conflicts with new menu element "Reload ontology", which happen to be earlier in the queue. In the menu both actions are labelled with cmd+R, which is confusing.

**Comment by csnyulas** [comment]
Maybe it could be Ctrl+Shift+R (Cmd+Shift+R on Mac) to parallel Ctrl+Shift+O for "Open from URL...",
or
Ctrl+Shift+L (Cmd+Shift+L on Mac) standing for Re**l**oad. Unfortunately Ctrl+L is already taken for "Edit active ontology library..."

We should definitely avoid conflicting with the reasoner's shortcut key, which is familiar to, and  frequently used by, most users.

**Comment by matthewhorridge** [comment]
Sorry, I hadn't spotted that.  I'll change it to CMD+SHIFT+R.
