### ISSUE TITLE
Increase/Decrease font size is not working

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#165]
The "Increase font size" and "Decrease font size" options in the Window menu (and their attached keyboard shortcuts) have no effect. Apparently they were not working in Protege 4.3 release either.

**Comment by matthewhorridge** [comment]
For the record, this works via the renderer tab in the preferences dialog.

**Comment by tudorache** [comment]
Maybe we should take out these two menu items then, as they do not work.

**Comment by csnyulas** [comment]
But even if we take the menu items out we should make sure to leave this issue open, or create a new enhancement request issue, so that we implement this feature at some point, as it is a very much requested one. I witnessed many people who had difficulty seeing what's displayed in the editor, and wanted to increase the font (some of these are reported on the mailing list as well). 
We can't expect from users to change their screen resolution to be able to comfortable use Protege, right? On the other hand changing the font size for  the entity rendering (`File -> Preferences... -> Renderer`) works fine.
