### ISSUE TITLE
Don't make protege.common re-export log4j

### ISSUE THREAD

**Issue by sesuncedu** [protegeproject/protege#167]
[log4j-2.X](http://logging.apache.org/log4j/2.x/) is made of people! Er, I mean bundles.

log4j-1.2.X compatible API is available in 
http://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-1.2-api/2.2

Fewer random dependencies.

The 1.2 compatibility api may or may not require changes to the custom appender. 

As an alternative, this may be an incentive to switch to slf4j, since most changes can be done with a special refactor.  
The  1.2 compatibility api and the slf4j bridge (not implementation), could redirect legacy log4j calls to slf4j. Must be careful not to have slf4j deployed to use log4j as the backend as that doesn't end well (or ever).

**Comment by matthewhorridge** [comment]
> As an alternative, this may be an incentive to switch to slf4j, since most changes can be done with a special refactor.

+1

**Comment by matthewhorridge** [comment]
We've switched to slf4j for Protege, but log4j is still exported for existing plugins.
