### ISSUE TITLE
Reset preferences does not update the preferences window

### ISSUE THREAD

**Issue by ykazakov** [protegeproject/protege#168]
Go to Preferences > Reasoner
make some changes in Displayed Inferences
press "Reset preferences..", press yes
nothing changes

tested v. 5.0.0-beta-17 on mac os x 10.10.2

**Comment by matthewhorridge** [comment]
Verified.  Thanks for the bug report.

**Comment by matthewhorridge** [comment]
This is all the prefs by the way.  The reset button resets everything (at least in the background).

**Comment by ykazakov** [comment]
On Thu, Mar 19, 2015 at 6:26 PM, Matthew Horridge <notifications@github.com>
wrote:

> This is all the prefs by the way. The reset button resets everything (at
> least in the background).
>

I see. Confirmed: if I close and reopen the preferences, the values will
set be default. So I guess its just a problem of refreshing the UI.
