### ISSUE TITLE
Monitoring question

### ISSUE THREAD

**Issue by evillaes** [protegeproject/protege#171]
I have a doubt regarding monitoring, I would like to know if there is a plugin to check health of protégé for Nagios or other monitoring system.

Thanks and regards,
Elena.

**Comment by csnyulas** [comment]
Hi Elena,
This is a question for our mailing list [1], rather then a issue for our github repository.
I am not aware of any specific Protege plug-in for monitoring system, but I guess Protege could be monitored as any Java application.

[1] Subscribe at http://protege.stanford.edu/support.php and write to protege-user@lists.stanford.edu
