### ISSUE TITLE
Individuals by type does not respect the selected class when adding a fresh individual

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/protege#177]
Select a class in the individuals by type view.
Press the add button to add a fresh individual and follow through to add it.
The individual is not added with a type of the selected class.

**Comment by saetre** [comment]
I have the exact same problem with Protege 4.2.0 Build 295.
Nothing ever shows up in the "Individuals by type" window, now matter which Class-Types I have assigned to my Entities/Individuals.

Can anyone explain what is happening, or what is not working?
