### ISSUE TITLE
GUI freezes or reacts mysteriously

### ISSUE THREAD

**Issue by drseb** [protegeproject/protege#205]
Hi,

I am sorry that I don't have 100% reproducible example, but very often the GUI freezes or does not react mouse-clicks properly. The Console only writes:
"Error logged
java.lang.ArrayIndexOutOfBoundsException
Uncaught Exception in thread AWT-EventQueue-0
java.lang.ArrayIndexOutOfBoundsException"

It happens very often when to a search and double-click on a search result. I am sorry that I can't be more specific.

I am on OS X Yosemite 10.10.3. . I use Protege 5.0.0-beta-17. I start the software by double-clicking on "run.command" which looks like this: 
cd "$(dirname "$0")"

CMD_OPTIONS="-Dapple.laf.useScreenMenuBar=true -Dcom.apple.mrj.application.apple.menu.about.name=Protege -Xdock:name=Protege -Xdock:icon=Protege.icns"

jre/bin/java -Xmx5G -Xms1G \
     -Dlog4j.configuration=file:log4j.xml \
     -DentityExpansionLimit=100000000 \
     -Dfile.encoding=UTF-8 \
     -classpath bin/org.apache.felix.main.jar:bin/ProtegeLauncher.jar \
     $CMD_OPTIONS org.protege.osgi.framework.Launcher

Let me know if you have any idea how I could help debug.

Sebastian

**Comment by tudorache** [comment]
Can you please post the entire stack trace? Also, please post the entire output in the console of when Protege starts. Thanks.

**Comment by drseb** [comment]
I updated to latest jdk (1.8.0_45), which was 1.8.0_31 before. Currently, I don't have any problems. I will re-open if I can give more detailed report.

**Comment by matthewhorridge** [comment]
Sebastian, thanks a lot for updating us with respect to this.

**Comment by tudorache** [comment]
Duplicate of #226.
