### ISSUE TITLE
TurtleOntologyParser breaks on legal Turtle 1.1 expression

### ISSUE THREAD

**Issue by grahamegrieve** [protegeproject/protege#209]
This turtle:

@prefix p: <http://example.org/path/> .

:X a rdf:Property;
  :prop p:bs\\#x.

causes protege 5.0 to report the following error:

uk.ac.manchester.cs.owl.owlapi.turtle.parser.ParseException: Encountered " <ERROR> "\\ "" at [].
Was expecting:
    "." ...

this is the escaped # in the URL. The IRI is http://example.org/path/bs#x

This appears to be a duplicate of https://github.com/protegeproject/protege/issues/89, but that is claimed to have been fixed in an earlier version

**Comment by matthewhorridge** [comment]
This will be fixed when we upgrade to the OWL API version 4.0.2 (or 4.1.0 when it's out)

**Comment by grahamegrieve** [comment]
oh. I misread the version numbers that applied. Can you give any estimate of when this will happen?

**Comment by matthewhorridge** [comment]
Working in 5.0.0 RC1.  (Well, from when we upgraded the OWL API)

**Comment by remkoboschker** [comment]
Hi,

The parser is crashing on an escaped quote ``\'``.

**Comment by tudorache** [comment]
This is an OWL API issue. Please report it on the OWL API mailing list (https://sourceforge.net/p/owlapi/mailman/) or on their GitHub (https://github.com/owlcs/owlapi/issues). It would be helpful to provide them a file that shows the behavior.
