### ISSUE TITLE
How to get Protégé 5 Icon on Windows Task Bar?

### ISSUE THREAD

**Issue by uscholdm** [protegeproject/protege#210]
I created a shortcut for run.bat for protégé 5, as instructed in the install notes, but this time, I do not get the Protégé icon, I get this instead:

![image](https://cloud.githubusercontent.com/assets/10777545/7168365/b9c1de6a-e371-11e4-92db-ba6158fba73b.png),   which is a shortcut for: "C:\Program Files\Protege-5.0.0-beta-17\run.bat"

However, I cannot get it onto the taskbar for quick start up.  Windows does not seem to recognized it as type application, it shows up as a “Windows Batch File”.  

Is there a way to get it onto the task bar?

**Comment by csnyulas** [comment]
Would this work:
http://superuser.com/questions/100249/how-to-pin-either-a-shortcut-or-a-batch-file-to-the-new-windows-7-taskbar

**Comment by csnyulas** [comment]
Regarding the icon to be used for your shortcut: we filed an issue for this ( #211 ), and once it is fixed (in the next release), you will be able to set up your shortcut to use the icon in the Protege distribution instead of the default command line icon provided by the OS.

**Comment by csnyulas** [comment]
I close this issue because one half of it has been addressed here, and for the other half a more specific issues has been created.
