### ISSUE TITLE
Issue with display in hierarchy in Cell Ontology

### ISSUE THREAD

**Issue by nicolevasilevsky** [protegeproject/protege#215]
When searching for terms in the Cell Ontology (in the cl-edit.owl file), when I click on the term, it does not display that term in the hierarchy on the left-hand side. This is a problem for me in Protege 4.3 and 5.0 (Build beta 16).

![image](https://cloud.githubusercontent.com/assets/6722114/7257148/514baffa-e808-11e4-856f-f03c89b49751.png)

**Comment by dosumis** [comment]
Workaround: Sync of search works with the entities tab.

**Comment by nicolevasilevsky** [comment]
It doesn't seem to work for me, see screenshot.
![image](https://cloud.githubusercontent.com/assets/6722114/7257456/be3d96d0-e80a-11e4-91ac-b3272b01794d.png)

**Comment by cmungall** [comment]
@nicolevasilevsky can you try with 5b17? This seems to fix it.

**Comment by nicolevasilevsky** [comment]
@cmungall Yep, I using Protege 5 beta 17 fixed the problem. Thank you!
