### ISSUE TITLE
How can one declare that a property has a union of classes as its domain?

### ISSUE THREAD

**Issue by ivanfilippenko** [protegeproject/protege#218]
Selecting more than one class to define the domain for a property in the Protege 5 UI always asserts the intersection of the classes to be the domain.  How can one, using the UI, specify that the union of several different classes is the property's domain?

**Comment by csnyulas** [comment]
This is not an appropriate issue for our issue tracker. If you have a question about how to do something, you should write to our mailing list and we will try to help you there.
You can subscribe to our mailing list here:
http://protege.stanford.edu/support.php
or here:
https://mailman.stanford.edu/mailman/listinfo/protege-user

**Comment by ivanfilippenko** [comment]
Hi, thanks for pointing that out.  I subsequently posted my question (on April 26) to the Protege User project on Nabble (http://protege-project.136.n4.nabble.com/), but it keeps showing "This post has NOT been accepted by the mailing list yet." which must explain the lack of replies.  Could you please ensure that my question is accepted?  Thank you very much!  -- Ivan

**Comment by tudorache** [comment]
You need to be subscribed to the protege-user mailing list to post. Go here to subscribe:
https://mailman.stanford.edu/mailman/listinfo/protege-user

**Comment by ivanfilippenko** [comment]
Okay, thanks.  I thought I was subscribed.  I'll do it again.  -- Ivan

**Comment by ivanfilippenko** [comment]
I subscribed.  I presume I don't need to re-post my two outstanding questions.  I also commented on another person's question, and that comment hasn't been accepted yet, either.  Many thanks for your help!  -- Ivan

**Comment by tudorache** [comment]
Yes, please re-post your questions on the mailing list, so that we can give a reply in context.

**Comment by ivanfilippenko** [comment]
Oh, okay, will do.  Thanks.

**Comment by csnyulas** [comment]
I observed that you have managed to post to our mailing list and your questions are being answered by our colleagues and/or the community.

I also added you to the "members" user group on nabble, so that in the future you should be able to post to our mailing list through the nabble interface as well.
