### ISSUE TITLE
Unqualified cardinality restrictions on data properties are impossible to create

### ISSUE THREAD

**Issue by mirzov** [protegeproject/protege#220]
Observed in 5.0.0 beta-17
For example, syntax checker in Class expression editor rejects expressions of the form `p exactly 1` where `p` is a data property, making such cardinality restrictions impossible to create in Protege 5. It works in Protege 4.3.

**Comment by matthewhorridge** [comment]
This could be due to changes in the OWL API.  You can enter unqualified cardinality restrictions on data properties but you will need to specify a filler of rdfs:Literal.  (Which is the top data type analogous to owl:Thing).  Depending on your rendering settings you will either need to type:

```  p exactly 1 Literal ```

or

``` p exactly 1 rdfs:Literal ```

**Comment by mirzov** [comment]
Got it, thanks!
