### ISSUE TITLE
Telling Protege to open an owl file from the command line

### ISSUE THREAD

**Issue by cmungall** [protegeproject/protege#221]
For P4 on OS X I had a very convenient command:

`alias p4='open -a /Applications/Protege-4.3.app`

Which meant I could do

`p4 foo.owl`

Directly from the directory that houses foo.owl. Believe me, this saved me a *lot* of time and tedium faffing with the file finder (especially as the "open>recent" menu in Protege doesn't *really* seem to remember your recent ontologies, it refuses to forget some ontology I last looked at in 2007, and the stored history is not very large).

P5 is launched via a bash script rather than an OS X bundle. I'm just too lazy to delve into the OSGi docs to figure out how to tunnel through what I need on the command line, if it's even possible.

If it's not possible, feel free to close this ticket.

**Comment by matthewhorridge** [comment]
This functionality will actually be available in the next beta build, albeit via the run.command script (which will now properly pass the command line arguments to Protege), but it works just the same.

**Comment by cmungall** [comment]
Thanks!

Just FYI for people arriving here in a search, the way to do that in the current snapshot requires a full URI, so to pass a file foo.owl in the current directory:

```
$PATH_TO_PROTEGE/run.command  file://`pwd`/foo.owl
```

**Comment by Gershele** [comment]
Greetings, all,

I am trying to tell Protege to open a file from the terminal (want to put that into a script later on). I have read this thread and adhered to the syntax suggested. I have tried all 4.x versions of Protege and version 5 as well - both with my local JRE and with the one bundled with the universal installer. No joy.

Could you please let me know, which version of Protege you have used, to make this work? is this perhaps OS related? I am running Ubuntu, perhaps you were running WIndows...?


Thank you for your help. Which is very much appreciated.
