### ISSUE TITLE
Improper character in label

### ISSUE THREAD

**Issue by swartik** [protegeproject/protege#224]
I'm running Protege Version 5.0.0, build beta-17 on Windows 7. The label at the bottom of the screen instructing how to use the reasoner has an invalid character. I can't seem to upload an image, so I'll describe it: the label is

>  To use the reasoner click Reasoner * Start reasoner

The character I've typed as `*` appears as a rectangle, that is, an unknown character.

**Comment by tudorache** [comment]
The missing character is an arrow. If it is not shown, it means that some font is missing on the host computer. See screenshot.

![screenshot - 06102015 - 05 20 44 pm](https://cloud.githubusercontent.com/assets/2709502/8097276/229bf4ee-0f95-11e5-8fed-e36f1b041c8a.png)

We can investigate if another character should be used instead, or just simply replace with text.

**Comment by swartik** [comment]
Tania,



Thanks. I figured you replaced the old “=>” sequence in Protégé 4 with a single character. As for whether a font is missing on my computer, I can only respond that I have a pretty standard Windows 7 configuration. I recall that the Protégé team uses Macs. Have you checked the character on a random sample of Windows systems?



Regards,



Steve Wartik

**Comment by tudorache** [comment]
We don't have any Windows computers :) But I am sure we'll find a virtual machine somewhere that works.

The screenshot was from a Linux computer.

Thank you for letting us know about the font problem. Did you try to clear your preferences to see if the problem still persists?

**Comment by swartik** [comment]
Tania,



I cleared my preferences but the problem persists, even after restarting Protégé.



Thanks for having sympathy for us Windows users. It’s not my fault!
