### ISSUE TITLE
Entity rendering chooses different substring in Protege 5 (caused by changes in the OWL API IRI::getFragement() implementation)

### ISSUE THREAD

**Issue by houzw** [protegeproject/protege#229]
I have tried the protege-5.0.0-beta-17-win, and I have found that entities like "~#Archean_Eonothem" displayed just fine, but others like "~#119Ma" or "~#0.0117Ma" just displayed incorrect with "Ma", but the uris are correct. I think that's a bug in protege 5 (Entities displayed correct in version 4.3).
![2015-08-09_104937](https://cloud.githubusercontent.com/assets/11572300/9153377/ea3c1c0e-3e84-11e5-99a9-b6ce4b6f8257.jpg)

Another problem is that the new version of peotege  displays Chinese in boxes, but when I changed the font to "SimSun" which supports Chinese by using 4.0,  the problem gone. So I recommend that the new version should add font change support again.

**Comment by matthewhorridge** [comment]
I've split this into two issues.  See #234 for the issue with the font.

**Comment by matthewhorridge** [comment]
I could do with the answers to some questions:

(1) What is the full IRI of "~#0.0117Ma"?
(2) Which renderer have you got selected in Protege (on the view menu)?

**Comment by houzw** [comment]
Thanks for your hint. I used the default render  rdfs:label before, but I had not set the labels ...  It's not a problem anymore, thanks!

**Comment by houzw** [comment]
Thanks for your hint. I used the default render  rdfs:label before, but I had not set the label ...  It's not a problem anymore, thanks!
