### ISSUE TITLE
Embed Guava in protege-common

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/protege#243]
It's currently turned into a plugin

**Comment by ykazakov** [comment]
I think Guava was not turned into a plugin, it is already provided as a bundle jar. What is to be achieved by embedding?

**Comment by matthewhorridge** [comment]
I thought it was turned into a plugin, but yes, it was already provided as a bundle.  In that case, embedding wouldn't buy us anything.... just a style issue as it's not a plugin as such.

**Comment by ykazakov** [comment]
I see, you mean the jar is now located in "plugins" not in "bundles". Would it be enough to just move it to "bundles"? I would prefer not to have huge jar containing other jars, which contain other jars, etc. Similarly for log4j (where is it embedded now?). Similarly for OWL API. From a plugin developer point of view it is more convenient to see which dependencies are provided by Protege. Also, upgrading bundles to new versions (provided they are within the admitted ranges) should be much easier. E.g., replacing OWL API with the new version with bug-fixes.

**Comment by matthewhorridge** [comment]
Not doing this now.
