### ISSUE TITLE
Failed to search the whole phrase

### ISSUE THREAD

**Issue by johardi** [protegeproject/protege#265]
When I looked at the search pattern, I saw my search string was split by the `AND` operator. That might be the bug.

**Comment by johardi** [comment]
OK I misunderstood the "Whole words" option. It has a correct behavior that when I typed the word "Diabet" the search engine didn't return me any result. And if I unchecked the option, it returned me results of "Diabetes" (which contains the string "Diabet" and this is correct).

However I expect I can search a whole phrase using this same option. So when I typed "Diabetes Mellitus" I should get only those entries with "Diabetes Mellitus" phrase in it, not each word "Diabetes" and "Mellitus". Does it make sense?

**Comment by matthewhorridge** [comment]
This is intended behaviour.  See this issue #87.
