### ISSUE TITLE
Inconsistency in search results

### ISSUE THREAD

**Issue by johardi** [protegeproject/protege#266]
For example, the results for "Diabetes Mellitus" and "Mellitus Diabetes" are different. PS. The search doesn't take into account getting the whole words/phrase.

**Comment by johardi** [comment]
I suspect the bug comes from this optimization code: https://github.com/protegeproject/protege/blob/master/protege-editor-owl/src/main/java/org/protege/editor/owl/model/search/SearchManager.java#L185

**Comment by matthewhorridge** [comment]
This is the intended behaviour.
