### ISSUE TITLE
"Instances (inferred)" view does not show inferred instances

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#267]
To reproduce:
1) Create this ontology
```
Class: Person
Class: Man
    subclassOf: Person
Individual: Joe
    Types: Man
Individual: John
    Types: Man
```
2) Select a reasoner (e.g. HermiT 1.3.8)
3) Start reasoner
4) Select "Individuals by class" tab, and add the "Instances (inferred)" view (from the Window -> Views -> Individual Views -> Instances (inferred) menu)
5) Select class `Man` in the "Class hierarchy" view. `Joe` and `John` will be shown both in the "Instances" and "Instances (inferred)" views.
6) Select class `Person` in the "Class hierarchy" view. "Instances" view should show nothing, but "Instances (inferred)" view should show  `Joe` and `John`, however that is also empty now.

See screen shots below:
![screenshot from 2015-10-28 16 27 24](https://cloud.githubusercontent.com/assets/2441046/10806784/bff93418-7d95-11e5-9b57-e03aa5706183.png)
![screenshot from 2015-10-28 16 28 00](https://cloud.githubusercontent.com/assets/2441046/10806790/c831f6e2-7d95-11e5-9f64-9d829b76e580.png)

**Comment by matthewhorridge** [comment]
It shows *direct* instances of the selected class.  Hence, nothing is shown for Person in this ontology.
