### ISSUE TITLE
Add an option to hide deprecated classes in the class tree

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/protege#270]
OBO ontologies can have a lot of obsolete (deprecated) classes in them.  There should be an option to hide these.

**Comment by cooperl09** [comment]
It would be great if this could be set in the preferences rather than having to do it each time an ontology is opened.

**Comment by matthewhorridge** [comment]
> It would be great if this could be set in the preferences rather than having to do it each time an ontology is opened.

Good suggestion.  At the moment it's on a per-hierarchy view basis, which is why this hasn't been implemented so far – it would probably make sense to have this as a global preference.

**Comment by Public-Health-Bioinformatics** [comment]
I second this. We were discussing it over in https://github.com/ontodev/robot/issues/259#issuecomment-417965353
where currently Gene Ontology & others use a "Obsolete Class" to hide deprecated classes from top-level view.  Having a feature to hide hidden classes from top level by default would be great.

**Comment by matthewhorridge** [comment]
@Public-Health-Bioinformatics this is already available. See the "Display deprecated (obsolete) entities" menu item.  I recommend that you download the 5.5-beta2 version as there's some improvements in there for editing biomedical ontologies.  You can get it here:

https://github.com/protegeproject/protege-distribution/releases/tag/v5.5.0-beta-2

**Comment by matthewhorridge** [comment]
p.s. if you don't want to try the 5.5 beta, for whatever reason, the functionality to hide obsolete classes is present in the 5.2 release

**Comment by Public-Health-Bioinformatics** [comment]
Hi, Matthew, thanks for that quick response.  Oy - I didn't notice that menu item on my 5.2, sorry!  , I will try out 5.5 beta too.

But one last question, It appears there is no "memory" to that option, opening and closing protege leads to forgetting selection, so deprecated terms are displayed by default.  Thoughts/plans about that? I'm thinking for educational purposes as more deprecation occurs into the future, it would be better to switch default to be that deprecated terms aren't shown; then it becomes an "esperienced user" option to show them, so meat of ontology is more clearly visible from the get-go.

At any rate consider this closed...

**Comment by matthewhorridge** [comment]
Hi Damion,
Your arguments make sense.  Deprecated classes hidden by default.  I'll file an issue for this.  
The setting is on a per view basis, but I think it would make more sense to have this as a global option that gets persisted.

**Comment by cooperl09** [comment]
Agreed- see my comment above

**Comment by alanruttenberg** [comment]
Perhaps there should be a checkbox on the search window as to whether you want to see them or not in search results.
