### ISSUE TITLE
Missing entity edition buttons in Class Usage

### ISSUE THREAD

**Issue by jgrzebyta** [protegeproject/protege#274]
I found that in commit 14947e82815c9614529ea71f7a4e7285bc19050d There is missing edition buttons (*Annotations*, *Remove*, *Edit*) on the right side of an entity within **Class Usage** panel. See attached image.

![editors](https://cloud.githubusercontent.com/assets/6738268/11218438/e8dfb1ba-8d4c-11e5-9c86-7e548d03bcca.png)

**Comment by matthewhorridge** [comment]
There have never been any buttons there - to the best of my knowledge.

**Comment by jgrzebyta** [comment]
Sorry. My fault. I found that panel Description disappeared. just needed to
reset the view.
