### ISSUE TITLE
Add support for JSON-LD

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/protege#278]
Add support for saving and loading ontologies written in JSON-LD

**Comment by akuckartz** [comment]
:smile:

**Comment by katsi** [comment]
Why was this opened and closed? I am interested in protege supporting also the JSON-LD format.

**Comment by rsgoncalves** [comment]
Protégé supports JSON-LD format since the issue was closed.

**Comment by rdewaele** [comment]
It seems that JSON-LD is only partially supported, as it does not seem to be able to handle any files using the `@graph` keyword.

For example, when loading the library example from the json-ld playground (https://json-ld.org/playground/), the following error is reported:

`ERROR  02:05:49  An error occurred whilst loading the ontology at file:/tmp/test.owl. Cause: Not a valid (absolute) URI: @context`

The expanded version of this example does not include `@`-keywords and seems to load fine.

Shall I open a new issue, or do we re-open this one?

===

For convenience, the JSON-LD file that is served on the JSON-LD playground included below:

```
{
  "@context": {
    "dc": "http://purl.org/dc/elements/1.1/",
    "ex": "http://example.org/vocab#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "ex:contains": {
      "@type": "@id"
    }
  },
  "@graph": [
    {
      "@id": "http://example.org/library",
      "@type": "ex:Library",
      "ex:contains": "http://example.org/library/the-republic"
    },
    {
      "@id": "http://example.org/library/the-republic",
      "@type": "ex:Book",
      "dc:creator": "Plato",
      "dc:title": "The Republic",
      "ex:contains": "http://example.org/library/the-republic#introduction"
    },
    {
      "@id": "http://example.org/library/the-republic#introduction",
      "@type": "ex:Chapter",
      "dc:description": "An introductory chapter on The Republic.",
      "dc:title": "The Introduction"
    }
  ]
}
```

**Comment by matthewhorridge** [comment]
@rdewaele please open a new, more specific, issue.  Thanks  a lot.
