### ISSUE TITLE
Dataproperty assertion set to false instead of true (Protege Desktop 5.0.0 beta-15)

### ISSUE THREAD

**Issue by andre-rifaut** [protegeproject/protege#285]
Script to produce the bug:
1) start protege desktop (see below tech infos)
2) select "Entitites" tab or "individuals" tab and create an individual (with "<>+" icon) with any name
3) click on the "+" next to "Data property assertion" to add a new data property for that individual.
4) when in the modal window "Data Property", at left side select "topDataProperty", 
5) then, at right side, type-in TRUE (or True) and click the "OK" button.
Finally the value will be set to "false" and the boolean type is automatically set.
Alternative to step 5: If we type-in true, the value will be set to true as expected.

Issue: when typing-in abcdef, this is interpreted as a string, and when typing-in 1, this is interpreted as a number, but True, tRUe, ... are interpreted as false. Why not interpreted them as string ?
When loading a .ttl file:
"tRUe"
is interpreted as a string, and
"tRUe"^^xsd:boolean  
is interpreted as false (still misleading).

I guess, the following misleading code is used somewhere:
if( "true"==toLower(input_string)) then Value=true else Value=false

Note: I got a similar bug in java 10 years ago: standard java libraries wrote "True" in property files, and interpreted it as false when re-read ...

Tech infos:
Protege Desktop (Version 5.0.0, Build = beta-15)
Platform:
    Java: JVM 1.8.0_66-b18 Memory: 506M
    Language: en, Country: GB
    Framework: Apache Software Foundation (1.5)
    OS: windows7 (6.1)
    Processor: x86

**Comment by matthewhorridge** [comment]
I've just had a quick look at this.  The OWL API parses the literal object when it is created so if I try to parse  anything but "true" or "1" with a datatype that is an xsd:boolean the value will be converted to be false.  (Inline with some of the points in you issue I think).

**Comment by andre-rifaut** [comment]
Thanks a lot for your fixing this very quickly. Protege is an excellent tool.
I understand that at some design step, shortcuts are taken to make project progress. Software tools are not sufficiently good to trace that. We still need the next generation of ontology-based software engineering tools ;-)
