### ISSUE TITLE
Build failure introduced in f3357f982a57e2f3ce05078fb9e4f7dc304d3670

### ISSUE THREAD

**Issue by aborkowski** [protegeproject/protege#287]
I encountered the following build failure while trying to build the current master branch (376f54b9fc69a7a72ffea0381ebb4c765c05063b) from source (as per [build instructions](https://github.com/protegeproject/protege/wiki/Building-from-Source)):
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (default-compile) on project protege-editor-owl: Compilation failure
[ERROR] /Users/alex/Repositories/github.com/protegeproject/protege/protege-editor-owl/src/main/java/org/protege/editor/owl/model/entity/CustomOWLEntityFactory.java:[46,17] constructor DefaultUserNameProvider in class org.protege.editor.owl.model.user.DefaultUserNameProvider cannot be applied to given types;
[ERROR] required: org.protege.editor.owl.model.user.UserNamePreferencesManager
[ERROR] found: no arguments
[ERROR] reason: actual and formal argument lists differ in length
```
I traced this back to commit f3357f982a57e2f3ce05078fb9e4f7dc304d3670 where class org.protege.editor.owl.model.user.DefaultUserNameProvider lost its default constructor.

**Comment by tudorache** [comment]
Fixed the compilation issue.

@matthewhorridge, please take a look at the fix.
