### ISSUE TITLE
Chinese characters of imported ontologies don't display correctly

### ISSUE THREAD

**Issue by faeriebug** [protegeproject/protege#292]
when I use protege 5.0 to create the first owl ontology, it displays the chinese characters correctly. But when I create another owl ontology and import the first owl file, ontologies from the first owl file become boxes in UI. As shown below:

first owl file. Chinese character display correctly:

![image](https://cloud.githubusercontent.com/assets/1785650/11836504/25e19f8a-a416-11e5-9541-3429d16ac402.png)

the second owl file. import the first owl file. chinese characters become boxes.:

![image](https://cloud.githubusercontent.com/assets/1785650/11836546/5ad7a3e2-a416-11e5-8541-29220522dfce.png)

 but note that the title of class hierarchy displays correctly!

This is really confusing. please help. thx :-)

**Comment by faeriebug** [comment]
Platform:
Java: JVM 1.8.0_40-b26  Memory: 466M
Language: zh, Country: CN
Framework: Apache Software Foundation (1.7) 
OS: windows8 (6.3)
Processor: x86-64

**Comment by tudorache** [comment]
Could you post a small example ontology that shows the behavior?

**Comment by matthewhorridge** [comment]
Closing this as a duplication of an issue that is being actively worked on (#818).  Please add further comments to #818.
