### ISSUE TITLE
Problems with the Hermit Reasoner Plugin 

### ISSUE THREAD

**Issue by ummAssiya** [protegeproject/protege#294]
I tested Protege 5 beta, build 21 and have problems with the included Hermit reasoner. 
Please see the error messages from the log. 
[ProtegeLog.txt](https://github.com/protegeproject/protege/files/67973/ProtegeLog.txt)

**Comment by csnyulas** [comment]
Did you try with HermiT 1.3.8 or HermiT 1.3.8.413?
I also have similar exceptions when I try with HermiT 1.3.8, but with 1.3.8.413 it works. I think the HermiT 1.3.8 should not have been included in this release. We would probably take it out in the next beta.

**Comment by matthewhorridge** [comment]
HermiT 1.3.8 isn't bundled with this release.  Only 1.3.8.413 is bundled.

**Comment by csnyulas** [comment]
Well, I thought also that it isn't bundled, but it always appears for me in a fresh installation of Protege 5.0.0. Beta 21. It is a bit strange.

**Comment by ummAssiya** [comment]
As to the version of HermiT,  I am not exactly sure. It came with the Protege 5.0.0 Beta 21 (i.e. I did not install the HermiT reasoner myself) and according to the Protege log it's "HermiT Reasoner (1.3.8)" (see my log file in my first post). 
See also the screenshot:
![clipboard01](https://cloud.githubusercontent.com/assets/6398283/11926842/4088a224-a7c8-11e5-961a-775ddd6b208e.jpg)

**Comment by tudorache** [comment]
Hermit 1.3.8 is picked up from the cached plugins from previous installations from the user home folder/.Protege/plugins. I have just confirmed that on several installations.

Solution: remove the .Protege folder from the user home directory.

**Comment by ummAssiya** [comment]
You are right @tudorache, the HermiT plugin was picked up from my .protege folder. I deleted it, dowloaded HermiT 1.3.8.413 and now it works. Thank you!
