### ISSUE TITLE
Improve Log view in Protege: Enable copy-pasting 

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#295]
At the moment it is not possible to copy-paste from the internal Log view of Protege (the one that pops up when you open the Window -> Show log menu, or if click on the red triangle with exclamation mark after an exception occurred). Having this feature would enlighten problem reporting significantly, especially for non-computer-savvy users.

**Comment by matthewhorridge** [comment]
Works for me.  CMD+C on a Mac.  Which platform are you on?

**Comment by csnyulas** [comment]
Linux, but it seems to work now. Really strange. I know it wasn't working before. Anyway, I just checked and it works on Windows, too.
Now that I was able to do the copy-paste I observed another annoying thing for which I'll open a separate issue. I will close this issue, since it seems to work now.
