### ISSUE TITLE
b5-21 fails to detect when underlying ontology file has been modified

### ISSUE THREAD

**Issue by cmungall** [protegeproject/protege#300]
I'm using b21 on OS X 10.11, launching protege via `run.command`

Previously Protege would auto-detect if the owl file I was editing (or any file in the import chain) was modified outside Protege. This worked in all previous versions I tried, up to and including the beta18 snapshot. However, this feature seems to be gone. Modifying the underlying file in a text editor has no effect, Protege does not detect the change.

**Comment by dosumis** [comment]
This functionality is very important to me.  Potentially a blocker to adoption.

**Comment by matthewhorridge** [comment]
We'll investigate this as a matter of priority.

**Comment by matthewhorridge** [comment]
Please can you confirm whether or not you get the dialog that prompts a reload?  I get the dialog that prompts the reload, but then a failure after this due to some internal changes in the OWL API.

**Comment by cmungall** [comment]
No dialog box, nothing on the console.

**Comment by matthewhorridge** [comment]
Just to let you know, I'm now able to reproduce this.  Working on a fix.

**Comment by csnyulas** [comment]
Reopening this issue, as it seems to be still an issue in P5.2 and P5.5 beta.
