### ISSUE TITLE
"Check for downloads now" button is missing in protege-5-beta-21

### ISSUE THREAD

**Issue by ghxiao** [protegeproject/protege#301]
Hi,

It seems that the "Check for downloads now" button is missing in protege-5-beta-21 and therefore we are not able to install plugins within protege.

----

protege-5-beta-17

![protege-5-beta-17](https://cloud.githubusercontent.com/assets/1907371/12178424/a6b6be76-b571-11e5-82e9-8c872fbcbf53.png)

----

protege-5-beta-21

![protege-5-beta-21](https://cloud.githubusercontent.com/assets/1907371/12178426/aa7eb414-b571-11e5-81ca-85e62e9c222b.png)

----

**Comment by johardi** [comment]
We have moved the button from the preference window to menu item "File > Check for plugins..."

**Comment by ghxiao** [comment]
Thanks for the clarification.
