### ISSUE TITLE
Object Property hierarchy is flat in p5beta21

### ISSUE THREAD

**Issue by cmungall** [protegeproject/protege#306]
Tested on ro.owl,

<img width="558" alt="screen shot 2016-01-25 at 7 44 23 am" src="https://cloud.githubusercontent.com/assets/50745/12555753/7fbd7516-c337-11e5-8282-b139558c7d50.png">

Note the AP hierarchy is fine.

Also reported by a user on protege users list

**Comment by matthewhorridge** [comment]
I'm still investigating, but it looks like this is a bug in the OWL API EntitySearcher.

**Comment by matthewhorridge** [comment]
Confirmed OWL API bug.  Issue file:  https://github.com/owlcs/owlapi/issues/485

I will come up with a work around for Protege.
