### ISSUE TITLE
Imported ontologies are loaded using the incorrect method

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/protege#314]
For some reason imported ontologies are loaded using the ```makeImportsLoadRequest``` method on OWLOntologyManager.  This shouldn't be used - the regular load method should be used.

**Comment by MarinusVonhof** [comment]
Hello Matthew, sure this adjustment is ok? Opening a file with an owl:imports relation to an other ontologie does not automatically load/merge the other file. In protege 5.0.0.-beta-23 that was functioning well.
