### ISSUE TITLE
Cannot open Property Matrix in Protege 5

### ISSUE THREAD

**Issue by longmeili** [protegeproject/protege#317]
Hi, is the plugin matrix_1.1.2 compatible with Protege 5? Whenever I open Property matrix view errors will occur, the log is below:
![log for protege5](https://cloud.githubusercontent.com/assets/15227853/12844694/450da27e-cc01-11e5-8f7d-a26a7825353f.png)

**Comment by matthewhorridge** [comment]
I've filed an issue on the github account for this plugin here:  https://github.com/co-ode-owl-plugins/matrix/issues/1.  I'm closing this issue here.

**Comment by matthewhorridge** [comment]
There's a new release of this plugin that works with Protege 5.0.0
https://github.com/co-ode-owl-plugins/matrix/releases

**Comment by yasenstar** [comment]
Thanks, this version works with Protege 5.6.3, just tested
