### ISSUE TITLE
Ontology source changed widget not closeable

### ISSUE THREAD

**Issue by jgrzebyta** [protegeproject/protege#323]
I use 2 instance of Protege. One is for copying axioms from some ontology into **urn:temp** which I save as file. The second one is for merging **urn:temp** with a final ontology. 

When I change **urn:temp** file with one instance I have the warning message "Ontology has changed outside of Protege". When I click *Yes* to confirm reloading the widged is not closed. The ontology itself is reloaded.

Screenshot:

![error](https://cloud.githubusercontent.com/assets/6738268/12986293/68dc19e6-d0ee-11e5-9ac6-b88a5a801254.png)

**Comment by matthewhorridge** [comment]
Is this beta-21?

**Comment by jgrzebyta** [comment]
Yes. Indeed. In Linux.
java -version gives:
> openjdk version "1.8.0_66-internal"
> OpenJDK Runtime Environment (build 1.8.0_66-internal-b17)
> OpenJDK 64-Bit Server VM (build 25.66-b17, mixed mode)

**Comment by matthewhorridge** [comment]
This problem is fixed in beta-23
