### ISSUE TITLE
Ontology-loading error dialog contains multiple 'RioParserImpl' entries

### ISSUE THREAD

**Issue by rsgoncalves** [protegeproject/protege#331]
![screen shot 2016-02-19 at 11 48 42](https://cloud.githubusercontent.com/assets/4361140/13187612/11963a68-d701-11e5-987f-2814c05cd4ea.png)

Ideally the tabs should be labeled with the document format that each particular RioParser is attempting to load. Otherwise one would have to check the console output (below) and identify which tab corresponds to what document format in order to identify the parsing error(s).

    An error was thrown: Could not load imported ontology: <http://www.owl-ontologies.com/assert.owl> Cause: Problem parsing http://www.owl-ontologies.com/assert.owl
    Could not parse ontology.  Either a suitable parser could not be found, or parsing failed.  See parser logs below for explanation.
    The following parsers were tried:
    1) org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser@262d4b62
    2) org.semanticweb.owlapi.owlxml.parser.OWLXMLParser@d30b546
    3) org.semanticweb.owlapi.functional.parser.OWLFunctionalSyntaxOWLParser@58253131
    4) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.RioTurtleDocumentFormatFactory@95fd655c
    5) org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxOntologyParser@502a36cf
    6) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.NQuadsDocumentFormatFactory@6f9c39ad
    7) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.RDFJsonDocumentFormatFactory@cd748dc3
    8) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.NTriplesDocumentFormatFactory@937ecd36
    9) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.TrigDocumentFormatFactory@27e81c
    10) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.RDFJsonLDDocumentFormatFactory@dcacc47d
    11) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.BinaryRDFDocumentFormatFactory@3bf24493
    12) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.N3DocumentFormatFactory@9a5
    13) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.RioRDFXMLDocumentFormatFactory@69b9a3bc
    14) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.TrixDocumentFormatFactory@27e82d
    15) org.semanticweb.owlapi.rdf.turtle.parser.TurtleOntologyParser@230d6fb0
    16) org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser@53655de7
    17) org.semanticweb.owlapi.krss2.parser.KRSS2OWLParser@56ab0dd8
    18) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.RDFaDocumentFormatFactory@264e8d
    19) org.coode.owlapi.obo12.parser.OWLOBO12Parser@7d6ac202

**Comment by matthewhorridge** [comment]
Closed.  Fixed duplicate #414
