### ISSUE TITLE
Current version of installed plug-ins is not shown

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#337]
The current installed version of the plug-ins is important information that used to be shown in the "Automatic Update" window, which comes up on checking on plug-in updates (through the File -> Check for plugins... menu), but it is not any more:

![protege_current_version_of_plugins_not_shown](https://cloud.githubusercontent.com/assets/2441046/13415147/5c2256f2-df0d-11e5-84bb-d97e5ccb9427.png)

**Comment by csnyulas** [comment]
On the other hand, the version numbers of the bundled plugins are shown in the "About" box

![screenshot protege plugins versions](https://cloud.githubusercontent.com/assets/2441046/13587479/718e8b80-e47d-11e5-92bf-7928ec8b6627.png)

**Comment by matthewhorridge** [comment]
It looks like you have those plugins installed.  Please can you confirm that that's the case?  
Some plugins, such as the SWRL tab are missing an update-url header in the Manifest that causes them to show up as downloads rather than updates (if a plugin is a download then it is assumed there is not  current version installed).  It's probably time for a rewrite/cleanup of the updater code.

**Comment by csnyulas** [comment]
For the record:
The beta-24 snapshot had SWRLTab plugin included as `swrltab-plugin-1.0.0-beta-10.jar`. When I looked at the list of available updates SWRLTab had version `1.0.0.beta-13` listed. After updating SWRLTab, another jar file, `swrltab.jar` appeared. @martinjoconnor was not sure where this file (containing no version information in its name) came from. In any case after this upgrade I got the error message mentioned in #356.

This all may be fixed once protegeproject/swrltab-plugin#19 gets fixed, however I wonder if the line
```
<plugin name="SWRLAPI Plugin for Desktop Protege" version="1.0.5">
```
in the  [plugin.xml file] (https://github.com/protegeproject/swrltab-plugin/blob/37d3569b53dee813a83005ade55e08b42cacc425/plugin.xml#L4) referring to version **1.0.5.** instead of **1.0.0.(beta-X)**, doesn't have something to do with all of this.

**Comment by martinjoconnor** [comment]
I corrected my plugin.xml to now say 1.0.0.

Do I have to keep this in exact sync with the release version?

**Comment by matthewhorridge** [comment]
As far as I know (I wasn't responsible for OSGi) the version number in the plugin.xml isn't used anymore

**Comment by csnyulas** [comment]
Although my earlier comment is true, and probably relevant to this issue, I just realized that I misunderstood @matthewhorridge 's earlier question (the one before closing this issue), and would like to provide an answer to that question, too.

The plugins listed in the "Autoumatic update" window are not the ones that I had already installed in my Protege installation. I.e. I do not have those plugins in my `plugins` directory. The only exception being the SWRLTab (and this is what my previous comment is about).

**Comment by matthewhorridge** [comment]
In the current UI (now the old UI) current version will be blank if the plugin is not installed.  The SWRL tab plugin had an incorrect id in the update file, which is why it was always displayed as a new plugin that was available to be installed.
