### ISSUE TITLE
Editing the rdfs:label in "Individuals by class" tab selects the next Class in the hierarchy list

### ISSUE THREAD

**Issue by bjonnh** [protegeproject/protege#338]
If the rdfs:label was not set before, it doesn't change the Class in the hierarchy list.

Step to reproduce:
- Add two classes 'A' and 'B'
- Create an instances of 'A' called 'aa'
- Go to « Individuals by class » tab
- Add a rdfs:label to 'aa'
- Try to edit the rdfs:label of 'aa'

Then the class "B" gets selected in class hierarchy.

Happens everytime. Didn't notice that in previous versions, but I can't say for sure it wasn't there already.

**Comment by csnyulas** [comment]
In my case the selection changes from aa, to A (not B), but we observed this involuntary selection change, as well. It is probably the same as #346.
