### ISSUE TITLE
Create annotation property button is disabled initially

### ISSUE THREAD

**Issue by tudorache** [protegeproject/protege#340]
The initial display of the annotation properties in the entities tab, shows all buttons disabled. In order to create an annotation property, a user needs to select first an existing annotation property, and the click on create at the same level, which is not intuitive at all. There should be a create annotation property button in the Annotation Properties tab.

![screenshot - 03022016 - 02 39 52 pm](https://cloud.githubusercontent.com/assets/2709502/13478230/f10d9c0e-e084-11e5-8a12-ac77a681d7e9.png)

**Comment by csnyulas** [comment]
This is still not working in the latest 1.0.0.beta-24 snapshot.

**Comment by matthewhorridge** [comment]
It's just not in the latest published snapshot.

**Comment by csnyulas** [comment]
Super!
