### ISSUE TITLE
Annotation editor dialog does not clear the IRI value from previous edits

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#345]

**Comment by matthewhorridge** [comment]
Can you provide any more detail about this?

**Comment by csnyulas** [comment]
Sorry for not providing more details, I was in a hurry when I created the issue, and I thought that may be the subject would be enough.
When you try to create an annotation value that is an IRI (for example, if you want to provide an URL to an image to annotate for an entity), and select the "IRI Editor" tab in the new annotation value editor, you will get the IRI field filled in with some value. This value seems to be the previous IRI value that you added earlier to an entity, or the ontology IRI if you did not use the IRI Editor before.
