### ISSUE TITLE
Entity selection changes seemingly randomly when trying to edit an annotation property value

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#346]
To reproduce:
- In the "Entities" tab select different entities in different views
- create an annotation on an entity
- edit that annotation by clicking on the circle icon.
- observe that the selection changed to an entity (class or property) that is selected in one of the views, which may or may not be visible at the moment

This behaviour may be related to allowing multiple selections in different views, so there is a chance that a proper fix to #335 may solve this issue, too.

**Comment by rsgoncalves** [comment]
It does seem to be related to selections in other views, though this wasn't a problem before. I couldn't replicate the above until I selected topObjectProperty (in the Entities tab). And then when editing the annotation property value of a class, the selection switch to topObjectProperty.

**Comment by matthewhorridge** [comment]
This seems to be caused by the initialisation of the annotation editor:

```AbstractOWLEntityHierarchyViewComponent.setShowDeprecatedEntities```

which causes a reload of the tree, followed by a re-selection.

**Comment by rsgoncalves** [comment]
Here are the steps I used to reproduce this, using only the Entities Tab:

* Create class A
* Add rdfs:comment annotation assertion to A (value is irrelevant)
* Select owl:TopObjectProperty in the object property view
* Select class A again
* Edit rdfs:comment annotation on A
* Notice the selection switches to owl:TopObjectProperty

**Comment by johardi** [comment]
Another steps to reproduce:
 1. Create class A and B in 'Entities' tab,
 2. Switch to 'Individuals by class' tab and select class B in the 'Class hierarchy',
 3. Go back to 'Entities' tab and select class A.
 4. Add an annotation, e.g., rdfs:comment "Blah",
 5. Edit the annotation and the selection immediately "jump" to class B
