### ISSUE TITLE
Master branch:  Popup menu items appear on the main menu bar

### ISSUE THREAD

**Issue by wismill** [protegeproject/protege#362]
Hi, there is a bug in the menu bar (see screenshot). Possible culprit: d9a985b4

- OS: Linux
- Java: 1.8
- Protégé: git/master (ddb7d813e273fcb096f336c7295a184d27aa4ed4)

![screenshot from 2016-03-09 07-37-59](https://cloud.githubusercontent.com/assets/3842915/13627459/d149f548-e5ca-11e5-9ead-e87217f17735.png)

**Comment by csnyulas** [comment]
The latest 5.0.0.beta-24 snapshot on Ubuntu with Unity does not have this problem.

This is my setup as reported by Protégé:
```
------------------------------------ Protégé ----------------------------------- 
Protégé Desktop 
Version 5.0.0, Build beta-24-SNAPSHOT 
 
 
----------------------------------- Platform ----------------------------------- 
Java: JVM 1.8.0_40-b26  Memory: 466M 
Language: en, Country: US 
Framework: Apache Software Foundation (1.7)  
OS: linux (3.13.0-68-generic) 
Processor: x86-64
```

A few questions:
- @wismill what graphical shell do you use?
- Is this hapenning all the time, or only ocassionally (can you describe in what situation is happening)?
- Are you running your own build? If yes, would you mind giving a try to our snapshots?

**Comment by matthewhorridge** [comment]
Things also look fine for me on OS X.  I'll have a deeper look though.

**Comment by wismill** [comment]
@csnyulas I use Gnome 3.18; bug is happening all the time; I just compiled the official master branch.
@matthewhorridge your commit fixed it. Thanks.
