### ISSUE TITLE
Drag and drop does not work for classes not involved in subsumptions (beta24)

### ISSUE THREAD

**Issue by rsgoncalves** [protegeproject/protege#372]

**Comment by matthewhorridge** [comment]
Have you got it enabled?  There is a preference item to disable it.

**Comment by tudorache** [comment]
I can reproduce this, and yes, the preference is enabled.

Some drag-n-drop operations work, others do not. I did not find the rule, yet.

**Comment by matthewhorridge** [comment]
Are you saying it works when you hold down some keys and not others?  It's working for me without holding down any modifier keys.

**Comment by tudorache** [comment]
No, I am not holding down any modifier key, just pure dnd in the tree.

It seems there are some classes for which it never works, while it works for others.

**Comment by matthewhorridge** [comment]
It will only (has only ever) for primitive classes.  Can you provide a small test case I can try out?

**Comment by tudorache** [comment]
I attached a small test case. I can move the class a, but never rrr.

All classes are primitive. After restarting protege, the dnd behavior is different. I cannot move some of the classes I could before. I could not move rrr in any of the sessions.

[t.owl.zip](https://github.com/protegeproject/protege/files/173091/t.owl.zip)

**Comment by matthewhorridge** [comment]
The problem seem to occur if there isn't a subclass axiom with the class being dragged in the subclass position.  For example,

```
Ontology(SubClassOf(:A :B))
```

will allow ```:A``` to be dragged and dropped elsewhere, but

 ```
Ontology(Declaration(:A), Declaration(:B))
```

will not allow ```:A``` to be dragged and dropped on to ```:B```
