### ISSUE TITLE
Possibly undesirable default prefixes are added during first save

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#375]
When saving ontologies the first time a default prefix declaration will be added to the ontology. This default prefix is generated from the ontology IRI followed by a hash (`#`). This is often undesirable, and can lead to problems later (for example with Cellfie), especially if the new entity name preference is set to use slash (`/`) as the separator between the namespace and the local name, and/or entities in the ontology use the `/` separator instead of `#`.

This happens when we save the ontology in most available formats (including RDF/XML, Functional OWL, Turtle), but I did not observe it with the Manchester syntax.

It would be preferable to either not add any default prefix to the ontology automatically, or if one needed to be added (for technical reasons), the default prefix should use the new entity name separator set in the preference after the ontology IRI.

**Comment by matthewhorridge** [comment]
It's best not to rely on these prefixes at all.  They are not really used anywhere within Protege unless prefix rendering is activated.  When saving, each format is basically free to do what it likes. 

Can you explain what problems occur for Cellfie?

**Comment by matthewhorridge** [comment]
we can change this btw, but Cellfie should work with the new entity settings within Protege.

**Comment by csnyulas** [comment]
AFAIK, [Cellfie](https://github.com/protegeproject/cellfie-plugin/) works with the new entity settings to resolve entity names only if there is no default prefix is specified in the ontology, which is the case for any newly generated ontology. However if the ontology is saved and reloaded there will be a default prefix ending with `#`, which may be appropriate for some ontologies but not for others. 

I think that Protege should not create an arbitrary default prefix. So unless there is a clear need for including default prefixes in ontology files, AND we have a good algorithm to guess what should be the default prefix for each ontology, I would suggest that we fix this, if possible.

**Comment by matthewhorridge** [comment]
Thanks for the details,

> I think that Protege should not create an arbitrary default prefix

Having looked into this a bit more, Protege currently doesn't specify any prefix.  The OWL API generates a default prefix.  Also, it's not arbitrary (it's the ontology IRI plus a hash - consistently).

Furthermore, different XML file formats may use different default namespaces.  For example, the default for OWL/XML is the OWL prefix.  Would Cellfie create new entities with the OWL prefix if the ontology was loaded from an OWL/XML document?

Having Cellfie rely on prefixes specified in ontology documents seems inherently flaky (these could be changed externally or they could be bound to different prefixes in different documents in an imports closure).  We should chat about a better way of doing things here.

CC'ing @johardi in on this.

**Comment by csnyulas** [comment]
Thanks a lot for looking in to this. I agree that is not ideal that Cellfie relies on the default prefix, but it this is how [MappingMaster](https://github.com/protegeproject/mapping-master/) tries to resolve entity names in the transformation rules. There are many historical reasons for this (for example the fact that the rules are suppose to be easy to write and read, they are stored independently from the ontology, etc) and it would be a big undertaking to implement such a fundamental change in MM. I hope it will be fixed one day, though.
In the meantime I appreciate all the insights you provided about how these default prefixes end up in the ontology. Let's discuss how we can go about them.

PS: When I said that the generated default prefixes are arbitrary, I did not mean that they are built arbitrarily, but rather that their appropriateness for a given ontology is arbitrary (i.e. the generated default prefix may or may not be appropriate for a given ontology)

**Comment by danielepantaleone** [comment]
I think I'm hitting this issue as well, but I seem to experience it only when serializing the ontology in Functional OWL. Basically whenever I use this format, the prefix I set is never used. In place, the default prefix `:` is used (which I did not specify). Here's the code I'm using (a part of it):

```java
OWLOntologyManager man = OWLManager.createOWLOntologyManager();
OWLOntology ontology = man.createOntology(IRI.create("http://www.dis.uniroma1.it/example/"));
OWLDataFactory dataFactory = man.getOWLDataFactory();
PrefixManager pm = new DefaultPrefixManager();
pm.setPrefix("example", "http://www.dis.uniroma1.it/example/");
OWLClass pizza = dataFactory.getOWLClass("example:pizza", pm);
OWLDeclarationAxiom declarationAxiom = dataFactory.getOWLDeclarationAxiom(pizza);
man.addAxiom(ontology, declarationAxiom);
FunctionalSyntaxDocumentFormat ontoFormat = new FunctionalSyntaxDocumentFormat();
ontoFormat.copyPrefixesFrom(pm);
man.setOntologyFormat(ontology, ontoFormat);
self.man.saveOntology(ontology, new StringDocumentTarget());
```

which produces the following:

```
Prefix(:=<http://www.dis.uniroma1.it/example/>)
Prefix(owl:=<http://www.w3.org/2002/07/owl#>)
Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>)
Prefix(xml:=<http://www.w3.org/XML/1998/namespace>)
Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>)
Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>)
Prefix(example:=<http://www.dis.uniroma1.it/example/>)

Ontology(<http://www.dis.uniroma1.it/example/>

Declaration(Class(:pizza))
)
```

If however I switch `FunctionalSyntaxDocumentFormat` to  `ManchesterSyntaxDocumentFormat` or `TurtleDocumentFormat`, the prefix I set is correctly used:

```
Prefix: example: <http://www.dis.uniroma1.it/example/>
Prefix: owl: <http://www.w3.org/2002/07/owl#>
Prefix: rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
Prefix: rdfs: <http://www.w3.org/2000/01/rdf-schema#>
Prefix: xml: <http://www.w3.org/XML/1998/namespace>
Prefix: xsd: <http://www.w3.org/2001/XMLSchema#>

Ontology: <http://www.dis.uniroma1.it/example/>

Class: example:pizza
```

```
@prefix : <http://www.dis.uniroma1.it/example/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix example: <http://www.dis.uniroma1.it/~graphol/example/> .
@base <http://www.dis.uniroma1.it/example/> .

<http://www.dis.uniroma1.it/example/> rdf:type owl:Ontology .

example:pizza rdf:type owl:Class .
```

**Comment by matthewhorridge** [comment]
Closing this because it's been closed in the OWL API issue
