### ISSUE TITLE
Context menu actions disappear when entity rendering was changed

### ISSUE THREAD

**Issue by LorenzBuehmann** [protegeproject/protege#383]
Hi,

I'm working on Protege-5.0.0-beta-24 and saw a strange behaviour if I use the context menu of the asserted class hierarchy tree: 
After start everything is fine and all actions are available, but once I change the entity rendering some actions disappear. If I restart Protege, all actions are available again, now in addition to the new entity rendering. Anybody knows what's going wrong here? Looks like some weird bug.

My system:
Ubuntu 15.10
Java 1.8.0_77

**Comment by matthewhorridge** [comment]
I'm not able to reproduce this.  Does it always happen?

**Comment by LorenzBuehmann** [comment]
Hm, me neither. Looks like some issue with the Protege version at the time of opening this issue. With a fresh Protege-5.0.0-beta-24 and Protege-5.0.0-RC1 everything is working fine. Sorry, can be closed indeed.

**Comment by matthewhorridge** [comment]
Great.  Thanks for closing this.
