### ISSUE TITLE
How to develop my own Java application with protege?

### ISSUE THREAD

**Issue by smilencezq** [protegeproject/protege#384]
Hello, I'm a newer to Protege. I want to develop a Java application, which will have an OWL related module to deal with OWL files,read,write and update. If I can use some cores of Protege (Not Whole), that'll be better. Now I'm wondering how to build a develop enviroment with Eclipse. Waiting for answers, Thank you

**Comment by tudorache** [comment]
To build an application, you can use the OWL API (https://github.com/owlcs/owlapi/wiki) that Protege also uses to handle OWL ontologies.

Closing this issue. If you have further questions, please post on the Protege user or dev lists:
http://protege.stanford.edu/support.php
