### ISSUE TITLE
OWLViz Imports Graph broken in recent betas (Windows)

### ISSUE THREAD

**Issue by johanwk** [protegeproject/protege#394]
The OWLViz Imports Graph is broken in Protégé 5.0.0 beta-24, on Windows 7 with Graphviz 2.36. 

When opening Protégé, the current, untitled ontology is displayed with a trailing ")" in the graph node title. Maybe this gives a clue to what is wrong.

Loading an ontology that has imports, the nodes are typically displayed all on top of each other.

**Comment by matthewhorridge** [comment]
I can reproduce this.  Thanks for the bug report.  I'm going to move this to the OWLViz repo though.

**Comment by matthewhorridge** [comment]
See https://github.com/protegeproject/owlviz/issues/9

**Comment by matthewhorridge** [comment]
Closing as this has been fixed in OWLViz 5.0.3
