### ISSUE TITLE
The Manchester entity renderer view should have a more informative title

### ISSUE THREAD

**Issue by tudorache** [protegeproject/protege#395]
Currently the title of the tab for the Manchester entity renderer is "Selected entity" (literally). Should be more informative, e.g., "Manchester entity renderer". The inner title is useful, but if the view is not selected, then the user has not idea what it represents.

This happens in the Entities tab, seems to work fine in the Individuals tab

![screenshot - 04292016 - 11 18 02 am](https://cloud.githubusercontent.com/assets/2709502/14925571/e8f78584-0dfc-11e6-8df5-1a6ccf9af81a.png)

**Comment by tudorache** [comment]
This behavior may be related to the exceptions thrown in #336. It works fine when the exception is not thrown (but I am not 100% of the causality)

**Comment by matthewhorridge** [comment]
Works as expected for me.  The tab title matches the view title, "Manchester Syntax Entity Rendering"

**Comment by tudorache** [comment]
I think it happens only the first time the view is activated, and if the exception is thrown.

**Comment by matthewhorridge** [comment]
Ah right.  The exception has something to do with it then.  Can you give me any steps to reproduce this?

**Comment by tudorache** [comment]
Will try to reproduce them. It seems that once it starts working, it works, just like the elusive rendering bug we once had.

**Comment by matthewhorridge** [comment]
Closing.  Please re-open this if you have a reproducible bug.
