### ISSUE TITLE
Protege error dialog failed to display the error message

### ISSUE THREAD

**Issue by johardi** [protegeproject/protege#396]
Protege shows an empty dialog. It happens to any plugins that utilize Protege error dialog UI.

![screen shot 2016-04-29 at 11 51 55 am](https://cloud.githubusercontent.com/assets/5062950/14926526/801b1e04-0e01-11e6-8afa-a0b94615445c.png)

**Comment by tudorache** [comment]
What are the steps to reproduce this?

**Comment by johardi** [comment]
For this example I use the SPARQL Query plugin. I made a syntax error, instead of typing "SELECT" I put "SLECT"
