### ISSUE TITLE
Preferences dialog does not fit on all displays

### ISSUE THREAD

**Issue by tudorache** [protegeproject/protege#397]
On a standard setup Dell laptop with Win 10, the resolution is 1280 x 800, and it is very hard to click on OK or Cancel, because the buttons are out of screen. The preference dialog should have a smaller height so that it fits on smaller resolution screens.

**Comment by csnyulas** [comment]
I agree. I use Protege in a Windows VM running on a 1280 x 1024 screen, and even there, although I can see the buttons, the `Preference` window feels too large.

There are only three tabs that would not fit the content in a smaller, let's say in a 875x650, window:
`Annotations`
'New Entities`
`Reasoner`

In `Annotations` we can fit the content if we put the check boxes in two columns. In `New Entities` we can reduce the size of some of the panels. I don't see what we could do in the ` Reasoner` tab to fit the content in the window, but I think it is not that bad if the users will need to scroll a bit, as they have to do this now as well.
