### ISSUE TITLE
OWLViz tab throws exception upon opening

### ISSUE THREAD

**Issue by samsontu** [protegeproject/protege#399]
Protege 5.0.0-RC1-SNAPSHOT 
Mac OS X, Protege.app edition
The error message says "An error related to DOT has occurred. This error was probably because OWLViz could not find the DOT application." However, the dot application is in the specified location. The 5.0.0.-beta-24 opens the OWLViz tab without any problem.

Level:       INFO
Time:        1461975116384
Message:     ------------------------------------ Protégé -----------------------------------

Level:       INFO
Time:        1461975116388
Message:     Protégé Desktop

Level:       INFO
Time:        1461975116389
Message:     Version 5.0.0, Build RC1-SNAPSHOT

Level:       INFO
Time:        1461975116390
Message:     

Level:       INFO
Time:        1461975116391
Message:     

Level:       INFO
Time:        1461975116391
Message:     ----------------------------------- Platform -----------------------------------

Level:       INFO
Time:        1461975116391
Message:     Java: JVM 1.8.0_40-b27  Memory: 3817M

Level:       INFO
Time:        1461975116391
Message:     Language: en, Country: US

Level:       INFO
Time:        1461975116391
Message:     Framework: Apache Software Foundation (1.7) 

Level:       INFO
Time:        1461975116391
Message:     OS: macos (10.11.4)

Level:       INFO
Time:        1461975116391
Message:     Processor: x86-64

Level:       INFO
Time:        1461975116392
Message:     

Level:       INFO
Time:        1461975116392
Message:     ------------------------------------ Plugins -----------------------------------

Level:       INFO
Time:        1461975116392
Message:     Plugin: Cellfie Protege 5.0+ Plugin (2.0.0.beta-7)

Level:       INFO
Time:        1461975116392
Message:     Plugin: OWL Code Generation Plug-in (2.0.0)

Level:       INFO
Time:        1461975116392
Message:     Plugin: Existential Query (2.0.0)

Level:       INFO
Time:        1461975116393
Message:     Plugin: Explanation Workbench (3.0.0)

Level:       INFO
Time:        1461975116393
Message:     Plugin: OntoGraf (2.0.2)

Level:       INFO
Time:        1461975116393
Message:     Plugin: DL Query (3.0.1)

Level:       INFO
Time:        1461975116393
Message:     Plugin: HermiT (1.3.8.413)

Level:       INFO
Time:        1461975116393
Message:     Plugin: OWLDoc (3.0.2)

Level:       INFO
Time:        1461975116393
Message:     Plugin: OWLViz (5.0.1)

Level:       INFO
Time:        1461975116393
Message:     Plugin: OWLAPI RDF Library (2.0.2)

Level:       INFO
Time:        1461975116394
Message:     Plugin: Protege SPARQL Plugin (2.0.1)

Level:       INFO
Time:        1461975116394
Message:     Plugin: SWRLTab Protege 5.0+ Plugin (1.0.0.beta-52)

Level:       INFO
Time:        1461975116394
Message:     

Level:       INFO
Time:        1461975116551
Message:     	OWLAPI RDF Library Plugin has no plugin.xml resource

Level:       INFO
Time:        1461975116795
Message:     Creating and setting up empty (default) editor kit

Level:       INFO
Time:        1461975116800
Message:     OWL API Version: 4.2.3.20160319-0906

Level:       WARN
Time:        1461975117479
Message:     Cannot generate ontology catalog for ontology at http://protege.stanford.edu/untitled-ontology-308

Level:       INFO
Time:        1461975117873
Message:     ------------------------------- Auto-update Check ------------------------------

Level:       INFO
Time:        1461975117875
Message:     Auto-update is disabled

Level:       INFO
Time:        1461975117875
Message:     

Level:       ERROR
Time:        1461975122019
Message:     An error related to DOT has occurred. This error was probably because OWLViz could not find the DOT application.  Please ensure that the path to the DOT application is set properly

Level:       ERROR
Time:        1461975122026
Message:     An error was thrown: An error related to DOT has occurred. This error was probably because OWLViz could not find the DOT application.  Please ensure that the path to the DOT application is set properly
org.coode.owlviz.util.graph.layout.dotlayoutengine.DotProcessException
StackTrace:  
    org.coode.owlviz.util.graph.layout.dotlayoutengine.DotProcess.startProcess(DotProcess.java:80)
    org.coode.owlviz.util.graph.layout.dotlayoutengine.DotGraphLayoutEngine.layoutGraph(DotGraphLayoutEngine.java:98)
    org.coode.owlviz.util.graph.ui.GraphView.revalidateGraph(GraphView.java:312)
    org.coode.owlviz.util.graph.ui.GraphView$4.hierarchyChanged(GraphView.java:160)
    java.awt.Component.processHierarchyEvent(Component.java:6692)
    java.awt.Component.processEvent(Component.java:6311)
    java.awt.Container.processEvent(Container.java:2234)
    java.awt.Component.dispatchEventImpl(Component.java:4881)
    java.awt.Container.dispatchEventImpl(Container.java:2292)
    java.awt.Component.dispatchEvent(Component.java:4703)
    java.awt.Component.createHierarchyEvents(Component.java:5541)
    java.awt.Container.createHierarchyEvents(Container.java:1443)
    java.awt.Container.addImpl(Container.java:1139)
    javax.swing.JViewport.setView(JViewport.java:962)
    javax.swing.JScrollPane.setViewportView(JScrollPane.java:1007)
    javax.swing.JScrollPane.<init>(JScrollPane.java:302)
    javax.swing.JScrollPane.<init>(JScrollPane.java:323)
    org.coode.owlviz.util.graph.ui.GraphComponent.<init>(GraphComponent.java:65)
    org.coode.owlviz.ui.OWLVizGraphPanel.<init>(OWLVizGraphPanel.java:70)
    org.coode.owlviz.ui.OWLVizView.createOWLVizTabUI(OWLVizView.java:175)
    org.coode.owlviz.ui.OWLVizView.initialiseClassView(OWLVizView.java:109)
    org.protege.editor.owl.ui.view.cls.AbstractOWLClassViewComponent.initialiseView(AbstractOWLClassViewComponent.java:28)
    org.protege.editor.owl.ui.view.AbstractOWLSelectionViewComponent.initialiseOWLView(AbstractOWLSelectionViewComponent.java:98)
    org.protege.editor.owl.ui.view.AbstractOWLViewComponent.initialise(AbstractOWLViewComponent.java:46)
    org.protege.editor.core.ui.view.View.createContent(View.java:424)
    org.protege.editor.core.ui.view.View.createUI(View.java:217)
    org.protege.editor.core.ui.view.View$1.hierarchyChanged(View.java:123)
    java.awt.Component.processHierarchyEvent(Component.java:6692)
    java.awt.Component.processEvent(Component.java:6311)
    java.awt.Container.processEvent(Container.java:2234)
    java.awt.Component.dispatchEventImpl(Component.java:4881)
    java.awt.Container.dispatchEventImpl(Container.java:2292)
    java.awt.Component.dispatchEvent(Component.java:4703)
    java.awt.Component.createHierarchyEvents(Component.java:5541)
    java.awt.Container.createHierarchyEvents(Container.java:1443)
    java.awt.Container.createHierarchyEvents(Container.java:1439)
    java.awt.Container.createHierarchyEvents(Container.java:1439)
    java.awt.Container.createHierarchyEvents(Container.java:1439)
    java.awt.Container.createHierarchyEvents(Container.java:1439)
    java.awt.Component.show(Component.java:1622)
    java.awt.Component.show(Component.java:1654)
    java.awt.Component.setVisible(Component.java:1606)
    javax.swing.JComponent.setVisible(JComponent.java:2644)
    javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:394)
    javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:270)
    javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:132)
    javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:67)
    javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:616)
    javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:591)
    javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:3647)
    java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
    java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
    java.awt.Component.processMouseEvent(Component.java:6522)
    javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    java.awt.Component.processEvent(Component.java:6290)
    java.awt.Container.processEvent(Container.java:2234)
    java.awt.Component.dispatchEventImpl(Component.java:4881)
    java.awt.Container.dispatchEventImpl(Container.java:2292)
    java.awt.Component.dispatchEvent(Component.java:4703)
    java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    java.awt.LightweightDispatcher.processMouseEvent(Container.java:4530)
    java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    java.awt.Container.dispatchEventImpl(Container.java:2278)
    java.awt.Window.dispatchEventImpl(Window.java:2750)
    java.awt.Component.dispatchEvent(Component.java:4703)
    java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
    java.awt.EventQueue.access$500(EventQueue.java:97)
    java.awt.EventQueue$3.run(EventQueue.java:702)
    java.awt.EventQueue$3.run(EventQueue.java:696)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    java.awt.EventQueue$4.run(EventQueue.java:724)
    java.awt.EventQueue$4.run(EventQueue.java:722)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
    java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
          Caused by:
        java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        java.lang.Runtime.exec(Runtime.java:620)
        java.lang.Runtime.exec(Runtime.java:485)
        org.coode.owlviz.util.graph.layout.dotlayoutengine.DotProcess.startProcess(DotProcess.java:60)
        org.coode.owlviz.util.graph.layout.dotlayoutengine.DotGraphLayoutEngine.layoutGraph(DotGraphLayoutEngine.java:98)
        org.coode.owlviz.util.graph.ui.GraphView.revalidateGraph(GraphView.java:312)
        org.coode.owlviz.util.graph.ui.GraphView$4.hierarchyChanged(GraphView.java:160)
        java.awt.Component.processHierarchyEvent(Component.java:6692)
        java.awt.Component.processEvent(Component.java:6311)
        java.awt.Container.processEvent(Container.java:2234)
        java.awt.Component.dispatchEventImpl(Component.java:4881)
        java.awt.Container.dispatchEventImpl(Container.java:2292)
        java.awt.Component.dispatchEvent(Component.java:4703)
        java.awt.Component.createHierarchyEvents(Component.java:5541)
        java.awt.Container.createHierarchyEvents(Container.java:1443)
        java.awt.Container.addImpl(Container.java:1139)
        javax.swing.JViewport.setView(JViewport.java:962)
        javax.swing.JScrollPane.setViewportView(JScrollPane.java:1007)
        javax.swing.JScrollPane.<init>(JScrollPane.java:302)
        javax.swing.JScrollPane.<init>(JScrollPane.java:323)
        org.coode.owlviz.util.graph.ui.GraphComponent.<init>(GraphComponent.java:65)
        org.coode.owlviz.ui.OWLVizGraphPanel.<init>(OWLVizGraphPanel.java:70)
        org.coode.owlviz.ui.OWLVizView.createOWLVizTabUI(OWLVizView.java:175)
        org.coode.owlviz.ui.OWLVizView.initialiseClassView(OWLVizView.java:109)
        org.protege.editor.owl.ui.view.cls.AbstractOWLClassViewComponent.initialiseView(AbstractOWLClassViewComponent.java:28)
        org.protege.editor.owl.ui.view.AbstractOWLSelectionViewComponent.initialiseOWLView(AbstractOWLSelectionViewComponent.java:98)
        org.protege.editor.owl.ui.view.AbstractOWLViewComponent.initialise(AbstractOWLViewComponent.java:46)
        org.protege.editor.core.ui.view.View.createContent(View.java:424)
        org.protege.editor.core.ui.view.View.createUI(View.java:217)
        org.protege.editor.core.ui.view.View$1.hierarchyChanged(View.java:123)
        java.awt.Component.processHierarchyEvent(Component.java:6692)
        java.awt.Component.processEvent(Component.java:6311)
        java.awt.Container.processEvent(Container.java:2234)
        java.awt.Component.dispatchEventImpl(Component.java:4881)
        java.awt.Container.dispatchEventImpl(Container.java:2292)
        java.awt.Component.dispatchEvent(Component.java:4703)
        java.awt.Component.createHierarchyEvents(Component.java:5541)
        java.awt.Container.createHierarchyEvents(Container.java:1443)
        java.awt.Container.createHierarchyEvents(Container.java:1439)
        java.awt.Container.createHierarchyEvents(Container.java:1439)
        java.awt.Container.createHierarchyEvents(Container.java:1439)
        java.awt.Container.createHierarchyEvents(Container.java:1439)
        java.awt.Component.show(Component.java:1622)
        java.awt.Component.show(Component.java:1654)
        java.awt.Component.setVisible(Component.java:1606)
        javax.swing.JComponent.setVisible(JComponent.java:2644)
        javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:394)
        javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:270)
        javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:132)
        javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:67)
        javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:616)
        javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:591)
        javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:3647)
        java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
        java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
        java.awt.Component.processMouseEvent(Component.java:6522)
        javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        java.awt.Component.processEvent(Component.java:6290)
        java.awt.Container.processEvent(Container.java:2234)
        java.awt.Component.dispatchEventImpl(Component.java:4881)
        java.awt.Container.dispatchEventImpl(Container.java:2292)
        java.awt.Component.dispatchEvent(Component.java:4703)
        java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
        java.awt.LightweightDispatcher.processMouseEvent(Container.java:4530)
        java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
        java.awt.Container.dispatchEventImpl(Container.java:2278)
        java.awt.Window.dispatchEventImpl(Window.java:2750)
        java.awt.Component.dispatchEvent(Component.java:4703)
        java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
        java.awt.EventQueue.access$500(EventQueue.java:97)
        java.awt.EventQueue$3.run(EventQueue.java:702)
        java.awt.EventQueue$3.run(EventQueue.java:696)
        java.security.AccessController.doPrivileged(Native Method)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
        java.awt.EventQueue$4.run(EventQueue.java:724)
        java.awt.EventQueue$4.run(EventQueue.java:722)
        java.security.AccessController.doPrivileged(Native Method)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
        java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
          Caused by:
            java.lang.UNIXProcess.forkAndExec(Native Method)
            java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
            java.lang.ProcessImpl.start(ProcessImpl.java:134)
            java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
            java.lang.Runtime.exec(Runtime.java:620)
            java.lang.Runtime.exec(Runtime.java:485)
            org.coode.owlviz.util.graph.layout.dotlayoutengine.DotProcess.startProcess(DotProcess.java:60)
            org.coode.owlviz.util.graph.layout.dotlayoutengine.DotGraphLayoutEngine.layoutGraph(DotGraphLayoutEngine.java:98)
            org.coode.owlviz.util.graph.ui.GraphView.revalidateGraph(GraphView.java:312)
            org.coode.owlviz.util.graph.ui.GraphView$4.hierarchyChanged(GraphView.java:160)
            java.awt.Component.processHierarchyEvent(Component.java:6692)
            java.awt.Component.processEvent(Component.java:6311)
            java.awt.Container.processEvent(Container.java:2234)
            java.awt.Component.dispatchEventImpl(Component.java:4881)
            java.awt.Container.dispatchEventImpl(Container.java:2292)
            java.awt.Component.dispatchEvent(Component.java:4703)
            java.awt.Component.createHierarchyEvents(Component.java:5541)
            java.awt.Container.createHierarchyEvents(Container.java:1443)
            java.awt.Container.addImpl(Container.java:1139)
            javax.swing.JViewport.setView(JViewport.java:962)
            javax.swing.JScrollPane.setViewportView(JScrollPane.java:1007)
            javax.swing.JScrollPane.<init>(JScrollPane.java:302)
            javax.swing.JScrollPane.<init>(JScrollPane.java:323)
            org.coode.owlviz.util.graph.ui.GraphComponent.<init>(GraphComponent.java:65)
            org.coode.owlviz.ui.OWLVizGraphPanel.<init>(OWLVizGraphPanel.java:70)
            org.coode.owlviz.ui.OWLVizView.createOWLVizTabUI(OWLVizView.java:175)
            org.coode.owlviz.ui.OWLVizView.initialiseClassView(OWLVizView.java:109)
            org.protege.editor.owl.ui.view.cls.AbstractOWLClassViewComponent.initialiseView(AbstractOWLClassViewComponent.java:28)
            org.protege.editor.owl.ui.view.AbstractOWLSelectionViewComponent.initialiseOWLView(AbstractOWLSelectionViewComponent.java:98)
            org.protege.editor.owl.ui.view.AbstractOWLViewComponent.initialise(AbstractOWLViewComponent.java:46)
            org.protege.editor.core.ui.view.View.createContent(View.java:424)
            org.protege.editor.core.ui.view.View.createUI(View.java:217)
            org.protege.editor.core.ui.view.View$1.hierarchyChanged(View.java:123)
            java.awt.Component.processHierarchyEvent(Component.java:6692)
            java.awt.Component.processEvent(Component.java:6311)
            java.awt.Container.processEvent(Container.java:2234)
            java.awt.Component.dispatchEventImpl(Component.java:4881)
            java.awt.Container.dispatchEventImpl(Container.java:2292)
            java.awt.Component.dispatchEvent(Component.java:4703)
            java.awt.Component.createHierarchyEvents(Component.java:5541)
            java.awt.Container.createHierarchyEvents(Container.java:1443)
            java.awt.Container.createHierarchyEvents(Container.java:1439)
            java.awt.Container.createHierarchyEvents(Container.java:1439)
            java.awt.Container.createHierarchyEvents(Container.java:1439)
            java.awt.Container.createHierarchyEvents(Container.java:1439)
            java.awt.Component.show(Component.java:1622)
            java.awt.Component.show(Component.java:1654)
            java.awt.Component.setVisible(Component.java:1606)
            javax.swing.JComponent.setVisible(JComponent.java:2644)
            javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:394)
            javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:270)
            javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:132)
            javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:67)
            javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:616)
            javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:591)
            javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:3647)
            java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
            java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
            java.awt.Component.processMouseEvent(Component.java:6522)
            javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
            java.awt.Component.processEvent(Component.java:6290)
            java.awt.Container.processEvent(Container.java:2234)
            java.awt.Component.dispatchEventImpl(Component.java:4881)
            java.awt.Container.dispatchEventImpl(Container.java:2292)
            java.awt.Component.dispatchEvent(Component.java:4703)
            java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
            java.awt.LightweightDispatcher.processMouseEvent(Container.java:4530)
            java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
            java.awt.Container.dispatchEventImpl(Container.java:2278)
            java.awt.Window.dispatchEventImpl(Window.java:2750)
            java.awt.Component.dispatchEvent(Component.java:4703)
            java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
            java.awt.EventQueue.access$500(EventQueue.java:97)
            java.awt.EventQueue$3.run(EventQueue.java:702)
            java.awt.EventQueue$3.run(EventQueue.java:696)
            java.security.AccessController.doPrivileged(Native Method)
            java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
            java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
            java.awt.EventQueue$4.run(EventQueue.java:724)
            java.awt.EventQueue$4.run(EventQueue.java:722)
            java.security.AccessController.doPrivileged(Native Method)
            java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
            java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
            java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
            java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
            java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
            java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
            java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
            java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by matthewhorridge** [comment]
I could reproduce this.

This seems to be a protege problem rather than an OWL Viz problem.

This seems to be to do with the JVM that we bundle.  If I change things around so that the installed system JVM is used instead then things work as expected.

**Comment by matthewhorridge** [comment]
I could reproduce this.

This seems to be a protege problem rather than an OWL Viz problem.

This seems to be to do with the JVM that we bundle.  If I change things around so that the installed system JVM is used instead then things work as expected.
