### ISSUE TITLE
Update the default bookmarked ontology URLs

### ISSUE THREAD

**Issue by tudorache** [protegeproject/protege#409]
Especially, the default pizza.owl URL does not work anymore. 

If using the pizza.owl URL, it will generated a parsing error (it points to a HTML page).

The cim3 links should also be removed/updated. The wiki is not maintained anymore.

Here are the links that don't resolve:
http://protege.cim3.net/file/pub/ontologies/ka/ka.owl
http://www.co-ode.org/ontologies/pizza/pizza.owl

![screenshot - 05032016 - 12 06 11 pm](https://cloud.githubusercontent.com/assets/2709502/14994991/78f1cb4a-1127-11e6-84fb-3cf6de0abdb9.png)

**Comment by matthewhorridge** [comment]
The cim3 links still work. Do we have an alternative though?

**Comment by csnyulas** [comment]
Most cim3 links work but the one that Tania pointed out does not.
Maybe we should upload the files to our current wiki:
protegewiki.stanford.edu/index.php?title=Special%3AListFiles
or create a GitHub project for them

**Comment by tudorache** [comment]
I uploaded them on our website, we have other files that we serve from there:

http://protege.stanford.edu/ontologies/koala.owl
http://protege.stanford.edu/ontologies/camera.owl
http://protege.stanford.edu/ontologies/travel.owl

Pizza was here:
http://protege.stanford.edu/ontologies/pizza/pizza.owl

We can certainly have them on github, as well.

**Comment by matthewhorridge** [comment]
Will update to the protege website.
