### ISSUE TITLE
Improve readability of Protege user's interface

### ISSUE THREAD

**Issue by tudorache** [protegeproject/protege#413]
Request from a user:

When using Protégé I had much reading problems to see the text efficiently on the grey background colour which is for me not a strong contrast to the grey text in front of it, s. attachment. From the usability point of view it should be possible to read all text in the frames and the title of the frame efficiently independent if users wear glasses and have cognitive eye problems ( e.g. brightness problems) or not.  

My recommendation is to give the frames and also the tabs a stronger background colour, so that the contrast of the letters will be better visible for users, s. ISO 9241 - Ergonomics of human-system interaction, especially part 110 - Dialogue principles or part 220 - Processes for enabling, executing and assessing human-centred design within organizations . Another option could be to have the opportunity to customize the colour by oneself. 

![p5](https://cloud.githubusercontent.com/assets/2709502/15123355/3c429fc0-15d8-11e6-94f1-b2263ac0a89f.png)

**Comment by matthewhorridge** [comment]
Here's a little explanation of what I did.  I made the text a little bit darker for the non-selected tabs by default and then made it darker still and made the borders darker if high contrast is enabled (in Windows).   

Current

<img width="380" alt="mail attachment" src="https://cloud.githubusercontent.com/assets/488607/15130757/acf3904a-15ff-11e6-813b-b9e5943b5190.png">

Contrast subtly increased slightly for default settings now.  It’s hard to see here, but noticeable in the tool.

<img width="381" alt="mail attachment" src="https://cloud.githubusercontent.com/assets/488607/15130764/b416a416-15ff-11e6-821d-0e1ee9108c50.png">

High contrast (if Windows is set to high contrast).  Tab borders are more distinct and the text is yet darker.

<img width="391" alt="mail attachment copy" src="https://cloud.githubusercontent.com/assets/488607/15130802/f5cf95c0-15ff-11e6-91cc-bdf008236b63.png">
