### ISSUE TITLE
The parse error dialog shows the parser class names that were tried instead of showing the associated formats

### ISSUE THREAD

**Issue by tudorache** [protegeproject/protege#414]
If a file fails to parse, Protege shows a dialog with the errors from the different parsers. There are 11 RioParserImpl shown right now. Ideally, a more descriptive name should be displayed.

![screenshot - 05092016 - 03 56 22 pm](https://cloud.githubusercontent.com/assets/2709502/15130637/df959cd8-15fe-11e6-9ace-fb89f860ec3b.png)

**Comment by matthewhorridge** [comment]
Change to show the format labels that were tried

<img width="973" alt="tabs" src="https://cloud.githubusercontent.com/assets/488607/15131318/be3164fa-1603-11e6-8d05-9a7d1bd7718b.png">
