### ISSUE TITLE
Duplicate annotation display for punned entities

### ISSUE THREAD

**Issue by swartik** [protegeproject/protege#422]
The attached ontology puns "enrolled" as a class and an object property. Protege 5.0.0 RC1 shows the rdfs:comments for both in the annotations window. Is it possible to be selective?
[AnnexDExamples.txt](https://github.com/protegeproject/protege/files/262259/AnnexDExamples.txt)

**Comment by matthewhorridge** [comment]
Technically, they are annotations on the IRI and not the entity - the subject of an annotation is an IRI and not an entity.  We therefore show annotations for the selected entity IRI, hence the reason why you see everything for a given IRI.  

The fact that the annotations appear to be on a class and appear to be on a property in the RDF/XML in this particular example is just an artefact of the this particular XML serialization - once parsed and we just have the triples this distinction disappears.

**Comment by matthewhorridge** [comment]
Closing because this isn't fixable.
