### ISSUE TITLE
Can't make hasvalue restrictions?

### ISSUE THREAD

**Issue by alanruttenberg** [protegeproject/protege#425]
I don't see how to make value restrictions. The restriction editor doesn't offer it as a type and doesn't allow instances to be selected. The class editor won't complete instance names in that context.

**Comment by alanruttenberg** [comment]
My bad. Used inv instead of inverse in object property expression. In that case it fails, even though the value keyword is highlighted and one would expect to complete an instance.

**Comment by matthewhorridge** [comment]
The highlighting of keywords is independent of valid syntax.  Closing for now.
