### ISSUE TITLE
how to change language show in class hierarchy window?

### ISSUE THREAD

**Issue by iampkuhz** [protegeproject/protege#428]
I want to show Chinese Name of class in Class Hierarchy window.
However, in Protege it shows English class names (shown in picture)
How can I change the view?

actually the class `dbo:Place` has no English label, only Chinese label. I have no idea why it shows English name in the class window?

thanks!

![screenshot from 2016-05-17 22 39 43](https://cloud.githubusercontent.com/assets/4539861/15326451/a18e8bba-1c80-11e6-8139-0e22de847174.png)

**Comment by matthewhorridge** [comment]
Please can you post this on the Protege mailing list?  This is a general Protege question and isn't (as far as I can tell) a bug report.
