### ISSUE TITLE
Insufficient default JVM stack size

### ISSUE THREAD

**Issue by tsarkov** [protegeproject/protege#434]
The default JVM stack size is too small for non-Java plugins, e.g. FaCT++. The error messages users receive are non-informative and look like a genuine errors. However, this problem is easy to fix by adding a -Xss option to the running scripts

**Comment by matthewhorridge** [comment]
@tsarkov nice to hear from you!  Do you have a suggestion for the default stack size?

**Comment by tsarkov** [comment]
I use 16M and it is enough for all applications including SNOMED, Gazeteer etc. Probably smaller limit will also be fine, but I've never checked. In the pull request I use 16M
