### ISSUE TITLE
OWLGraf : direction of the subClassOf arrow like in UML

### ISSUE THREAD

**Issue by jmvanel** [protegeproject/protege#438]
It would be nice for the direction of the subClassOf arrow to be like in UML,
that is pointing towards the ancestor,
which is after all the direction of a semantic dependency .

An example of an UML diagram with inheritance:
http://www.ibm.com/developerworks/rational/library/content/RationalEdge/sep04/bell/#N1019F

**Comment by tudorache** [comment]
This is an OntoGraf issue. Closing here, and opening for OntoGraf:
https://github.com/protegeproject/ontograf/issues/15
