### ISSUE TITLE
Saving Information widget does not disappear after action

### ISSUE THREAD

**Issue by jgrzebyta** [protegeproject/protege#445]
I found that sometimes saving information widget (example on picture) does not disappear after performed action. No errors in log found - only information that ontology was saved. Also I checked that saving was properly done using a text editor.

![screen](https://cloud.githubusercontent.com/assets/6738268/15901924/54e58560-2d9d-11e6-96b8-582dce61f6e4.png)

Versions;
Protege: 5.0.0
Linux: Xbuntu 16.04 x64

**Comment by matthewhorridge** [comment]
@jgrzebyta does this alway happen?  Is it just with a specific ontology or any ontology?

**Comment by jgrzebyta** [comment]
Now for _Protege 5.0.0 (build beta-23)_ it seems to be ok.
