### ISSUE TITLE
Editing a string with a @ results in data corruption

### ISSUE THREAD

**Issue by jmvanel** [protegeproject/protege#447]
Opening a file ( created outside of Protégé ) with a string value,
for example an rdfs:label, containing the character @,
and editing it,
results in a bad language tag,
and the string value is cut after the @ .
And after saving the resulting Turtle file is syntactically incorrect.

Here is an example Turtle file :

```turtle
@base <http://data.fr/ontologies/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

<http://data.onisep.fr/ontologies/> a owl:Ontology .
<APH> a owl:Class ;
    rdfs:label "Association de personnes handicapées (APH) @ Structures" .
```

NOTES: 

- there is a workaround: choosing explicitly the Type xsd:string in the editing popup window
- I'm not sure that Undo works well in this editing case

**Comment by matthewhorridge** [comment]
This is probably related to https://github.com/protegeproject/webprotege/issues/2
