### ISSUE TITLE
Fail to open the ontology

### ISSUE THREAD

**Issue by JKChang2015** [protegeproject/protege#451]
Hi, I updated my Protege to version 5.0.0 today, and unable to load the ontology with new/old version.  The attachment is the log file for the error. 

[protege.log.txt](https://github.com/protegeproject/protege/files/311730/protege.log.txt)

Could you please help me to solve this problem?

**Comment by matthewhorridge** [comment]
Please can you provide your ontology?

**Comment by JKChang2015** [comment]
http://purl.enanomapper.org/onto/enanomapper-dev.owl 
Thank you

**Comment by matthewhorridge** [comment]
The ontology loads for me, but I do get some warnings caused by some mismatches between ontology IRI and ontology location.  In particular, the import, 

```
http://purl.enanomapper.org/onto/internal/iao-ext.owl
```

actually resolves to an ontology with an IRI that is

```
http://purl.enanomapper.org/onto/internal/endpoints.owl
```

Is this a mistake?

**Comment by JKChang2015** [comment]
@egonw Please check this. I corrected the xml:base from endpoint to iao-ext.

**Comment by matthewhorridge** [comment]
[This line](https://github.com/enanomapper/ontologies/blob/master/internal/iao-ext.owl#L22) looks like it could do with updating as well.

**Comment by JKChang2015** [comment]
@matthewhorridge Solved, Thank you so much.

**Comment by matthewhorridge** [comment]
Great.  Glad it's sorted.

**Comment by egonw** [comment]
Same here. I had no time to look at it yet (up the academic ladder I am now :( )... it was stupid copy/paste bug :(

We have some way to go towards properly automating integrating ontologies... this should be been caught somewhere by the build/test code.
