### ISSUE TITLE
Plugin update mechanism does not correctly handle snapshot version ordering

### ISSUE THREAD

**Issue by martinjoconnor** [protegeproject/protege#452]
If I have a snapshot version of a plugin in the plugins directory (e.g., 1.0.9-SNAPSHOT) and release a production version (e.g., 1.0.9) the plugin update mechanism misclassifies the snapshot version as being later than the release version. Hence, the release version will not be updated. The snapshot version has to be deleted manually from the plugin directory to enable an update.

**Comment by matthewhorridge** [comment]
Just a heads up.  

We use ```org.osgi.framework.Version``` to compare version numbers and this is why you're seeing the behaviour.  I need to look at a better way of doing this (perhaps using the Maven comparison).

**Comment by martinjoconnor** [comment]
Yet another reason to love OSGi! Thanks for the fix.
