### ISSUE TITLE
JVMOptions -Xss?

### ISSUE THREAD

**Issue by mcourtot** [protegeproject/protege#457]
Looking at the info.plist file content, it reads:
        <key>JVMVersion</key>
        <string>1.8+</string>
        <key>JVMOptions</key>
        <array>
            <string>-Dapple.laf.useScreenMenuBar=true</string>
            <string>-Xss16M</string>
            <string>-Xdock:name=Protégé</string>
            <string>-DentityExpansionLimit=100000000</string>
            <string>-Dlogback.configurationFile=conf/logback.xml</string>
            <string>-Dfile.encoding=UTF-8</string>
            <string>-XX:CompileCommand=exclude,javax/swing/text/GlyphView,getBreakSpot</string>
        </array>

I couldn't figure out what the Xss options is - help? I checked https://developer.apple.com/library/mac/documentation/Java/Reference/Java_VMOptionsRef/Articles/JavaVirtualMachineOptions.html#//apple_ref/doc/uid/TP40008049

I was trying to increase the memory options as usual and just added
             <string>-Xmx12000M</string>
             <string>-Xms2000M</string>
which seem to be working fine.

**Comment by matthewhorridge** [comment]
The Xss option specifies the stack size.  We increased this from the default to support reasoning with some particular biomedical ontologies.

I'll leave this issue open as a reminder to add some documentation about this.

**Comment by dosumis** [comment]
I was getting lousy performance out of P5 with GO loaded until I deleted the -Xss setting.
Before deleting (& with -Xmx set to 6G) the performance with sluggish, with the cpu frequently maxing out rendering the editor unresponsive for up to a minute at a time.  Now seems fine.  

System OSX with Java 1.8.  2.9GHz Intel Core i7; 16G RAM; SSD.

**Comment by matthewhorridge** [comment]
Closing this because it seems stale.
