### ISSUE TITLE
Object property hierarchy view broken in Protege 5.0.0  (first non beta release)

### ISSUE THREAD

**Issue by dosumis** [protegeproject/protege#458]
![image](https://cloud.githubusercontent.com/assets/112839/16234426/572ef4e2-37c9-11e6-9459-01d6c716d24c.png)

This is a show-stopper for me.

(Apologies if this is a dup ticket.  Thought I remembered mention of it previously but couldn't find ticket on tracker).

**Comment by dosumis** [comment]
Update:  Seems to be due to elk 0.4.3.  Back to normal once I turn off the reasoner.

*but* - surely the reasoner should only be required of the 'inferred object property hierarchy'?

**Comment by aifargonos** [comment]
ELK 0.4.3 does not provide access to the taxonomies of object or data properties. Protege 5 displays these scary messages in such cases. The next version of ELK should provide access to object property taxonomy.

**Comment by matthewhorridge** [comment]
@dosumis It may be that when you select an object property the reasoner is queried to retrieve inferred equivalent and super properties for the property description view.  However, this shouldn't wipe out the property hierarchy.  I'm looking into it.

**Comment by matthewhorridge** [comment]
@dosumis at what point do you start ELK?  Here is, what I believe is a work around:  Make sure you select the entities tab before you select the reasoner and activate it.  If I do this then I get some message dialogs saying some methods are not supported, but the Object Property Hierarchy view remains intact.

**Comment by ykazakov** [comment]
Interesting that the Data property hierarchy view works fine even though ELK does not support reasoning with data properties. Also, Protege seems to ignore the setting of "Displayed Inferences" in Preferences > Reasoner. Even if everything is unchecked, it still asks the reasoner and try to display those inferred hierarchies.
