### ISSUE TITLE
ontograf: relations from imported ontologies are not shown

### ISSUE THREAD

**Issue by SebStaeubert** [protegeproject/protege#459]
Hi,

Scenario: 3 Ontologies
Ontology 1 contains 2 classes (CA, CB) which are associated with ObjectProperty A1: CA --A1--> CB
Using OntoGraf to visualize this works - the nodes and arc are visible.

Ontology 2 contains 2 classes (CF, CG) which are associated with ObjectProperty A2: CF --A2--> CG
Using OntoGraf to visualize this only works after restarting protegé and loading Ontology 2 at first. Only for the first ontology all nodes and arc are visible. For the second loaded Ontology only arcs of type Subclass are visible.

Ontology 3 imports Ontology 1 and 2. Then only arcs of type Subclass are visible, too.

This seems to be a Bug in visualizing association other then SubClass of when more then one Ontology is loaded or imported.

Regards,
Sebastian

**Comment by matthewhorridge** [comment]
Filed in the ontograf repo.  See this https://github.com/protegeproject/ontograf/issues/16
