### ISSUE TITLE
Temporary folders should be deleted upon closing Protege

### ISSUE THREAD

**Issue by rsgoncalves** [protegeproject/protege#461]
Protege generates temporary folders named "ProtegeCache-uuid" that never get expunged after closing the editor.

**Comment by matthewhorridge** [comment]
A bit more info...

Protege creates a temporary cache directory on each launch, but there is code to clean this up on shutdown. 

Testing this on a Mac, the cleanup code is only run when the Protege window is closed using the close button on the window frame.  Pressing CMD+Q to Quit doesn't give the cleanup code a chance to run.

**Comment by matentzn** [comment]
Yes, you are right.. I have this issue, and I am closing Protege a lot using cmd (strl+c). I just had a folder with around 40GB and I was wondering what it was.. I am not too bothered, I know what it is now, and I will just go and clean my temp dir from time to time when I see I am running out of space.

**Comment by matthewhorridge** [comment]
@matentzn I believe it's fixed :)

**Comment by matentzn** [comment]
Sorry misunderstood :) Thanks!
