### ISSUE TITLE
Add ability to reset HistoryManager

### ISSUE THREAD

**Issue by bdionne** [protegeproject/protege#463]
The `HistoryManager` that supports the `undo/redo` functionality in the editor does not play well with the protege client. When an existing project is opened the entire change history is loaded into the manager. We need the ability to reset the history, as this is not the intended semantics in this case, rather the idea is to capture edits in the current session. Something like this [workaround](https://github.com/bdionne/protege/commit/9350d9caf54ea316037c2e2664de3df14d2a8315) seems simple enough, though an interface method would be preferrable

**Comment by matthewhorridge** [comment]
> When an existing project is opened the entire change history is loaded into the manager

@bdionne Please can you explain why this happens?  Is it because of the way the project is loaded?

**Comment by bdionne** [comment]
When the project loads, the change history is fetched from the server in the form of list of `OWLOntologyChange` objects. The manager [applies](https://github.com/protegeproject/protege-client/blob/metaproject-integration/src/main/java/org/protege/editor/owl/client/util/ClientUtils.java#L197) that list of changes. 

This is somewhat mitigated in the client we're using as we load first from a snapshot, so the history applied from the server will be smaller.

**Comment by matthewhorridge** [comment]
I see, thanks.  I guess these changes should be silently applied as they aren't the result of user actions.  This way, the history manager, or any other object that listens for changes won't apply them.  Would there be any side effects to this solution from your point of view?

**Comment by bdionne** [comment]
That works, if by silently you mean in this kind of case we'd call a different method such as `applyChangesSilently` ? But yea, when we retrieve these from the server they are changes already committed by someone else so we don't need to track them in history.

I do still want to be able to get at History and use the Undo functionality, which I can do as there's a `getHistory` on the model manager. It gives me clean way to quickly undo some of these complex operations.

**Comment by matthewhorridge** [comment]
> That works, if by silently you mean in this kind of case we'd call a different method such as applyChangesSilently 

Yes, something like this.

**Comment by bdionne** [comment]
As I consider it more, there's also the case of committing changes to the server, after which it would be nice to reset the history manager, or not, I can see use cases where you'd want both capabilities
