### ISSUE TITLE
Protege fails to initialize plugin

### ISSUE THREAD

**Issue by bdionne** [protegeproject/protege#467]
Protege throws a [cast exception](https://gist.github.com/bdionne/97b2db6e5f1343241fdb9a092e505588) in `AbstractEditorKit` in the `initializedCompleted` method, when trying to use the LuceneQueryPlugin.

This is using the `search-api` branch of Protege and the nci-lucene-search branch of the plugin. I'm running Java 1.8.0_31 on OS X

**Comment by bdionne** [comment]
This could be a [lucene plugin](https://github.com/protegeproject/lucene-search-plugin/issues/1) issue

**Comment by matthewhorridge** [comment]
Closing this as it was a lucene plugin issue
