### ISSUE TITLE
Recursive expansion of hierarchies (ALT+Click) does not work properly

### ISSUE THREAD

**Issue by ykazakov** [protegeproject/protege#468]
If I click on owl:Thing in the class hierarchy view (asserted or inferred) while holding the ALT/Option key, the hierarchy does not expand recursively, just one level (as without ALT).
If, however, while holding ALT I first close the hierarchy and then open it, it expands correctly.
I have looked in the debugger, and it seems that the culprit is that in [OWLObjectTree](https://github.com/protegeproject/protege/blob/master/protege-editor-owl/src/main/java/org/protege/editor/owl/ui/tree/OWLObjectTree.javal) the mouse listener which sets altDown is fired *after* the TreeExpansionListener that checks the value of altDown.

Tested on mac OS X 10.11.5 with the latest Protege 5 (built from sources):

**Comment by matthewhorridge** [comment]
I can't reproduce this using the Mac OS L&F, but using the Protege LAF I can.

**Comment by ykazakov** [comment]
Indeed, I had a different L&F. With Mac OS X L&F seems to work fine. Still, I think it would be better not to rely on the order in which the listeners are called.

**Comment by matthewhorridge** [comment]
Yep, I'm rewriting the code....

**Comment by ykazakov** [comment]
I just tested Alt+Click for the latest version built from master, and while the recursive expansion now works, something is wrong with the label -- it is rotated 180 degrees, not 90. See the screenshot:

![screen shot 2016-08-04 at 14 05 01](https://cloud.githubusercontent.com/assets/2140361/17401224/b7de0454-5a4c-11e6-83f6-167677a74ccf.png)

**Comment by matthewhorridge** [comment]
This was the visual artefact that I observed with the fix.  On OS X there's an animation of the triangle and it gets stuck on the second frame with this fix.  I'm not sure why this occurs because I haven't looked into it any further.  However, I thought it was still worth having the fix over not having it.
