### ISSUE TITLE
Copy/pasting of strings into fields does not work on mac for non-mac look & feel

### ISSUE THREAD

**Issue by ykazakov** [protegeproject/protege#469]
On Mac OS X, if I select another look & feel from the Window menu (either Protege or Cross-Platform), then pasting strings into values (such as File > Open from URL... or Search...) does not work.

**Comment by matthewhorridge** [comment]
What key combination are you using to do this?

**Comment by ykazakov** [comment]
The usual Mac's ⌘C / ⌘V. Should other keys be used?

**Comment by matthewhorridge** [comment]
Does Ctrl+C and Ctrl+V work?  I believe that the default Protege look and feel (which I would not recommend - and this is one of the reasons why) hard codes these values to the Windows values.

**Comment by ykazakov** [comment]
I'll check that tomorrow (I don't have a laptop with me).
The other look and feels can be useful because one can see the navigation
help lines for hierarchies.

**Comment by ykazakov** [comment]
OK, I confirm that Ctrl+C and Ctrl+V work fine. In principle, one can add
the missing mappings
<http://stackoverflow.com/questions/7252749/how-to-use-command-c-command-v-shortcut-in-mac-to-copy-paste-text>
but
it seems that not only copy/paste shortcuts are affected, but also home/end
(alt + <-/ alt + ->) and maybe there are others mac-specific shortcuts.
The ticket can probably be closed for now.

**Comment by matthewhorridge** [comment]
Thanks for the confirmation.  As I say, this look and feel (which is there for historic reasons) is pretty weird.  I'll look at the issue of the lines in the hierarchy (in a separate issue).
