### ISSUE TITLE
close = exit?

### ISSUE THREAD

**Issue by SebStaeubert** [protegeproject/protege#478]
Szenario: multiple ontologies are open in one protege-window and modified. If you close one with File->Close then protege closes the protege-window with all open ontologies in this window! And the currently not active ontotogies in this protege-window are not saved!!!

**Comment by matthewhorridge** [comment]
The Close menu item on the File menu closes the current focused Window.  Any ontologies open in the Window that have been modified but not saved causes a dialog to be displayed prompting the user to save the ontologies.  If there is only one Window open selecting Close will ultimately cause Protege to exit.

I've just verified this behaviour.  If you're seeing something else then I would say there is a bug.  If you could provide some detailed unambiguous steps to reproduce the behaviour your seeing we would appreciated it.

**Comment by SebStaeubert** [comment]
I checked it again. You are right, Matthew.
Maybe i lost my changes on two ontologies in one windows as i want to close a third one. In the third one i did not want to save changes...

For me, the intended function of "close" was not to close the window but to close the active ontology! The "close" function should renamed to "close window". And i still think, it would be nice to have a "close" function, that closes the active ontology. This seems to be missing or did i just not found it yet?

**Comment by wismill** [comment]
I agree with @SebStaeubert : the menu label is misleading.
