### ISSUE TITLE
Protege freezing while trying to open an owl file

### ISSUE THREAD

**Issue by helenocampos** [protegeproject/protege#480]
Hello. My Protege application is freezing whenever I try to load a local owl file. I tried with multiple different files and got the same problem. Loading owl files through URL works though.
My operating system is Mac OS (el capitan 10.11.1) and the protege version is 5.0.0 (downloaded through the official website last week).
I tried also on windows 7 through Parallels Desktop VM on this same machine and got the same issue.

When I tried to load the same files in another computer (Windows) it worked normally.
Few example files that I tried: 
https://www.w3.org/ns/prov-o.owl
http://protege.stanford.edu/ontologies/pizza/pizza.owl

**Comment by matthewhorridge** [comment]
Is the local OWL file contained in a directory that has a lot of other file in it (either directly or in subdirectories)?

**Comment by helenocampos** [comment]
Yes it was. I moved them to a new folder and it just worked fine. Thank you!

**Comment by matthewhorridge** [comment]
Thanks for the confirmation.  Closing this.
