### ISSUE TITLE
The usage panel does not show annotation axioms that mention an IRI corresponding to the IRI of the selected entity

### ISSUE THREAD

**Issue by bdionne** [protegeproject/protege#483]
The usages panel only seems to display references through object properties or subclass relations or equivalences, essentially all the logic.

How hard would it be to show annotation properties as well? 

At NCI we have these `Associations` that are object relationships with no semantics. 

Programmatically we need something like:

`Set<OWLAxiom> getReferencingAxioms(@Nonnull OWLPrimitive owlEntity);`

That works for Annotations. Does such a method exist?

**Comment by matthewhorridge** [comment]
This should work.  OWLPrimitive is implemented by IRI and it's the IRI of the entity that needs to be search on (as annotation assertions work with IRIs and not entities).  Will look into this to see if something is missing/broken.

**Comment by bdionne** [comment]
That would be awesome. I was [debugging](https://github.com/owlcs/owlapi/blob/3e2d7fa990a74aeac82023fcab8987e548bfe7f5/impl/src/main/java/uk/ac/manchester/cs/owl/owlapi/OWLImmutableOntologyImpl.java#L452-L478) this code and that was my impression, that it would work. I tried passing in the IRI rather than the `OWLEntity` to no avail.

**Comment by matthewhorridge** [comment]
For the record.  OWLPrimitive doesn't work as one might think - only OWLEntity objects work.  Some custom index is needed to fix this.

**Comment by bdionne** [comment]
This works for me, though I have to use that same loop in both retirements and merges. I'll try it on the large ontology and see how slow it is. I suspect it will suffice for now. 

I'm not sure why we call `getReferencingAxioms` twice, once with `owlEntity` and once with `owlEntity.getIRI()`. The latter does include `OWLAnnotationAssertionAxioms`, but with the `owlEntity` in the subject rather than the `value`. I guess this is why the loop over the `AnnotationAssertions`

**Comment by matthewhorridge** [comment]
The extra loop is because the subject of an annotation assertion is an IRI and not an entity.  I need to dig into the OWL API to make sure things are working as documented here though.

**Comment by matthewhorridge** [comment]
Closing as this is working as expected
