### ISSUE TITLE
[Fatal Error] :22:94: The entity "raquo" was referenced, but not declared.

### ISSUE THREAD

**Issue by jziemer2** [protegeproject/protege#484]
Hi Protégé team,
An ontology turtle file on my website loads without issues.  File->Open from URI: http://finregont.com/fro/cfr/FRO_CFR_Title_17_Part_275_Section1-7.ttl 
But when I open a file that imports it: File->Open from URI:
http://finregont.com/fro/Import_FRO_CFR.ttl 

Protégé throws the strange error: _entity “raquo” defined, but not declared_.
Please let me know, if you can reproduce the issue or need further diagnostics.
Many thanks
Jurgen 

File->New	Ontology IRI: [](http://www.finregont.com/fro/Import_FRO_CFR.ttl )
Direct Imports 
Import an ontology contained in a web document: 
http://finregont.com/fro/cfr/FRO_CFR_Title_17_Part_275_Section1-7.ttl
Everything works: Imported ontologies shows above file and all indirect imports. The Entities are there. No issues with inferencing.
File->Save	Turtle Syntax: Import_FRO_CFR.ttl
Restarting Protégé
File->open	Import_FRO_CFR.ttl
Everything works
Uploading the turtle file to the website
File->Open from IRI…
         http://www.finregont.com/fro/Import_FRO_CFR.ttl
__[Fatal Error] :22:94: The entity "raquo" was referenced, but not declared.
_Failed to load imported ontology at_ _http://finregont.com/fro/cfr/FRO_CFR_Title_17_Part_275_Section_1-7.ttl__
Here is the output from the command line window:
[protege5_fatal_RAQUO_error_cmd_window_output.txt]
(https://github.com/protegeproject/protege/files/387509/protege5_fatal_RAQUO_error_cmd_window_output.txt)
_

**Comment by matthewhorridge** [comment]
The imported document IRI is not the same as the one that you load directly.  Compare them below:

```
http://finregont.com/fro/cfr/FRO_CFR_Title_17_Part_275_Section1-7.ttl            (loaded directly)
http://finregont.com/fro/cfr/FRO_CFR_Title_17_Part_275_Section_1-7.ttl           (in the import statement)
```

**Comment by jziemer2** [comment]
Fixed the typo and everything works.
Thanks so much Matthew.

**Comment by matthewhorridge** [comment]
You're welcome!
