### ISSUE TITLE
Class expression editor crash

### ISSUE THREAD

**Issue by dosumis** [protegeproject/protege#485]
Working with the class expression editor in Protege 5, I accidentally typed a '\' just before trying to use tab autocomplete.  The Class expression editor then became inactive.  Here's the error message:

Level:       ERROR
Time:        1469731489138
Message:     Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.IllegalArgumentException
StackTrace:  
    javax.swing.text.JTextComponent.setCaretPosition(JTextComponent.java:1629)
    javax.swing.text.DefaultEditorKit$BeginWordAction.actionPerformed(DefaultEditorKit.java:1754)
    javax.swing.text.DefaultEditorKit$SelectWordAction.actionPerformed(DefaultEditorKit.java:2163)
    javax.swing.text.DefaultCaret.selectWord(DefaultCaret.java:390)
    javax.swing.text.DefaultCaret.mouseClicked(DefaultCaret.java:419)
    java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
    java.awt.Component.processMouseEvent(Component.java:6528)
    javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    java.awt.Component.processEvent(Component.java:6290)
    java.awt.Container.processEvent(Container.java:2234)
    java.awt.Component.dispatchEventImpl(Component.java:4881)
    java.awt.Container.dispatchEventImpl(Container.java:2292)
    java.awt.Component.dispatchEvent(Component.java:4703)
    java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    java.awt.LightweightDispatcher.processMouseEvent(Container.java:4542)
    java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    java.awt.Container.dispatchEventImpl(Container.java:2278)
    java.awt.Window.dispatchEventImpl(Window.java:2750)
    java.awt.Component.dispatchEvent(Component.java:4703)
    java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
    java.awt.EventQueue.access$500(EventQueue.java:97)
    java.awt.EventQueue$3.run(EventQueue.java:702)
    java.awt.EventQueue$3.run(EventQueue.java:696)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    java.awt.EventQueue$4.run(EventQueue.java:724)
    java.awt.EventQueue$4.run(EventQueue.java:722)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
    java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by matthewhorridge** [comment]
Hi @dosumis,

I can't reproduce this.  Do you have some more specific steps that you can share with me? e.g. ontology, selected class and a partial expression that triggers it.

**Comment by matthewhorridge** [comment]
Closing because this seems stale given the discussion thread.  If more comments are added I'll reopen the issue.
