### ISSUE TITLE
Unable to creator property from dc:creator 

### ISSUE THREAD

**Issue by dosumis** [protegeproject/protege#486]
Tried the following entries in the config box in preferences.  None of them worked:

http://www.geneontology.org/formats/oboInOwl#created_by
<http://www.geneontology.org/formats/oboInOwl#created_by>
oboInOwl:created_by

Each attempt to change was followed by a considerable and prolonged spike in cpu usage by P5.

**Comment by matthewhorridge** [comment]
Reproducible.  I'll look for a fix.
