### ISSUE TITLE
Protege hangs when attempting to save certain obo files

### ISSUE THREAD

**Issue by cmungall** [protegeproject/protege#501]
The plant trait ontology editors would like to keep their source file in obo (for diffs) and edit in Protege. Unfortunately Protege hangs whenever they try and save. 

The ontology can be parsed and saved using the OWLAPI so it seems likely there is something in Protege causing this. I have been unable to reduce this to a small test example (since it requires opening up Protege, making a change, saving, which is time consuming). There are no obvious culprits, and I have not seen this behavior in any ontology.

To reproduce:
1. clone the following repo: https://github.com/Planteome/plant-trait-ontology
2. use commit 11bb1305eabecd3c02e8f7d25e6c55a108c7c4ba (not necessarily important but just to be sure our environments are identical)
3. Open the file `plant-trait-ontology.obo` in Protege
4. Edit anything in the main ontology (not an important). Try `carbon sensitivity`, modify the textual definition
5. Save

Protege will hang.

We are using the latest Protege -- About shows "Protege 5.0.0. (Build )"

cc @marieALaporte @austinmeier @cooperl09

**Comment by matthewhorridge** [comment]
I can reproduce this with the particular commit mentioned.  Just to note, with the head of master things work as expected.  Will look into it.

**Comment by matthewhorridge** [comment]
The above error messages are red herrings.

I think I've found the actual problem, which looks like it is caused by a deadlock that happens in the OWL API when there is essentially an attempt to upgrade a manager read lock to a write lock (which isn't possible).  This is happens when the OWLAPIOwl2Obo code creates a fresh ontology during the save.  I haven't checked, but the code path that does this isn't always invoked on a save.

**Comment by matthewhorridge** [comment]
Another update...

The deadlock arises when the save code has to translate axioms that cannot be serialised to OBO syntax.  In this case the axioms are saved in functional syntax and this serialisation is written into the OBO file - as far as I can tell.  To do this, a fresh ontology is created.  This requires a write lock, which blocks due to the read lock that is held during the save operation.  It would be best if a separate manager was created in order to generate the functional syntax.  However, we should also check the locking strategy in the OWL API to see whether it is doing the right thing here.

**Comment by cmungall** [comment]
Thanks! Yes, you are quite right, see [5.0.4 of the spec for treatment of untranslatable axioms](http://owlcollab.github.io/oboformat/doc/obo-syntax.html#5.0.4). Just knowing this is the cause should give us some short term options (these are probably unintended in this ontology).

**Comment by dosumis** [comment]
Any progress on this?  Was hoping it would be fixed in 5.1, but (from the file I'm working with right now at least) is seems not.

Many thanks,
David

**Comment by matthewhorridge** [comment]
Hi David,

I believe that the fix for this needs to occur in the OBO writer.  I'm not sure who's best placed to fix this.  Copying in @ignazio1977 incase he has thoughts about it!

**Comment by ignazio1977** [comment]
OWLAPIOwl2Obo has a translationManager included that's used only for untranslatable axioms and to obtain data factories - looks like it was designed to act as a separate manager. However in the OWLAPI renderer this manager is initialised with the ontology manager, which would cause the problem Matthew is observing. I'll try to replicate this in a unit test.

**Comment by LilyAndres** [comment]
Is there any update to this? I've been just trying to use owl2obo but I'm just wasting my time. I'm working with version the 5.2.0

**Comment by dosumis** [comment]
> On Jul 10, 2017, at 8:53 AM, LilyAndres <notifications@github.com> wrote:
> 
> Is there any update to this? I've been just trying to use owl2obo but I'm just wasting my time. I'm working with version the 5.2.0
> 

I can confirm that this is still an issue with 5.2.  I (now) only see this issue when a stanza contains an OBO id axiom whose value differs from the URI.

e.g. of AP axiom:

http://www.geneontology.org/formats/oboInOwl#id "GO:0000199"^^xsd:string

This is a common issue when creating terms through duplication.  robot and owltools cope fine with this.

**Comment by cmungall** [comment]
> I can confirm that this is still an issue with 5.2.  I (now) only see 
> this issue when a stanza contains an OBO id axiom whose value differs 
> from the URI.
>
> e.g. of AP axiom:
>
> http://www.geneontology.org/formats/oboInOwl#id 
> "GO:0000199"^^xsd:string
>
> This is a common issue when creating terms through duplication.  robot 
> and owltools cope fine with this.

These annotations cause a lot of confusion. Perhaps we should remove the 
auto-generation of these

**Comment by matthewhorridge** [comment]
This needs retesting with 5.5.0-beta-8 or later as we've upgraded the OWL API

**Comment by ignazio1977** [comment]
Are these large files? There's a long-standing issue with large obo files, the translator requires a lot of memory.

**Comment by matthewhorridge** [comment]
I don't think the files are large @ignazio1977. I'm pretty sure that the problem is caused by the deadlock described above.  Basically [this](https://github.com/protegeproject/protege/issues/501#issuecomment-239894827) comment and the one above it.

**Comment by ignazio1977** [comment]
Ok, deadlock can be replicated with a small test:

    @Test
    public void testNoDeadlock() throws OWLOntologyStorageException, OWLOntologyCreationException {
        OWLOntology o = OWLManager.createConcurrentOWLOntologyManager()
            .createOntology(IRI.create("urn:test:ontology"));
        o.getOWLOntologyManager().addAxiom(o,
            df.getOWLSubClassOfAxiom(df.getOWLNothing(), df.getOWLThing()));
        OWLOntologyDocumentTarget target = new StringDocumentTarget();
        o.saveOntology(new OBODocumentFormat(), target);
    }

I'll look into a solution, but it might be tricky.

**Comment by matthewhorridge** [comment]
Beautiful test case @ignazio1977

**Comment by ignazio1977** [comment]
Fix is up, I'm not overly proud of it but it's the best fix that does not involve interface changes.

**Comment by matthewhorridge** [comment]
Thanks @ignazio1977.  Will keep my eyes open for a 4 release.

**Comment by ignazio1977** [comment]
I'd like to fix the different individuals annotation issue before releasing

**Comment by ignazio1977** [comment]
OWLAPI 4.5.9 has been released, fixes three bugs that affect Protege.

**Comment by matthewhorridge** [comment]
Thanks so much for the fix @ignazio1977

**Comment by cmungall** [comment]
Thanks!!!
