### ISSUE TITLE
Get rid of 'Select an ontology format' dialog on Save As selection

### ISSUE THREAD

**Issue by martinjoconnor** [protegeproject/protege#510]
From the usability point of view it is annoying because it asks a question that likely has the same answer for a user 95%+ of the time - and also causes an extra intermediate step for every initial save. 

However, it think it is also causing a lot of people to save their files in OWL/XML format, which is not stable in Protege. (I suspect few people are familiar with OWL serialization formats and will pick OWL/XML over RDF/XML for their OWL ontologies because it looks like it could make more sense.)

I would make this an option under the file name in a Save As dialog.

<img width="539" alt="screen shot 2016-08-15 at 7 25 30 am" src="https://cloud.githubusercontent.com/assets/1731323/17667413/b04a171c-62b9-11e6-85e4-1bae42fabb0e.png">

**Comment by matthewhorridge** [comment]
> I would make this an option under the file name in a Save As dialog.

I looked to see if there was an easy way to do this with the native FileDialogs but there's not.  

> a question that likely has the same answer for a user 95%+

These days, I'm not sure what the percentage would be.  Turtle seems pretty popular nowadays.

**Comment by matthewhorridge** [comment]
Given the dialog is impossible to change (it seems) I'm closing this issue.
