### ISSUE TITLE
Inferred class hierarchy: Nothing Selected

### ISSUE THREAD

**Issue by ykazakov** [protegeproject/protege#519]
I guess the screenshot is self-explanatory:
![screen shot 2016-08-24 at 14 52 44](https://cloud.githubusercontent.com/assets/2140361/17931320/278d3ae0-6a0b-11e6-95a8-05de02038f9e.png)

To reproduce:
1. open the pizza ontology
2. classify
3. select "pizza" in the "Class hierarchy" panel
4. switch to "Class hierarchy (inferred)" tab

Similarly for the "Object property hierarchy (inferred)" tab.

What I also found confusing is that the inferred hierarchies can be either accessed from the asserted hierarchies by choosing "inferred" from the drop list or from window>views>class views>Class hierarchy(inferred). Perhaps the letter should be removed.

**Comment by matthewhorridge** [comment]
I can't reproduce this with the latest master.  I did make some changes to the selection mechanism here and I'm wondering if this fixed this issue by chance.

> What I also found confusing is that the inferred hierarchies can be either accessed from the asserted hierarchies by choosing "inferred" from the drop list or from window>views>class views>Class hierarchy(inferred). Perhaps the letter should be removed.

I would like to remove the latter.  At the moment it's in there for compatibility reasons so users' layouts don't break.  I wonder whether this really matters though.

**Comment by ykazakov** [comment]
I can still reproduce this with the fresh master from today.
Although one has to switch between the "Class hierarchy" and "Class hierarchy (inferred)" tabs a few times (without clicking on the selected class).

**Comment by matthewhorridge** [comment]
Thanks for the clarification.  I still cannot reproduce it.  Could you "reset" your UI (Window -> Reset selected tab to default state) and see if it still happens?  The UI will layout will look a bit different after the reset.

**Comment by ykazakov** [comment]
UI reset helped. Works fine now. Thanks.

**Comment by ykazakov** [comment]
I am afraid I have to reopen this: just noticed that the problem still shows up with tabs "Class hierarchy (inferred)" and "Object property hierarchy (inferred)"
When I select a class in "Class hierarchy (inferred)" and switch to "Object property hierarchy (inferred)" and back to "Class hierarchy (inferred)", the description for the selected class disappears ("Nothing selected" is shown)
This happens even after UI reset.
