### ISSUE TITLE
Front end filtering SWRL Builtin class

### ISSUE THREAD

**Issue by martinjoconnor** [protegeproject/protege#520]
I have an ontology (enclosed) that declares two individuals:

<tt>b1</tt>, which is an instance of <tt>swrl:NotBuiltin</tt>

and 

<tt>b2</tt>, which is an instance of <tt>swrl:Builtin</tt>

When I open the ontology in Protege is seems to treat the <tt>swrl:Builtin</tt> class specially and does not show the class itself or show that <tt>b2</tt> is an instance of it. <tt>swrl:NotBuiltin</tt> is correctly shown as a class, with <tt>b1</tt> shown as an instance of it.

[FilteredSWRLBuiltinClass.owl.txt](https://github.com/protegeproject/protege/files/443779/FilteredSWRLBuiltinClass.owl.txt)

**Comment by martinjoconnor** [comment]
To follow up on this. If I have the following ontology:

```
    ...
    <owl:Ontology rdf:about="http://swrl.stanford.edu/ontologies/built-ins/5.0.0/strings.owl"/>

    <owl:NamedIndividual rdf:about="http://swrl.stanford.edu/ontologies/built-ins/5.0.0/strings.owl#fred">
        <rdf:type rdf:resource="http://www.w3.org/2003/11/swrl#Builtin"/>
    </owl:NamedIndividual>
```

load it into Protege and then save it I get the following:

```
    ...
    <owl:Ontology rdf:about="http://swrl.stanford.edu/ontologies/built-ins/5.0.0/strings.owl"/>

    <owl:NamedIndividual rdf:about="http://swrl.stanford.edu/ontologies/built-ins/5.0.0/strings.owl#fred"/>
</rdf:RDF>
```

That is, the SWRL `Builtin` type gets stripped.

**Comment by matthewhorridge** [comment]
The parser in the OWL API only parses class assertions if the class is either owl:Thing, owl:Nothing or a class that isn't part of the reserved vocabulary.  I'm guessing that swrl:Builtin is part of the SWRL syntax and is reserved vocabulary and therefore ```x rdf:type swrl:Builtin``` won't be parsed as a class assertion and hence x won't be parsed as an individual.  It's a bit like a blank node being typed as an owl:Restriction.  This is part of the OWL syntax and the blank node will never be parsed into an individual typed with owl:Restriction.

**Comment by martinjoconnor** [comment]
Makes sense. 

Thanks.
Martin
