### ISSUE TITLE
Property value that contains logical keywords does not render correctly

### ISSUE THREAD

**Issue by bdionne** [protegeproject/protege#522]
![screen shot 2016-08-30 at 2 54 00 pm](https://cloud.githubusercontent.com/assets/31741/18102786/d58a1fcc-6ec1-11e6-8c4e-cd534a272ce1.png)

**Comment by ykazakov** [comment]
This was also observed in #502

**Comment by matthewhorridge** [comment]
Just fixed this for the axiom annotations dialog in https://github.com/protegeproject/protege/commit/0ea5504c810af033f12fe3762307a86cec4928f9

**Comment by bdionne** [comment]
This problem is still here, even after applying [0ea5504](https://github.com/protegeproject/protege/commit/0ea5504c810af033f12fe3762307a86cec4928f9)

<img width="1021" alt="screen shot 2016-12-16 at 12 29 37 pm" src="https://cloud.githubusercontent.com/assets/31741/21272051/9b03041c-c38b-11e6-9245-a8572ce9bb6b.png">

**Comment by matthewhorridge** [comment]
This is working for me.... see the rendering below, which looks quite different to yours.  I'll check the commit and make sure that's not screwed up.

<img width="532" alt="annos" src="https://cloud.githubusercontent.com/assets/488607/21272510/79b9fb0e-c3b7-11e6-807a-9fa5997cbd75.png">

**Comment by bdionne** [comment]
nm, you're right, I see the issue. I had the preferences checked to highlight keywords.

<img width="1022" alt="screen shot 2016-12-16 at 1 07 35 pm" src="https://cloud.githubusercontent.com/assets/31741/21273293/db9a12a4-c390-11e6-9b98-d4a7042e3ebd.png">

**Comment by matthewhorridge** [comment]
You shouldn't need to change the highlight prefs settings to get this working correctly.  From your latest screenshot it still looks like your rendering is the old rendering - the icon isn't shown in the new rendering that fixes the problem.  I still need to check the commit to make sure that something hasn't been missed out of it by accident.
