### ISSUE TITLE
Cannot install protégé 5.0_beta on Linux Ubuntu 14.04

### ISSUE THREAD

**Issue by pidory** [protegeproject/protege#54]
1-I have tried to run on the terminal the run .sh (cmd)
I get a command not found even if I changed the directory (cd Documents)

2- If i double-click on run.sh that I have extracted to my document. I get a prompt mentionning "could not open" Archive type not supported.

Can you help me?
Regards,
Dominique

**Comment by tudorache** [comment]
Protege works fine on Ubuntu 14.04. Closing the issue.
