### ISSUE TITLE
Internationalization ? string to translate

### ISSUE THREAD

**Issue by AmauryVanEspen** [protegeproject/protege#542]
Good evening,

i'm learning how to build ontology,
i would like to support your activity by expanding community to foreign language speakers
would you be kind to let me know if there is a translation project of protégé or maybe if it would be possible to init an internationalization of the string in order to proceed.
Thank you for your kind collaboration

Amaury

**Comment by matthewhorridge** [comment]
Sorry for this very late response.  There isn't an effort for this.  We need to make Protege internationalizable to do this.  There's an issue open for this (https://github.com/protegeproject/protege/issues/694) so I'll close this issue.
