### ISSUE TITLE
Order of Tools menu items is not logical

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#548]
Observed in 5.1.0 Snapshot from 20161003:
`Create data property hierarchy...` should come as the third item in the `Tools` menu (before `Create axioms from Excel workbook...`), because it is similar to the first two menu items `Create class hierarchy...` and `Create object property hierarchy..`

**Comment by johardi** [comment]
I think Cellfie needs to adjust its menu location. What about at the second menu group, top position, right before "Generate java code..."?

**Comment by csnyulas** [comment]
I think the first group is fine, because it is about "bulk" creation of axioms. But it should be after the class/property hierarchy creations.

**Comment by johardi** [comment]
Relocate the menu item to the bottom position: https://github.com/protegeproject/cellfie-plugin/commit/4b5a7b92adca629b3c9f1e7c650ea45f1e624e70
