### ISSUE TITLE
Excluding compile: javax.swing.text.GlyphView::getBreakSpot

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#550]
Observed in 5.1.0 Snapshot from 20161003:
In most cases when I run Protege on Linux and Windows I get this cryptic, and somewhat worrisome, message...

```
------------------------------- Auto-update Check ------------------------------ 
Auto-update last performed: Tue Oct 04 12:03:16 PDT 2016 
Auto-update has been performed today.  Not performing it again. 
 
### Excluding compile: javax.swing.text.GlyphView::getBreakSpot
```

Also, there is a similar message shown in the very first line:
```
CompilerOracle: exclude javax/swing/text/GlyphView.getBreakSpot
```

**It happens on:**
- Windows 7 
    - windows version if I start it with `run.bat`
- Linux (Ubuntu 14.04 LTS)
    - platform independent version (started with `run.sh`)
    - linux version (started with `run.sh`)

**It does not happen on:**
- Windows 7 
    - platform independent version (started with `run.bat`)
    - windows version when started with `Protege.exe`

**Comment by matthewhorridge** [comment]
It's a JVM message and it is related to this issue:  https://github.com/protegeproject/protege/issues/226 where we set a flag.  It's a message in response to this flag.
