### ISSUE TITLE
Type inference issue in tab `Individual by class`

### ISSUE THREAD

**Issue by wismill** [protegeproject/protege#582]
In the tab `Individual by class`, it seems there is a problem with the type inference.
In the following example, `:a` and `:b` won't appear in when I select the class `:A` but the class is correctly inferred in tabs `Entities` and `Classes`.

```
:A  a owl:Class ;
    owl:equivalentClass [
        a owl:Class ;
        owl:oneOf (:a :b)
    ] .
```

Configuration:
- Windows 10 64 bit
- Java 1.8.112
- Protégé 5.1 build from source, commit 0ea5504c810af033f12fe3762307a86cec4928f9
- Reasoner: Pellet 2.2

**Comment by matthewhorridge** [comment]
This tab doesn't show inferred individuals by type by default.  You can add the view that does show this information to this tab though.  Use the "Windows" -> "Views" -> "Individual views" -> "Instances (inferred)" to show this information.

**Comment by wismill** [comment]
Thanks Matthew, I did not know this option. So it adds a view i.e. a tab. Couldn't be there by default?

**Comment by matthewhorridge** [comment]
> Couldn't be there by default?

Yes, I'll file an issue for this.  Thanks for the suggestion.
