### ISSUE TITLE
Search dialog missing close box

### ISSUE THREAD

**Issue by donpellegrino** [protegeproject/protege#584]
The Protege Desktop includes a button labeled "Search" in the upper right of the main interface. Clicking this button opens a Search dialog box. The dialog box does not have a close button as part of its window decoration.

The Search dialog box should have appropriate window decorations including a close box.

Work-around: Pressing ESC on the keyboard closes the Search dialog.

Test System:
------------------------------------ Protege ----------------------------------- 
Protege Desktop 
Version 5.1.0, Build  
----------------------------------- Platform ----------------------------------- 
Java: JVM 1.8.0_111-b15  Memory: 466M 
Language: en, Country: US 
Framework: Apache Software Foundation (1.7)  
OS: linux (3.10.0-514.el7.x86_64) 
Processor: x86-64

$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.3 (Maipo)

$ java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b15)
OpenJDK 64-Bit Server VM (build 25.111-b15, mixed mode)

**Comment by matthewhorridge** [comment]
I expect this is a platform specific issue, because the close button is visible on OS X/MacOs.....

<img width="217" alt="close" src="https://cloud.githubusercontent.com/assets/488607/20279350/204a95c4-aa5d-11e6-8482-d32da473c5bb.png">

**Comment by donpellegrino** [comment]
The close box is also present on Microsoft Windows 7.

**Comment by csnyulas** [comment]
And the close button is also visible in Ubuntu.

![search window close button](https://cloud.githubusercontent.com/assets/2441046/20501183/a938c906-afed-11e6-9016-d49b9f8dd587.png)

I wonder if anyone could reproduce this on a Red Hat machine.

**Comment by donpellegrino** [comment]
The default GNOME desktop was used on the test RHEL 7 system.

**Comment by donpellegrino** [comment]
Screenshot:

![screenshot from 2017-01-06 08-53-07](https://cloud.githubusercontent.com/assets/4835457/21719835/b1b306b8-d3ed-11e6-84dd-05698d87ae7f.png)

**Comment by csnyulas** [comment]
Does the ESC button work?
Did you have a clean install of Protege (i.e. there were no previous versions, or if there were, you have removed them before installing the new version)?

**Comment by donpellegrino** [comment]
@csnyulas Yes, the ESC button does work. I believe this was a clean install.

**Comment by csnyulas** [comment]
We don't have a Red Hat machine at hand to reproduce it ourselves. Anyone else with the Red Hat machine or another OS, can reproduce it?

Would it be possible to run Protege with the Oracle JDK, instead of OpenJDK, and see if the problem still appears?

**Comment by donpellegrino** [comment]
Testing in GNOME on CentOS 7.6, the close box now appears as it should. Perhaps this was an issue with the distribution or Java runtime that has since been resolved at one of those layers. This issue can be closed.

$ cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 

$ java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by matthewhorridge** [comment]
Thanks @donpellegrino.  Much appreciated.
