### ISSUE TITLE
Annotations on annotation assertions - window lacks a box to interact with

### ISSUE THREAD

**Issue by dosumis** [protegeproject/protege#594]
Seems to only effect annotations on fields with lots of text content that don't yet have annotations on them.  See:

![image](https://cloud.githubusercontent.com/assets/112839/21027013/f1b6ef36-bd86-11e6-9d4c-c97947cb4fbd.png)

vs

![image](https://cloud.githubusercontent.com/assets/112839/21027141/70f3b446-bd87-11e6-93ae-5de2e5a3cb47.png)

Protege version 5.1.0

java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

on 
![image](https://cloud.githubusercontent.com/assets/112839/21027129/62f5bd6c-bd87-11e6-9b9f-92b7101bdf61.png)

**Comment by matthewhorridge** [comment]
Duplicate of #577, which is fixed for the next release.
