### ISSUE TITLE
OWLAPI v5

### ISSUE THREAD

**Issue by ghxiao** [protegeproject/protege#596]
Hi, I am wondering if there is a plan to upgrade owlapi to version 5?

**Comment by crapthings** [comment]
this is 2018, will this happen near future?

**Comment by matthewhorridge** [comment]
There is not.  This is due to the fact that the OWL API 5 is backwards incompatible with OWL API 4.  It's likely, because of the changes, that many plugins would be broken.

**Comment by sszuev** [comment]
For those who are interested, there are at least two forks with OWL-API v5:
- https://github.com/Galigator/protege (with default OWL-API-impl)
- https://github.com/sszuev/rdf-protege (ONT-API based fork)
