### ISSUE TITLE
Conversion from OWL to OBO does not work or takes a long time

### ISSUE THREAD

**Issue by LLCampos** [protegeproject/protege#597]
Hi!

I'm using Protegé version 5.1.0. I run the program and open the RadLex owl file, available [here](http://bioportal.bioontology.org/ontologies/RADLEX). Then I do the following:

![gifrecord_2017-01-02_174328](https://cloud.githubusercontent.com/assets/12008784/21593840/9c0e3210-d113-11e6-90bf-ebd21b7cf250.gif)

It hangs in the "Saving Ontology" window for a lot of time, not finishing. I've let it hang for some hours, and still no results. 

Maybe some more hours would do the trick? But if that's the case, it's too slow.

**Comment by dosumis** [comment]
Duplicate of: #501 

Protege doesn't cope with untranslatable OWL axioms. For now it is safer to save as OWL and use a command line tools for the standard OWL to OBO conversion:  [Robot](https://github.com/ontodev/robot) or [OWLtools](https://github.com/owlcollab/owltools).  AFAIK, both of these use the same code for conversion as Protege.  The Protege conversion issue is an integration problem.

**Comment by LLCampos** [comment]
Alright. Btw, I found that other issue before posting this one, but I understood that the problem was different. Sorry about that. :)

**Comment by csnyulas** [comment]
I close this issue, if this is a duplicate. Please follow the other one (#501).
