### ISSUE TITLE
Missing *c* in Object Property 

### ISSUE THREAD

**Issue by akatie** [protegeproject/protege#603]
In the object properties tab, the property ***contents***, although correct in the `.owl` file, appears as ***ontents***

<img width="1136" alt="ontents defect" src="https://cloud.githubusercontent.com/assets/3288013/21983394/164812fc-dbbf-11e6-9133-7e00018fb9f2.png">

[myOnto.owl.zip](https://github.com/protegeproject/protege/files/708334/myOnto.owl.zip)

**Comment by matthewhorridge** [comment]
In the OWL file the label of contents is actually "ontents".  Protege just displays this label.

See here:

```xml
    <!-- http://alignapi.gforge.inria.fr/tutorial/myOnto.owl#contents -->

    <owl:ObjectProperty rdf:about="http://alignapi.gforge.inria.fr/tutorial/myOnto.owl#contents">
        <rdfs:domain rdf:resource="http://alignapi.gforge.inria.fr/tutorial/myOnto.owl#Entry"/>
        <rdfs:range rdf:resource="http://alignapi.gforge.inria.fr/tutorial/myOnto.owl#Text"/>
        <rdfs:comment xml:lang="en">A Table of Contents.</rdfs:comment>
        <rdfs:label xml:lang="en">ontents</rdfs:label>
    </owl:ObjectProperty>
    ```
