### ISSUE TITLE
Protege 5.0.0 creates both .protege and .Protege

### ISSUE THREAD

**Issue by phillord** [protegeproject/protege#608]
A clean installation of Protege 5.0.0 (build from source by myself) seems to create both a `.protege` directory (which contains `logs`) and a `.Protege` directory (which contains `plugins`).

This is on an Ubuntu machine.

**Comment by matthewhorridge** [comment]
There should just be one ```.Protege``` directory.  Both logs and plugins should be in this directory.  Will look into it.

**Comment by matthewhorridge** [comment]
I don't believe this problem occurs with 5.1.0 – only ```.protege``` gets created.  @phillord please can you check this with 5.1.0?

**Comment by phillord** [comment]
Sorry for slow reply! Yep, 5.1.0 looks good to go to me!

**Comment by matthewhorridge** [comment]
Great,  thanks Phil.
