### ISSUE TITLE
Autoid generator not taking used ids into account.

### ISSUE THREAD

**Issue by hdrabkin** [protegeproject/protege#610]
For the Gene Ontology; I have been assigned a range of ids for new terms, GO:0001500  through GO:0003000.   Some of them have already been used. 
My attachment shows how I have set up my auto id generator. (fig 1); this is based on a co-workers set up, but using MY range. 
However, upon making a new term, even though GO:0001500 has been used, it gives me GO:00001500
(see fig 2).  In other words, it is not detecting that the id it is giving me is used already 

![fig1](https://cloud.githubusercontent.com/assets/10440080/22387585/547f2968-e4aa-11e6-8259-e310b877a721.jpg)

![fig2](https://cloud.githubusercontent.com/assets/10440080/22387590/5a66eb90-e4aa-11e6-9113-1bad1ec5576c.jpg)

This does not happen to my co-worker; his new ids are incremented with the next available number.

**Comment by hdrabkin** [comment]
Forgot: this is Protege 5.0.0

**Comment by matthewhorridge** [comment]
I've tried to reproduce this with Protege 5.0.0 but I cannot.  Please can you give me the specific version of the gene ontology that you're working from?

**Comment by hdrabkin** [comment]
Forgot NOT to reply to the email directly.
ANY version; If I update the obo file now, it does the same thing.
I feel it is something in a plugin or something that is responsible for looking at this. 

Here is the current obo file
[gene_ontology_write.obo.gz](https://github.com/protegeproject/protege/files/750770/gene_ontology_write.obo.gz)

**Comment by hdrabkin** [comment]
BTW, I'm working on a mac if that might matter.

**Comment by matthewhorridge** [comment]
In the example file that you attached GO:0001500 is actually not used.  Protege is therefore doing the right thing here, as far as I can tell.  Please can you double check this?

**Comment by hdrabkin** [comment]
This is strange; but you are right; there IS no GO:0001500, although there is a GO:0001501, 2, 3, etc.
Let me reset my id range to start at GO:0001501 and see what happens.

**Comment by hdrabkin** [comment]
Ok, now my next id is GO:0002591, which is what it does in Oboedit. 
Thanks for your attention to this

**Comment by matthewhorridge** [comment]
You're welcome.  Glad we've cleared this up.
