### ISSUE TITLE
How to see lang from langString in protege

### ISSUE THREAD

**Issue by fanavarro** [protegeproject/protege#613]
Hi,
I've developed an application in order to add labels systematically to an owl file by using OWLAPI. The function that performs this task is the following:

```
public static void addLabel(OWLOntology ontModel, OWLEntity entity, String label, String lang){
	OWLDataFactory df = ontModel.getOWLOntologyManager().getOWLDataFactory();
	OWLAnnotation annotation = df.getOWLAnnotation(df.getRDFSLabel(), df.getOWLLiteral(label, lang));
	OWLAxiom axiom = df.getOWLAnnotationAssertionAxiom(entity.getIRI(), annotation);
	ontModel.getOWLOntologyManager().applyChange(new AddAxiom(ontModel, axiom));
}
```

This creates rdfs:label annotations which have rdf:langString type. When I see the created labels by opening the ontology in protege, I can not check the language tag:
![imagen](https://cloud.githubusercontent.com/assets/11376639/22547117/6bf84382-e940-11e6-8830-510f4e8bff0c.png)

However, the language tag appears on the OWL/XML file of the ontology:

`<AnnotationAssertion><AnnotationProperty abbreviatedIRI="rdfs:label"/><IRI>#ZonaGeografica</IRI><Literal xml:lang="es" datatypeIRI="http://www.w3.org/1999/02/22-rdf-syntax-ns#langString">a</Literal></AnnotationAssertion>`

and I'm able to retrieve labels by their language tag by using OWLAPI.
Is there any way to know the language of an annotation whose type is rdf:langString in Protege?

Cheers,
Francisco Abad.

**Comment by matthewhorridge** [comment]
What version of Protege are you using?  Also, what version of the OWL API are you using?

**Comment by fanavarro** [comment]
I'm sorry, I forgot to mention the versions I'm using.
Protege 5.0.0 and OWLAPI 5.0.4.

Thanks,
Francisco Abad.

**Comment by matthewhorridge** [comment]
The problem arises because Protege uses version 4 of the OWL API - it expects rdf:PlainLiteral as the datatype.  When you save with version 5 of the OWL API the datatype is specified as rdf:langString.

 If you use RDF/XML then this problem won't happen.

**Comment by fanavarro** [comment]
Thanks @matthewhorridge. It works as expected by using OWLAPI 4 + Protege 5 instead of OWLAPI 5 + Protege 5.
