### ISSUE TITLE
Protege Setup in Eclipse PDE

### ISSUE THREAD

**Issue by ykazakov** [protegeproject/protege#617]
We made some [instructions](https://github.com/ykazakov/protege/wiki/Setup-in-Eclipse-PDE) on how to setup Protege in Eclipse using the Plug-in Development Environment (PDE). I think, they could be useful to other Protege (plug-in) developers. Is it OK to move them to the Protege wiki here? (It seems that anyone can edit that?)

**Comment by matthewhorridge** [comment]
> Is it OK to move them to the Protege wiki here? (It seems that anyone can edit that?)

Absolutely!  This would be a very nice contribution.  Thanks!

**Comment by ykazakov** [comment]
OK, I moved the page. The only thing, it would be nice to also move the images to a better suitable location. Currently they are hosted in another repository. And also it would be nice if somebody in Standford could test the instructions. ;-)

**Comment by johardi** [comment]
You can upload the images here https://github.com/protegeproject/github-wiki-resources/tree/master/protege/Developer-Documentation

**Comment by johardi** [comment]
I'll let you know my test result. Thanks for contributing! :)

**Comment by johardi** [comment]
You know what, I'm going to upload the images for you and change the image links in the wiki. I think it's easier and faster.

**Comment by johardi** [comment]
Hi @ykazakov, I went through the instructions but I wasn't able to run Protege. It didn't show me any error message in the console either. I'll try to run it again tomorrow perhaps.

**Comment by johardi** [comment]
Just a bit of feedback from following the instruction text:
- When installing the Eclipse PDE plugin, I think it's worth to mention the update site URL, e.g., http://dowload.eclipse.org/eclipse/updates/4.6 for Neon.
- Question: I found two components for the PDE plugin: "Eclipse PDE Plug-in Developer Resources" and "Eclipse Plugin Development Environment". Do I need the latter one?
- Write each component in the Prerequisites as a header instead of a bullet point. I found it was confusing to follow.
- The "ANSI Escape in Console" plugin couldn't be installed. The site URL was broken at the time I tested it.
- The paragraph starts with 'Under "Plug-ins and Fragments to Import" tick the first option: [...]', I found the steps in the bullet points are confusing.

**Comment by ykazakov** [comment]
@johardi, in run/debug configuration, did you set "the default start level to 1 and the default auto-start to true" (the screenshot does not show the auto-start value, which appeared only later)?
You can try the fix described in Troubleshooting "Runtime errors"? It looks like sometimes the configuration gets corrupted.

**Comment by ykazakov** [comment]
@johardi,

> When installing the Eclipse PDE plugin, I think it's worth to mention the update site URL, e.g., http://dowload.eclipse.org/eclipse/updates/4.6 (for Neon).

The update site changes from version to version, furthermore, isn't it set by default like that?
(I think it is not possible to upgrade to Neon, so it should be like that for the fresh install)

> Question: I found two components for the PDE plugin: "Eclipse PDE Plug-in Developer Resources" and "Eclipse Plugin Development Environment". Do I need the latter one?

In the Details it is written: "Eclipse plug-in development environment, including documentation and source code zips." So, I think, it already includes the "Eclipse Plugin Development Environment". In fact, installing just the environment (without sources) should work fine.

> I might write each required plugin in the Prerequisites as a section header instead of a bullet point. I found it was confusion to follow because of the text indentation.

Please, feel free to change the formatting as you think it is better.

> The "ANSI Escape in Console" plugin couldn't be installed. The site URL was broken at the time I tested it.

Did you install through the eclipse marketplace or via the url? I think I would remove the url as it becomes outdated rather quickly.

> The paragraph that starts with: Under "Plug-ins and Fragments to Import" tick the first option:, I found the steps in the bullet points are confusing.

Again, feel free to change the formatting as you think is less confusing.

**Comment by Yaaqoub** [comment]
Hi, i did follow the steps but in the step where i should Fix a problem with org.apache.commons.io bundle version numbers. the errors (red marks) still there .. i have two errors one in the Manifest file of protege-editor-core the other in the Manifest file of protege-editor-owl ..

**Comment by ykazakov** [comment]
Can you paste the error messages (or attach the screenshot where they are visible) here?

**Comment by Yaaqoub** [comment]
![1](https://cloud.githubusercontent.com/assets/11662053/23713508/6f6c350e-0426-11e7-8213-8703fbdec071.PNG)
That's the screenshot of the problem. now i succeed to open protege but there is still those errors .. is it fine if i remove those Export-Package like the error message tell me.

**Comment by ykazakov** [comment]
Can you tell me what's the error? I see only the quick fix suggestions.

**Comment by Yaaqoub** [comment]
Now protege run fine but it still give me that there is no plugins installed like the first time ..
![1](https://cloud.githubusercontent.com/assets/11662053/23714543/e20c6b26-0429-11e7-8de2-a069f35495c5.PNG)

**Comment by ykazakov** [comment]
Let us solve one problem at a time. Could you post the error messages for your previous screenshot?

**Comment by Yaaqoub** [comment]
Now all is good .. i deleted all the project and i start from the beginning again, i fount that i didn't import all plugins to the project .. Thank you.

**Comment by ykazakov** [comment]
OK, thanks for testing!
Regarding the missing plugins - that's normal. Plugins are not loaded from the usual location (the bundles directory), so I guess Protege does not detect them.
