### ISSUE TITLE
Meaning of bold rendering in Class hierarchy

### ISSUE THREAD

**Issue by superciccio14** [protegeproject/protege#665]
Hello there. 
In Protege 5, what is the meaning of bold/not-bold rendering of Class/Property names in hierarchical views?

**Comment by matthewhorridge** [comment]
This isn't an issue with Protege, rather it's a user question.  Please can you post this question to the Protege mailing list rather than using the GitHub Issue Tracker?  Thanks.

**Comment by superciccio14** [comment]
Yes, I posted here since in some repos the issue tracker is used also for questions. Sorry for the inconvenience :)

**Comment by matthewhorridge** [comment]
No problem!  I'll close this issue.
