### ISSUE TITLE
Importing the SIO ontology does not work

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/protege#667]
From the mailing list:

> The SIO ontology has multiple renderings at separate URLs on the web. As of Protege 5.0, it was possible to import http://semanticscience.org/ontology/sio-subset-labels.owl, which has, as its ontology URI, http://semanticscience.org/ontology/sio.owl, which is its own ontology. In Protege 5.2, the ontology will load, but its axia aren't added to the importing ontology.

> This seems like a bug to me, as I believe the semantics are "load the ontology that is defined at this location", and shouldn't be consulting the internal ontology URI for the actual import.

**Comment by matthewhorridge** [comment]
Needs reproducing with 5.5.0-beta-8 or later

**Comment by csnyulas** [comment]
I can't reproduce this is 5.5.0-beta-9. But neither in 5.2.0. Maybe I don't understand what the problem is?

Can you anyone reproduce this issue?

**Comment by matthewhorridge** [comment]
Seems to work in 5.5.0-beta-9.  I specify ```
http://semanticscience.org/ontology/sio-subset-labels.owl``` in the owl:imports statement and the ontology is imported with 9825 axioms and with an IRI of ```
http://semanticscience.org/ontology/sio.owl``` and a version IRI of ```http://semanticscience.org/ontology/sio-subset-labels.owl```

**Comment by matthewhorridge** [comment]
Closing this issue as the behavior is as expected.
