### ISSUE TITLE
Problem when with apostrophe when using the class expression editor

### ISSUE THREAD

**Issue by pgaudet** [protegeproject/protege#668]
Hello, 

Since the class expression editor uses apostrophes as grouping characters for strings of more than one words, terms such as 'cyclic AMP, adenosine 3',5'-cyclophosphate' cannot be entered using the class expression editor. 

(GO issue where this was encountered: https://github.com/geneontology/go-ontology/issues/13881) 

It would be convenient if there was a way to use these characters directly. We solved this one by using the Object restriction creator (as far as I recall) @ukemi can you provide details ?

Thanks, Pascale

**Comment by matthewhorridge** [comment]
Hi Pascale,

You will have to escape the single quotes using a backslash character e.g.

```'cyclic AMP, adenosine 3\',5\'-cyclophosphate'```

We're always happy to hear suggestions if you think you have a more convenient way of doing this.

**Comment by pgaudet** [comment]
Great, thanks for the tip !! 

Pascale
