### ISSUE TITLE
Creating Subproperties by importing them by Cellfie .

### ISSUE THREAD

**Issue by pranav0008** [protegeproject/protege#688]
The case is, I have a property defined Acceleration and inside I want to define the various units in which acceleration can be measured. 
I tried using 
ObjectProperty: ACCELERATION
SubPropertyof: @D*(ObjectProperty) 
and many other combinations, It didn't work

**Comment by matthewhorridge** [comment]
This is a question that should be posted to the Protege mailing list rather than an issue for here.  Please could you post this to the Protege mailing list?  Thanks.

**Comment by pranav0008** [comment]
thank you
