### ISSUE TITLE
Myanmar font not displayed properly in the UI

### ISSUE THREAD

**Issue by tudorache** [protegeproject/protege#69]
We had a report on the mailing list that the Myanmar font is displayed as square boxes in the Protege 4.3 UI. Interestingly, the font is displayed properly in Protege 4.2 alpha.

We should investigate what changed with the font implementation between the two versions. It might be that we switched between using logical and physical fonts, or the Myanmar font is not mapped by Java.

More info on font issues:
http://www.cs.lafayette.edu/docs/java/guide/intl/faq.html#Text Rendering

**Comment by stdotjohn** [comment]
These two issues look related and they both contain hints about possible solutions:

https://github.com/protegeproject/protege/issues/234
https://github.com/protegeproject/protege/issues/245

Sorry - I am not sure how to do cross references correctly.

-Timothy

**Comment by matthewhorridge** [comment]
Closing this because it seems to be a Java setup issue.
