### ISSUE TITLE
Import ontologies with same namespace

### ISSUE THREAD

**Issue by Evertude** [protegeproject/protege#693]
Good evening,

When I try to directly import an ontology that has the same namespace as the ontology that is currently opened, Protege will import the currently opened file (which makes no sense to me) instead. The other file won't be imported.

Is this normal behavior or did I get anything wrong?

Best regards,
Hannes

**Comment by matthewhorridge** [comment]
Hi Hannes,
What do you mean by "namespace"?  Do you mean ontology IRI?  If so, this is intended behaviour. Protege computes the imports statement by looking at the IRI of the ontology that you want to import.  If this IRI is equal to an ontology that is already loaded then that ontology will be used.

**Comment by Evertude** [comment]
Hi Matthew,
does this mean that if I have two partial owl files that I want to combine, I can't do this?
The problem is that I have some kind of an upper ontology with higher level classes and their properties and another ontology that has all the instances but also some of the lower level classes

**Comment by matthewhorridge** [comment]
Would you be able to post these ontologies to this issue so that I could take a look?  Without looking, it sounds like these are two separate ontologies and should therefore have different ontology IRIs.

**Comment by Evertude** [comment]
I set up a short example of the problem I have.
[Ontologies.zip](https://github.com/protegeproject/protege/files/1243413/Ontologies.zip)

I have three file: higher, middle and lower ontology.
higher and middle are created by humans.
lower is generated by an algorithm.

**Comment by matthewhorridge** [comment]
The problem is due to the fact that middle has the same ontology IRI as low.  If you change this IRI to middle (or something else) the imports should work as expected.

**Comment by Evertude** [comment]
Thank you very much, now I can see my problem.
Issue can be closed
