### ISSUE TITLE
Default answer for import resolution dialog.

### ISSUE THREAD

**Issue by marco-brandizi** [protegeproject/protege#707]
I have an ontology full of `owl:imports` statements, pointing at non-resolvale URIs. This causes Protegé to ask it a lot of times (one per URI) if I want to resolve the URIs (ie, specify which files they correspond to). Well, I don't want, and I'd like to tell it only once, with some additional button (or checkbox) like 'No to All'.

**Comment by matthewhorridge** [comment]
👍
