### ISSUE TITLE
Check update settings for the OAF Protege Plugin 

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/protege#711]
From the mailing list:

There seems to be some kind of inconsistency in the plugin repository list for Protégé 5 (I’m using 5.2.0).
 
It seems to think that the following plugins need to be updated:
 
IndividualPropertiesContextualAssertions (to 1.0.1)
OAF Protege Plugin (from 1.0.0 to 1.1.0)
 
When I in fact have the latest versions.  Also, when loading Protégé, the console when loading plugins outputs:
 
Plugin: OAF Protege Plugin (1.0.0)
 
when the file I have in my plugins folder is oaf-protege-1.1.0.jar (which came bundled with Protégé). When I go to the OAF website, however, the latest beta download is version 1.0.1 (oaf-protege-1.0.1.jar).
 
Also the 1.0.1 version of IndividualPropertiesContextualAssertions is not available on the Protégé Plugins library for download (although it comes bundled with the Protégé download)
 
It doesn’t appear to be affecting anything functionally (so far), but I thought I’d let you know.

**Comment by marco-brandizi** [comment]
Happens to me too, on a macOS system. Tried as admin too, the .jar is updated, but Protege keep saying it has 1.0.0. Same happens with IndividualPropertiesContextualAssertions.

**Comment by matthewhorridge** [comment]
From comments elsewhere I believe this issue is now fixed.

**Comment by csnyulas** [comment]
Yes, this issue was reported as part of #766, and it has been fixed.
