### ISSUE TITLE
display issue on definition annotation

### ISSUE THREAD

**Issue by nicolevasilevsky** [protegeproject/protege#712]
When I write a long string of text in the 'definition' annotation, and then try to add an additional annotation using the @ symbol, the long text hides the additional annotation buttons. See screenshots.
![image](https://user-images.githubusercontent.com/6722114/30665495-0315b478-9e06-11e7-91fc-8981dc96f590.png)

![image](https://user-images.githubusercontent.com/6722114/30665529-1c621cb4-9e06-11e7-819d-c324532a0340.png)

**Comment by matthewhorridge** [comment]
Hi @nicolevasilevsky we've fixed this issue for the next release.  

(For reference, here is the original issue #594)
