### ISSUE TITLE
DL learner latest plugin 0.8 is not working in protege 5.2 

### ISSUE THREAD

**Issue by pranav0008** [protegeproject/protege#713]
How to install DL learner plugin Properly in Protege ?
Is there any other way to use Machine Learning in making Ontology in Protege. I have surfed the Internet for weeks but I cannot find anything other than DL learner.
I want to make a ML model (Ontology Learning Model ) so that making Ontology of a large number of excel sheets could be made easy. 

Please reply at the earliest !

**Comment by matthewhorridge** [comment]
Please post general questions like this on to some mailing list e.g. the Protege mailing list.  This tracker is for specific issues/bugs with Protege.  Thanks.

**Comment by csnyulas** [comment]
You can subscribe to our mailing list(s) here: https://protege.stanford.edu/support.php
