### ISSUE TITLE
Problem displaying Unicode characters in Protege look-and-feel

### ISSUE THREAD

**Issue by swartik** [protegeproject/protege#714]
I have an ontology with class names that contain the fi and ffi ligatures. When the look-and-feel is set to Protege, these ligatures aren't always displayed properly. I am running Windows 7, Java 8 (1.8.0_144). Csongor Nyulas has tested the ontology on Ubuntu and didn't observe the erroneous display, so the problem must be Windows-specific.

I wanted to illustrate the problem by uploading an image, but github wouldn't let me. In the protege-dev mailing list (September 2017), see the thread with the subject "Question on Protege's Unicode character rendering".

**Comment by swartik** [comment]
Thank you. My company's firewall may well have something to do with the upload failure.

Here's the description I'd wanted to write. In the screenshot, the class name appears in two places: in the hierarchy, and in the label above the hierarchy. The first place displays it correctly, but in the label the "ffi" ligature appears as an empty rectangle.

**Comment by csnyulas** [comment]
Here is the whole thread on the mailing list, which provides more details:
http://protege-project.136.n4.nabble.com/Question-on-Protege-s-Unicode-character-rendering-td4669584.html

**Comment by matthewhorridge** [comment]
Possibly related to #818.  @swartik if you have time please could you check to see if this problem is still exhibited in 5.5.0-beta-8?

**Comment by swartik** [comment]
A problem remains, unfortunately. Except it's not quite the same.  Here's a screenshot from 5.5.0-beta-8:

![ligatures-in-550b8](https://user-images.githubusercontent.com/6043991/51407227-406cec00-1b29-11e9-8be0-e886abf1da6a.png)

Now the only correctly displayed name is under the ontology selector.

**Comment by matthewhorridge** [comment]
Thanks a lot @swartik.  Hmmm okay.  I changed the font for the render to use the font that JTextArea uses to be sure it was on the platform.  Previously, it was Verdana, but on Windows this doesn't include some unicode characters that are needed for Chinese.  The breadcrumb trail is actually, "Dialog", Plain, 11, which I think maps to Arial on Windows, as far as I can tell.

**Comment by matthewhorridge** [comment]
@swartik I've fixed the rendering problem in the class hierarch, I think (for the next beta).  However, do the boxes show in the view title if the Look & Feel is set to the Windows Look & Feel?

**Comment by matthewhorridge** [comment]
Thanks a lot @swartik 

I think we've finally nailed down the problem.  If you have a moment, please could you try the beta-9 snapshot build?  It's here:

https://oss.sonatype.org/content/repositories/snapshots/edu/stanford/protege/protege-desktop/5.5.0-beta-9-SNAPSHOT/protege-desktop-5.5.0-beta-9-20190123.010908-11-platform-independent.zip

It's a bare bones build, i.e. no plugins.

**Comment by swartik** [comment]
@matthewhorridge Good work. I downloaded the snapshot build and verified that the ligature characters display correctly in all 3 look-and-feels.

**Comment by matthewhorridge** [comment]
@swartik thanks so much for testing this.  Really glad to hear that it works with all L&F.  I'll mark this as fixed and close the issue.
