### ISSUE TITLE
Annotation axiom doesn't show up

### ISSUE THREAD

**Issue by petrsimon** [protegeproject/protege#735]
Hi,
when importing Turtle format with annotation in the form of:
```
:myannotation rdf:type owl:Axiom ;
   owl:annotatedSource :a ;
   owl:annotatedProperty :hasProp ;
   owl:annotatedTarget :b ;
   rdfs:comment "Some comment"^^xsd:string .
```
or 
```
:x rdf:type owl:Axiom .
:x owl:annotatedSource :a .
:x owl:annotatedProperty :hasProp .
:x owl:annotatedTarget :b .
:x rdfs:comment "Some comment"^^xsd:string .
```

it doesn't show up in the annotations dialog accessible via `@`. When exporting a file to Turtle from Protege, annotation of a triple was exported as blank node. 

I've noticed that Protege exports annotations as blank nodes.

**Comment by matthewhorridge** [comment]
The reification of the annotated axiom uses blank nodes, not IRIs.  So, as far as I know, neither of these are correct representations of an OWL axiom in RDF.  Checkout the [OWL 2 Mapping to RDF Graphs](https://www.w3.org/TR/owl2-mapping-to-rdf/) document.

**Comment by petrsimon** [comment]
I see my mistake, I've misread the specification. Thanks a lot!
