### ISSUE TITLE
URGENT "Changing IRIs of all the entities and Individuals while importing ontologies" 

### ISSUE THREAD

**Issue by pranav0008** [protegeproject/protege#736]
I want to change the IRI of all the entities after importing it into the other main Ontology's IRI. 

If I change its IRI before importing then import, it does not show any change and treat both the files, the one i am importing and the one i am importing into as the same.

**Comment by csnyulas** [comment]
I am not sure I fully understand what you are trying to do, but here is one thing you can do: You could change the IRI of the *imported* ontology (in the "Active ontology" tab) to the IRI of the *importing* ontology. When you click outside of the "Ontology IRI" field, Protégé will ask you if you would also want to rename all the entities whose IRI starts with the old ontology IRI. Choose **Yes**. Then change the ontology IRI to something else (maybe what it was before, or anything that is different from the onotlogy IRI of the *importing* ontology). When asked again if you want to rename all the entities starting with the old ontology IRI, this time choose **No**. Save your ontology, and you are ready to import it in the other ontology.

I close this issue as this is not describe an actionable problem with Protege that we can address. Please use our [mailing lists](http://protege.stanford.edu/support.php) to ask questions.
