### ISSUE TITLE
Incorrect inference of equivalent properties: using inverse(R) and HermiT

### ISSUE THREAD

**Issue by johanwk** [protegeproject/protege#741]
If an object property is explicitly stated to be subproperty of an inverse, invalid inferences are made.

Here's a minimal example ontology.
```

Prefix: : <http://example.org/>
Ontology: <http://asdf>

ObjectProperty: hasBigPart
    SubPropertyOf: 
        hasPart,
         inverse (partOf)
ObjectProperty: hasPart
    InverseOf: 
        partOf
ObjectProperty: partOf
    Characteristics: 
        Transitive
    InverseOf: 
        hasPart
```
    
Running the HermiT reasoner (but not, e.g., Fact++) we are presented with the inference that hasBigPart is equivalent to hasPart -- which should not be the case. Note that "hasBigPart is a subproperty of inverse (partOf)" is readily inferred if it's not added explicitly. Testing with HermiT on the command line, the invalid inference is not output. Therefore this looks like a Protégé bug.

I came across this problem when loading a set of inferred triples back into Protégé. 

(Protégé 5.2.0, HermiT plugin 1.3.8.413)

**Comment by ykazakov** [comment]
I could verify this bug. But it also happens from the OWL API (i.e., without Protege):

```
public class TestHermitReasoner {

	public static void main(String[] args) throws OWLOntologyCreationException {

		String fileName = args[0]; // the path to the ontology
		OWLOntologyManager man = OWLManager.createOWLOntologyManager();
		OWLOntology ont = man
				.loadOntologyFromOntologyDocument(new File(fileName));

		OWLReasonerFactory factory = new org.semanticweb.HermiT.ReasonerFactory();
		OWLReasoner reasoner = factory.createReasoner(ont);
		System.err.println(reasoner.getEquivalentObjectProperties(
				man.getOWLDataFactory().getOWLObjectProperty(
						IRI.create("http://example.org/hasBigPart"))));
	}

}
```
When I run the code above, I get the following printed:
`Node( ObjectInverseOf(<http://example.org/partOf>) <http://example.org/hasBigPart> <http://example.org/hasPart> )`

Looks like the bug still takes place with the latest (of now) HermiT 1.4.1.513 and OWL API 5.1.3.
I suggest to file a bug report to HermiT maintainers. 

@matthewhorridge Who is releasing HermiT now and where can one find the issue tracker?
[This project](https://github.com/phillord/hermit-reasoner) seems to be outdated (the latest release on maven was on Nov 07, 2017).

**Comment by ykazakov** [comment]
It seems that this bug was reported on the HermiT mailing list a few yers ago and has not been yet fixed since then:
https://code.google.com/archive/p/hermit-reasoner/issues/41

**Comment by matthewhorridge** [comment]
Should be fixed by using the latest available version of HermiT.  We'll try updating from 1.3.8.413 to 1.3.8.456

**Comment by csnyulas** [comment]
This is solved in the latest code on master, with addressing issue #828.
