### ISSUE TITLE
protege 5.2 doesn't have a tab named sparql Query 

### ISSUE THREAD

**Issue by 9444148408msr** [protegeproject/protege#742]
I trie for updation of plugins. But when I check for updates It only shows:
![screen shot 2017-12-06 at 11 49 46 am](https://user-images.githubusercontent.com/21138084/33647551-9cc3469c-da7b-11e7-9d6e-91929501399f.png). How to fix this

**Comment by csnyulas** [comment]
It comes bundled with Protege. It should be accessible through the `Window -> Tabs -> SPARQL Query` menu.

**Comment by 9444148408msr** [comment]
thank you I found that
