### ISSUE TITLE
Does not save annotation on Different Individuals axiom.

### ISSUE THREAD

**Issue by dillard** [protegeproject/protege#747]
I have a set of different individuals (owl#AllDifferent) in my ontology. I create an annotation for that axiom in Protege and this seems to work fine. However, when saving to file, Protege does not actually save the annotation for the axiom -- when I reload the ontology from the file, the annotation is missing. I am able to successfully add and save annotations on an AllDisjointClasses axiom.

Protege 5.2.0
OSX 10.12.6
RDF/XML syntax

P.S. The reason I'm trying to add an annotation is to be able to identify the axiom later in order to modify it as I add more distinct individuals. I'm fairly new to working with ontologies, so if there's a better way to accomplish this, please let me know.

**Comment by matthewhorridge** [comment]
I can confirm this behaviour with saving in RDF/XML (and other RDF formats e.g. Turtle).  As a workaround you could save your ontology in OWL/XML as the annotation is successfully saved and reloaded when using this format.

**Comment by matthewhorridge** [comment]
Needs reviewing in light of updates to the OWL API.

**Comment by csnyulas** [comment]
This issue is still present in 5.5.0-beta-7, exactly as described above: annotations are not saved in RDF/XML format, but they are saved in OWL/XML format.

**Comment by matthewhorridge** [comment]
Possibly an OWL API bug

**Comment by matthewhorridge** [comment]
After writing a stand alone test case, it appears to be an OWL API bug.  File an issues on the OWL API tracker:

https://github.com/owlcs/owlapi/issues/816
