### ISSUE TITLE
SNAP SPARQL plugin difficulty

### ISSUE THREAD

**Issue by rkboyce** [protegeproject/protege#748]
I had allot of difficulty figuring out how to get the SNAP SPARQL plugin to work in the Protege 5.2 release. This is what  finally worked:

1) Go to "File --> Check for Plug-ins" 

2) select the snap-sparql-query-plugin and make sure that OWLAPI RDF Library is up to date

3) Go to Window --> Tabs and uncheck "SPARQL Query" (this might conflict with SNAP SPARQL - Protege froze when I clicked on the tab after installing SNAP and running the reasoner over an ontology so I turned it off)

4)  Restart Protege, load you ontology.  The Snap Plugin is available as a View: Window > Views > Query Views > Snap SPARQL Query, which you can drop in any tab.

I think that the SNAP plug-in is important and am glad to see it in protege but have not seen much documentation about it except a 2015 conference paper cgi.csc.liv.ac.uk/~valli/OWLED2015/OWLED_2015_paper_21.pdf

**Comment by matthewhorridge** [comment]
Closing this, but it should still be searchable.  Thanks for the steps.
