### ISSUE TITLE
RDF:type creation

### ISSUE THREAD

**Issue by Gautamshahi** [protegeproject/protege#751]
I have created an ontology and wants to add rdf:type to my class so that I can run a SPARQL query to get all the instance which rdf:type (A particular class).

Kindly share the procedure to add rdf:type to the class.

Thanks & Regards,

**Comment by csnyulas** [comment]
This is the github issue tracker of the Protege Desktop application. Your question does not seem to report any issue with Protege, so it may be better addressed on the [Protege mailing lists](https://protege.stanford.edu/support.php). Please follow up there.

`rdf:ype` assertions are automatically created when you add an instance to a class (for example by using the purple diamond icon with the plus sign in the `Instances` view

![image](https://user-images.githubusercontent.com/2441046/35017846-a75b3934-fad3-11e7-966f-04899b7ebdc9.png)

or  in the `Individuals by type` view, after selecting the desired class)

![image](https://user-images.githubusercontent.com/2441046/35017943-2b9af02c-fad4-11e7-9e15-8efcce26cb5d.png)

Types can be also added, by selecting an individual (e.g. `b`) and clicking on the plus sign in the `Types` section of the entity description view.
![image](https://user-images.githubusercontent.com/2441046/35018059-b0880252-fad4-11e7-9ea0-1dd06a501957.png)

If you want to create such a statement programmatically, you can do it in different ways using the [OWLAPI](https://github.com/owlcs/owlapi/wiki/Documentation).
