### ISSUE TITLE
issue with adding equiv axioms that include a class with a comma in the label

### ISSUE THREAD

**Issue by nicolevasilevsky** [protegeproject/protege#754]
I wanted to add the following equivalence axiom:
'has part' some ('decreased amount' and ('inheres in' some (1,5-anhydro-D-glucitol and ('part of' some 'blood serum'))) and ('has modifier' some abnormal))

but protege doesn't seem to like the comma in the label for CHEBI_16070 1,5-anhydro-D-glucitol (see screenshot). I managed to add the equiv axiom though by switching the view to 'Render by entity IRI short name (Id)' and used all the IRIs for the classes and properties instead of their labels.

![image](https://user-images.githubusercontent.com/6722114/35890871-55069852-0b56-11e8-91b9-db3323b3f9aa.png)

**Comment by csnyulas** [comment]
Have you tried using single quotes around _1,5-anhydro-D-glucitol_, like this _'1,5-anhydro-D-glucitol'_? I think that should work.

**Comment by nicolevasilevsky** [comment]
Adding single quotes doesn't seem to work for me.
![image](https://user-images.githubusercontent.com/6722114/35891098-5ac75e88-0b57-11e8-9552-ff69835077ff.png)

**Comment by matthewhorridge** [comment]
Looks like a bug.  I can reproduce this with a simple test case.

**Comment by matthewhorridge** [comment]
Just to confirm this was a bug in Protege – names with commas in them should be escaped in single quotes, but Protege wasn't doing this at all and this was causing lookup problems with the expression parser.  Fixed for the next release, which will hopefully be sooner rather than later.

**Comment by nicolevasilevsky** [comment]
Thanks @matthewhorridge!

**Comment by matthewhorridge** [comment]
p.s. @nicolevasilevsky, if you need to work on this now, before the release, I can produce a snapshot build for you.... just let me know.

**Comment by nicolevasilevsky** [comment]
Thanks @matthewhorridge. I don't need to work on this at the moment.
