### ISSUE TITLE
Change entity IRI dialog does not display short names that start with numbers

### ISSUE THREAD

**Issue by sheldonkhall** [protegeproject/protege#756]
I have a concept with this IRI http://example.com/7hIr6BA14M and when I view it in the change uri context box I see this:

![screen shot 2018-02-09 at 18 08 00](https://user-images.githubusercontent.com/8779668/36042629-6eb412be-0dc4-11e8-93dc-b447030c237f.png)

and this

![screen shot 2018-02-09 at 18 08 09](https://user-images.githubusercontent.com/8779668/36042638-75441fde-0dc4-11e8-90c2-efb62860320b.png)

It seems numbers are trimmed when displaying without the full iri.

I am using protege version

![screen shot 2018-02-09 at 18 13 04](https://user-images.githubusercontent.com/8779668/36042800-f7050272-0dc4-11e8-9fa6-361c84e4cfde.png)

**Comment by matthewhorridge** [comment]
Thanks for the bug report.  I can reproduce this.
