### ISSUE TITLE
Error while adding the plugin OWLlinkHTTPXML [AWT-EventQueue-0] ERROR ProtegeApplication    Uncaught Exception in thread 'AWT-EventQueue-0'

### ISSUE THREAD

**Issue by visraj1** [protegeproject/protege#758]
The plugin to use OWLlink shows the error while adding the plugin. It works fine with version 4.3?

**Comment by csnyulas** [comment]
Where did you find this plug-in? 
If there is a problem with it, you should probably write to the plug-in authors. 
Please note, that most Protege 4.x plug-ins are not automatically compatible with Protege 5.x, as Protege 4 and 5 use different versions of the OWLAPI. The plug-in authors who want to make their plugin compatible with P5, usually adapt their plugin's source code and release a new version of it.

**Comment by visraj1** [comment]
Got it!
