### ISSUE TITLE
no plugin.xml resource

### ISSUE THREAD

**Issue by stdotjohn** [protegeproject/protege#76]
After a fresh install, Protege will display a series of warnings:
<pre>
	OWLAPI RDF Library Plugin has no plugin.xml resource
	OWL Difference Engine Plugin has no plugin.xml resource
	Guava: Google Core Libraries for Java Plugin has no plugin.xml resource
	OWLAPI Distribution Plugin has no plugin.xml resource
	Cajun Visualization Library Plugin has no plugin.xml resource
</pre>
These error messages may give end users the impression that something is wrong.  In addition they dilute the original intent.  If we have control over the manifest for the library, then this can easily be fixed or some alternative scheme of suppressing such warnings could be created.

**Comment by matthewhorridge** [comment]
We've not had any complaints on the list about this for a long time.  Closing for now.

**Comment by csnyulas** [comment]
In release 5.0.0 RC2 I get only one such message:
```
	OWLAPI RDF Library Plugin has no plugin.xml resource
```
Could we fix it before we close this issue?

**Comment by csnyulas** [comment]
Thanks for fixing this. I was thinking more about adding a `plugin.xml` file to the [OWLAPI RDF Library Plugin](https://github.com/protegeproject/rdf-library).
