### ISSUE TITLE
Typing class name in "Create a new Class" dialog freezes Protege

### ISSUE THREAD

**Issue by daniel86** [protegeproject/protege#765]
It only happens for long class names (>22 characters).
After some length entering a single additional character takes minutes!

I am using most up to date git version.
No errors are shown in the console.
In my test there were ~30 OWL ontologies loaded, potentially
a couple of thousand classes (if this matters).
No reasoner was active.
One CPU core is at max load during this.

Any ideas?

**Comment by matthewhorridge** [comment]
I can't reproduce this using 5.2.0 and an empty ontology.
Do you know what the memory usage of Protege on your system is?

**Comment by daniel86** [comment]
It remains constantly low, seems not affected by this.
It also happens with an empty ontology here.

**Comment by matthewhorridge** [comment]
> I wonder what is happening with the input that it can freeze the whole GUI. Shouldn't it be just checking if the identifier was taken before?

Yes, that's all it's meant to do.  What "New Entity" settings to you have?

Thanks for the log.  I can't see anything that's immediately illuminating.  You might try removing the org.exquisite.protege debugger plugin though – it seems to be throwing some errors.

**Comment by daniel86** [comment]
The "New Entities" tab in the settings dialog has these options:

- Start with: Active ontology IRI
- Followed by: # 
- End with: User supplied name

Is there an in-GUI way of disabling plugins? I can't find an option for this.

**Comment by matthewhorridge** [comment]
Thanks for the clarification about entity settings.

> Is there an in-GUI way of disabling plugins? I can't find an option for this.

There isn't.  You have to remove plugins from the plugins folder.  This is either embedded in your Protege distribution (if Protege can write to that directory or it is located as a hidden folder inside your home folder).

**Comment by matthewhorridge** [comment]
This problem surfaces in 5.5-beta-3 and seems to do with the regex matching that checks for OBO Ids.

**Comment by matthewhorridge** [comment]
Removing the ```Pattern.CASE_INSENSITIVE``` flag fixes the problem.  Not sure why this flag was in there because the pattern deals with case sensitivity.
