### ISSUE TITLE
Difference between using Pellet reasoner and using Drools in SWRL Tab for protege 5.2.0

### ISSUE THREAD

**Issue by ying6991** [protegeproject/protege#779]
I'm learner in protege. I wrote some rules in SWRL Tab, but the same results 
can be get when i run Pellet reasoner or run Drools in SWRL Tab. I do not 
known this case is a mere coincidence or inevitable conclusion. Could 
someone give me a favour to explain this situation? 

Thank you! 
Ying

**Comment by lifan0127** [comment]
I am new as well. My understanding is that the Pellet reasoner can incorporate SWRL rules in reasoning and create inferred triples, whereas using Drools will actually add the triples to your ontology.

**Comment by csnyulas** [comment]
In fact this question was already asked and answered on the mailing list:
http://protege-project.136.n4.nabble.com/Difference-between-using-Pellet-reasoner-and-using-Drools-in-SWRL-Tab-for-protege-5-2-0-td4670592.html
I'll close this issue.
