### ISSUE TITLE
missing resources

### ISSUE THREAD

**Issue by stdotjohn** [protegeproject/protege#78]
It looks like there are some missing resources in the maven generated bundles.  I bumped into one of these when trying to explain an inconsistent ontology.  The IntroductoryPanel.createCenterPanel method includes the line:
<pre>
        URL help = getClass().getResource("InconsistentOntologyHelp.html");
</pre>
The unix command 
<pre>
     find . -name "*.java" -exec grep -H getResource {} \;
</pre>
found at least one other likely candidate:
<pre>
./org.protege.editor.core.application/src/main/java/org/protege/editor/core/ui/action/start/ResetPreferencesAction.java:			URL u = getClass().getResource("ResetPreferencesExplanation.html");
</pre>

**Comment by matthewhorridge** [comment]
Seems to be o.k. to close this now.
