### ISSUE TITLE
Creating a fresh individual always uses OWLNamedIndividual class for [type] prefix

### ISSUE THREAD

**Issue by fer22f** [protegeproject/protege#785]
I'm new to this program, but I was trying to setup an entity naming system based on Wikidata using Protégé, but when creating new instances, I always get OWLNamedIndividual on [type] (and also on the title of the preview window):

![image](https://user-images.githubusercontent.com/3057302/41785431-f6fadfec-7618-11e8-8760-7e1f9b9edaeb.png)

Another problem with implementing my concept is the fact that auto IDs require a fixed number of digits, while Wikidata works without these restrictions: https://www.wikidata.org/wiki/Q1, https://www.wikidata.org/wiki/Q42, https://www.wikidata.org/wiki/Q513, https://www.wikidata.org/wiki/Q1348219, but I should probably make a separated issue for this.

So, am I missing something? Web Protégé doesn't have these kinds of advanced options, so I'm not able to compare, either.

**Comment by matthewhorridge** [comment]
> when creating new instances, I always get OWLNamedIndividual on [type]

In the new entity settings dialog, remove "[Type]" from the prefix.  You just want a prefix like "Q".

> Another problem with implementing my concept is the fact that auto IDs require a fixed number of digits

This is true.  This functionality is based on the usage of these kinds of Id in biomedical ontologies.  The advantage of having a fixed number of digits (I believe) is that basic string comparison sorts them in ascending numeric order.

> Web Protégé doesn't have these kinds of advanced options, so I'm not able to compare, either.

It does, you need to edit the new entity settings. See below.  Choose "Auto-Generated OBO Style Id". Specify the digit count as 1 (this is just a minimum digit count in WebProtege) and specify the appropriate prefix (ignore the warning about ending with an underscore, it's only a warning).  

<img width="540" alt="image" src="https://user-images.githubusercontent.com/488607/41786228-ccbb1ca2-75f9-11e8-90c8-19c6ae466356.png">

**Comment by fer22f** [comment]
Ok, it seems reasonable, odd that I can do the numbering thing on the Desktop application though, it truncates the numbers onto one digit.
