### ISSUE TITLE
Self referential warnings

### ISSUE THREAD

**Issue by TomConlin** [protegeproject/protege#790]
Offer a warning when an ontology becomes self referential.
Granted it may be needed in isolated cases, 
but in general an ontology may be encouraged to be defined in terms _not_ defined within the ontology.

for example:  
https://github.com/oborel/obo-relations/issues/246

**Comment by cmungall** [comment]
Can you provide more specifics? Referring to other parts of the ontology is of course good if it's done in a modular fashion. I think you mean that textual definitions should not be circular?

Also did you mean to put this in the ROBOT tracker rather than the Protege one?

**Comment by matthewhorridge** [comment]
Closing because it appears to be a ROBOT issue
