### ISSUE TITLE
Change IRI functionality - new entity options issue - auto-generated id

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [protegeproject/protege#796]
I work on a few ontologies within the OBOFoundry family.  When I switch from working on one to another, by opening a protege window, Protege seems to recall the previous ontology when deciding what prefix , digit size and number counter to apply to new "auto-generated id" terms.  This may be because it doesn't have an option to remember a user's specified counter with respect to the opened ontology - which I think would be a solution?

Here's what IRI's look like when I have FoodOn.owl open, **and then open GenEpiO.owl** and create a new term:

<img width="602" alt="screen shot 2018-09-04 at 8 52 53 am" src="https://user-images.githubusercontent.com/10779910/45042782-5bc6d700-b020-11e8-8deb-5d97f54ec874.png">

**Perhaps it is that the specified IRI - http://purl.obolibrary.org/obo/ - as it is shared between the ontology family, is not enough to cue up Protege to use GENEPIO_ as a prefix, and a 7 digit count, rather than FOODON and 8 digit count?**

To be clear, this happens after I establish what the auto-generated id characteristics are for a given ontology like GenEpiO, FoodOn, etc...

**Comment by Public-Health-Bioinformatics** [comment]
I'm game for that.  Ontology metadata would need all the parts that make up the auto-incremented id component.  Currently I'd been throwing this into the metadata, but if you folks have or know of a full set of ontology metadata tags (along the lines of dublin core tags) that would be great. We could probably get them into the https://github.com/INCATools/ontology-development-kit .

**Comment by matthewhorridge** [comment]
Supporting ODK projects would be good for this.

**Comment by matthewhorridge** [comment]
Older issue that request this functionality https://github.com/protegeproject/protege/issues/680

**Comment by matthewhorridge** [comment]
In 5.6.0 ODK -idranges.owl files will be supported

**Comment by matthewhorridge** [comment]
This has been implemented and will be available in 5.6.0
