### ISSUE TITLE
add an image 

### ISSUE THREAD

**Issue by issawayzani** [protegeproject/protege#801]
hello please i want to know how to add an image for an instance from a class thank you

**Comment by ssskralin** [comment]
@issawayzani , https://stackoverflow.com/a/50390481? That works well both for classes and individuals.

Or do you want the image to be "inherited" by all individuals, i. e. something like `Butterfly SubClassOf schema:image value "http://example.com/butterfly.png"`?  I'm affraid, it is impossible for annotation properties.

**Comment by issawayzani** [comment]
i saw this example question but i did not know how to  add the schema:image can you show me please how to add it

**Comment by issawayzani** [comment]
Thank you i found out how it worked
