### ISSUE TITLE
Licence for Mastro is highly restrictive

### ISSUE THREAD

**Issue by bjonnh** [protegeproject/protege#803]
"The Licensee is granted a personal, revocable, limited, non-exclusive and non-transferable right to install one copy of the Software and use it as an application. The Software may not be used in activities related to any commercial, entrepreneurial or professional activity, and may not be used as part of an automated process. The Licensee may not modify, translate, create derivative work(s) of, copy, distribute, license, sub-license, reverse engineer, disassemble, decompile, or unjar the Software, or otherwise attempt to derive the source code of the Software."

Should it still be included in the basic plugins?

**Comment by bjonnh** [comment]
http://www.obdasystems.com/mastro-license-agreement1

**Comment by matthewhorridge** [comment]
> Should it still be included in the basic plugins?

This is not included in the basic plugins that form part of the Protege distribution as far as I am aware.  It is available on auto-update though.  I'd therefore like to close this issue.  @bjonnh if you have further comments please post them, otherwise I will close the issue in a few days.

**Comment by bjonnh** [comment]
No problem, can close.

**Comment by matthewhorridge** [comment]
Thanks a lot @bjonnh
