### ISSUE TITLE
Add user specified name to preferences, to be used as annotation for newly created entities

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#808]
`Preferences -> New Entities Metadata` should have an additional option to the "Creator value" property, similar to user name and ORCID, to specify user defined creator name.

**Comment by matthewhorridge** [comment]
See the _User details_ preferences pane, which is where this is set

**Comment by csnyulas** [comment]
Cool! There could be a hint for it in the "New Entities Metadata" tab.
