### ISSUE TITLE
Protege freezes when loading an "online" ontology if proxy was not resolved

### ISSUE THREAD

**Issue by callingmybluff** [protegeproject/protege#815]
Loading a saved ontology, with online depencies, freezes if these dependencies could not be resolved.

Steps to reproduce:

1. Run protege using your proxy settings (I personally added them to my `run.bat`) and make an ontology with online dependencies.

1. Save your ontology, and close protege.

1. Run protege without the special proxy settings (i.e. the online ontologies' proxy can not be resolved).

1. Try to load your saved file. Protege freezes.

I suppose you can also do it the other way around (in case you have a direct internet connection):

1. Run protege normally and make an ontology with online dependencies.

1. Save and close.

1. Run protege with false proxy settings (ones that will not resolve).

1. Loading your saved ontology will cause protege to freeze (probably).

Worth mentioning that the handling of unresolved links is minimal; when trying to import an online ontology, it just does not do anything instead of showing a clear error message.

EDIT: Using `-Dhttp.proxyHost` and `-Dhttp.proxyPort` to set the proxy, if relevant.

**Comment by davidshumway** [comment]
I have also experienced this. Removing the ontology from the .owl is a temporary workaround.

**Comment by matthewhorridge** [comment]
This is resolved in 5.5.0-beta-7, which has just been released.  Please could you double check for me that it solves this issue?
