### ISSUE TITLE
Metrics panel shows metrics of first ontology only

### ISSUE THREAD

**Issue by woschmid** [protegeproject/protege#816]
Hi all,

when I load more than one ontology into the **current window** in Protégé v5.5.0-beta-5, the metrics panel does not update appropriately. Only the metrics of the first ontology are shown:

![metrics](https://user-images.githubusercontent.com/21000076/48544014-067e3000-e8c3-11e8-88dc-eb5dc215ef1c.gif)

------------------------------------ Protege -----------------------------------
Protege Desktop
Version 5.5.0, Build beta-5-SNAPSHOT

----------------------------------- Platform -----------------------------------
Java: JVM 1.8.0_40-b26  Memory: 466M
Language: de, Country: AT
Framework: Apache Software Foundation (1.8)
OS: windows8 (6.3)
Processor: x86-64

------------------------------------ Plugins -----------------------------------
Plugin: Cellfie Protege 5.0+ Plugin (2.1.0)
Plugin: OWL Code Generation Plug-in (2.0.0)
Plugin: Existential Query (2.0.0)
Plugin: Explanation Workbench (3.0.0)
Plugin: OntoGraf (2.0.3)
Plugin: DL Query (4.0.1)
Plugin: HermiT (1.3.8.413)
Plugin: Browser View (OWLDoc) (3.0.3)
Plugin: OWLViz (5.0.3)
Plugin: OWLAPI RDF Library (2.0.2)
Plugin: Protege SPARQL Plugin (2.0.1)
Plugin: SWRLTab Protege 5.0+ Plugin (2.0.5)

Best regards,
Wolfgang Schmid

**Comment by matthewhorridge** [comment]
@woschmid thanks for the demo video and reporting this.
