### ISSUE TITLE
Loading OBO Relations Ontology causes Protege 5.5 to hang

### ISSUE THREAD

**Issue by cmungall** [protegeproject/protege#817]
This occurs when I try and load http://purl.obolibrary.org/obo/ro.owl in Protege 5.5.0 beta-5-SNAPSHOT

It doesn't matter if I download the file first and open directly, or open from a URL

The same file will load fine using the same version of the OWLAPI (tested in the absence of catalog files).

This is on OS X, but a user has reported this for a PC too.

I'm afraid I don't recall where to read log messages, but the hanging happens before the magic red triangle appears. 

I suspect it must be something in an import, because if I include a catalog file and the imports from the top level of https://github.com/oborel/obo-relations/ (which is identical to the release imports) then loading is successful. 

Note I did test using robot with a no catalog scenario and it parses fine, so my random guess is something in the Protege stack different from the owlapi stack about how redirects is handled in fetching from remote URLs...?

**Comment by matthewhorridge** [comment]
Thanks for this report @cmungall.  Reproduced.

**Comment by matthewhorridge** [comment]
Looking at a stack dump, possibly related to this:

https://github.com/owlcs/owlapi/issues/806

**Comment by matthewhorridge** [comment]
The problem is indeed due to
https://github.com/owlcs/owlapi/issues/806.  A deadlock is caused because ontologies are loaded in a separate manager and in a thread that is not the EDT.  

Upgrading to OWL API 4.5.7 fixes the problem.  This also breaks some things due to changes in the DLExpressivityChecker.  I'll fix these problems and produce a new release.

**Comment by cmungall** [comment]
AFAICR this happens if one of the imported ontologies is doing something naughty (or completely fails to parse), can you tell from the stack dump if there is an obvious offender?

**Comment by matthewhorridge** [comment]
@cmungall I'll look into this, but one of the imports cannot be found (need to trace down the reason why) and this causes a prompt to be displayed.  With the changes in the OWL API this caused concurrent access and a deadlock.  OWL API 4.5.7 fixed this problem.

**Comment by matthewhorridge** [comment]
Just a quick followup.  All of the imports can be found on the Web.  Protege does display message boxes for each import indicating that it can't be found locally, which is painful, but a different issue.

**Comment by matthewhorridge** [comment]
Just a heads up @cmungall I've just produced a [5.5.0-beta-7 release](https://github.com/protegeproject/protege-distribution/releases/tag/v5.5.0-beta-7) that updates the OWL API and fixes the hanging problem.
