### ISSUE TITLE
Upgrade Protege to Java 11

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/protege#822]

**Comment by matthewhorridge** [comment]
Relevant issue:  https://github.com/protegeproject/protege/issues/702#issuecomment-451423167

**Comment by matthewhorridge** [comment]
Relevant issue: https://github.com/protegeproject/protege/issues/753

**Comment by matthewhorridge** [comment]
Relevant issue: https://github.com/protegeproject/protege/issues/732

**Comment by csnyulas** [comment]
Relevant issue: #825

**Comment by matthewhorridge** [comment]
Ensure that performance is ok.  See #723

**Comment by ykazakov** [comment]
B.t.w., how do you plan go about the new Java licensing model? Switch to OpenJDK?

**Comment by matthewhorridge** [comment]
For Java 11? Yes, we'll switch to OpenJDK.  We've done this for WebProtege.

**Comment by ykazakov** [comment]
Does Protege work well for OpenJDK? I did not test.
I think even for Java 8 the updates of Oracle JDK will no longer be free.

**Comment by matthewhorridge** [comment]
I need to double check both of these things

**Comment by ykazakov** [comment]
OK, I just tried Protege with OpenJDK on MacOS 10.14.2:
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_192-b12)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.192-b12, mixed mode)
From: https://adoptopenjdk.net
Everything feels and looks just like for Oracle JDK, including the issue #723.  
Just icons look funny.
<img width="473" alt="screenshot 2019-01-17 at 23 11 01" src="https://user-images.githubusercontent.com/2140361/51352547-3528aa80-1aae-11e9-9020-0facca2fbdfe.png">

**Comment by matthewhorridge** [comment]
Awesome @ykazakov!  Funny icons.  Will have to look into this.

**Comment by matthewhorridge** [comment]
For Java 8, my understanding is that we can still distribute the JRE without problems.  There just won't be anymore public updates for Java 8.

**Comment by woutermont** [comment]
How is this coming along? The issue referenced above (#732, #753, #702#issuecomment-451423167 and #825) still occurs when running 5.5-beta9 on Linux with Java 11.

**Comment by ykazakov** [comment]
@woutermont have you checked if the branch referenced in #732 works for Java11?
The current release 5.5-beta9 is for Java 8. It is unlikely that the same version of Protege will work for both Java 8 and Java 11 as there are some incompatibilities (see #732).

**Comment by woutermont** [comment]
@ykazakov my bad, I thought support for Java 11 was supposed to be ready now ... The fork doesn't work either though.

**Comment by ykazakov** [comment]
@woutermont if it were ready, this ticked would be closed ;-)
What is exactly in the fork not working for Java 11? @wismill [mentioned](https://github.com/protegeproject/protege/issues/732#issuecomment-383922105) that his modifications are working for Java 10.

**Comment by ykazakov** [comment]
@woutermont from which of the two branches did you build Protege? The osgi.ee error should have been [fixed](https://github.com/protegeproject/protege/issues/732#issuecomment-350247647) by the newer version of Apache Felix.

**Comment by ykazakov** [comment]
I just tried [this](https://github.com/protegeproject/protege/issues/732#issuecomment-350333303) branch on mac os 10.14.2: works fine with java 10.0.2 but not with 11.0.2:
```
CompileCommand: exclude javax/swing/text/GlyphView.getBreakSpot
Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.xml.bind not found
```

**Comment by ykazakov** [comment]
Probably related to [this](https://stackoverflow.com/a/52502208).

**Comment by ykazakov** [comment]
I think I fixed the errors. Could you give it a try?
https://github.com/liveontologies/protege/tree/feature/java11
I also created a PR based on this, but it requires some further testing.

**Comment by woutermont** [comment]
@ykazakov that seems to work! I'll work a bit with it and report any problems ...

**Comment by ykazakov** [comment]
@serasset Nice! I did not know that there is already a native java vor M1.

**Comment by mickbaggen** [comment]
Any chance that Protege 5.5 will be upgraded to run under OpenJDK 11 (or later)? This issue is already quite old...

**Comment by AndrewSmart** [comment]
For security I like to wrap everything in Firejail, including Java. To use Java 11, in addition to the changes mentioned above, for the [swrltab plugin](https://github.com/protegeproject/swrltab-plugin/) I also had to install a CORBA implementation as CORBA was [removed from Java 11](https://docs.oracle.com/javase/10/docs/api/deprecated-list.html). Here are the errors on launch regarding swrltab, which were later fixed with a CORBA implementation:
```
Starting bundle swrltab-plugin 
Jul 09, 2021 3:13:05 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Error starting file:/opt/Protege-5.5.0/plugins/swrltab-plugin-2.0.6.jar 
org.osgi.framework.BundleException: Unable to resolve swrltab-plugin [33](R 33.0): missing requirement [swrltab-plugin [33](R 33.0)] osgi.wiring.package; (osgi.wiring.package=org.omg.CORBA) Unresolved requirements: [[swrltab-plugin [33](R 33.0)] osgi.wiring.package; (osgi.wiring.package=org.omg.CORBA)]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4398) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2308) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1566) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) ~[org.apache.felix.main.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]


Plugin: SWRLTab Protege 5.0+ Plugin (2.0.6) was not successfully started.  Please see the Protégé log for more details.
```

Without having to setup and re-learn an environment for Java development, I manually downloaded the newer Felix from [here](https://search.maven.org/artifact/org.apache.felix/org.apache.felix.main), javax.xml.bind jar and dependencies from [here](https://search.maven.org/artifact/org.glassfish/javax.xml.bind), and CORBA implementation from [here](https://search.maven.org/artifact/org.jacorb/jacorb). I placed those 6 new jars in Protege-5.5.0/bin/ (also renaming the Felix jar to match what was in **run.sh**)

In **run.sh** in addition to javax.xml.bind I added jacorb:
```--add-modules javax.xml.bind,jacorb \```

Works.

**Comment by RalphBln** [comment]
Regarding https://github.com/protegeproject/protege/issues/822#issuecomment-877488750:  9d8c0d4afde21ae4435b3bbc08fa772f5a395128 takes care of this. @matthewhorridge: I can create a pull request if you are interested.

**Comment by gouttegd** [comment]
Closing as Protégé has been using Java 11 since version 5.6.0. Discussions about how/when to move to a higher version should go to #1236.
