### ISSUE TITLE
Open from URL fails on HTTPS addresses

### ISSUE THREAD

**Issue by berezovskyi** [protegeproject/protege#830]
When opening `http://open-services.net/ns/core#` vocabulary via the `Open from URL` options, I get the following error:

`sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

Server TLS report: https://www.ssllabs.com/ssltest/analyze.html?d=open-services.net (cert is issued by https://letsencrypt.org/ which is responsible for many TLS certs in use today)

v5.5.0 beta 8; macOS 10.14.2

**Comment by matthewhorridge** [comment]
Related issue: #702

**Comment by matthewhorridge** [comment]
Duplicate of #702.  Closing this issue and leaving #702 as the main issue.
