### ISSUE TITLE
Plugin not recognizing * and + used in property paths

### ISSUE THREAD

**Issue by linisundaram** [protegeproject/protege#857]
SELECT ?a, ?b,?c 
WHERE { ?a rdf:type t:Type1 .
?a t:creates ?b .
?b. t:movesTo+ ?c .}

Consider the above query. I want to list all variables created by ?a and which moves to ?c in one or more steps via property "moves To". This query is executed by normal SPARQL plugin without any issues, but does not list the inferred triples. But SNAP SPARQL query plugin shows an error in the syntax itself, as it does not recognize '+' symbol.

**Comment by matthewhorridge** [comment]
> But SNAP SPARQL query plugin shows an error in the syntax itself, as it does not recognize '+' symbol.

This isn't supported by SNAP.  In OWL, what you'd typically do is make movesTo transitive, so this property path wouldn't be needed.  Just for background,  there's a discussion about property paths under the OWL entailment regime in the SPARQL entailment regimes document.
