### ISSUE TITLE
Weird class hierarchy

### ISSUE THREAD

**Issue by william-vw** [protegeproject/protege#858]
A student in one of my tutorials got a "weird" class hierarchy displayed (well, one that I'm unfamiliar with at least). See below for a screenshot (notice the "arrow" next to the class bullet). Also note that classes are being put under classes where they shouldn't be (e.g., Pizza under PizzaBase) so the hierarchy appears wrong as well.
<img width="463" alt="class hierarchy 2" src="https://user-images.githubusercontent.com/11859376/54216625-c3c31200-44c8-11e9-9fd0-b7d19d276576.png">

But my particular Protege (which is the exact same version) doesn't have this issue - it doesn't display the arrows and shows the proper class hierarchy. Perhaps it's a reasoning option enabled/disabled somewhere? I've tried (un)checking various options but couldn't find the issue. Any help will be appreciated.

Protege version: 5.5.0 beta 9 (Hermit: 1.3.8.413)

**Comment by matthewhorridge** [comment]
They have the "Display relationships in class hierarchy" menu item checked in the "View" menu.  In this case, this shows, Pizza SubClassOf hasBase some PizzaBase.  Hover over the hierarchy and it will tell you what the relationship is.  You can uncheck the "Display relationships in class hierarchy" to display a pure ISA hierarchy.
