### ISSUE TITLE
FaCT++ 1.6.5 Fails on Protege 5.5.0-beta-9: "missing requirement"

### ISSUE THREAD

**Issue by nh905** [protegeproject/protege#863]
I just installed Protege 5.5.0-beta-9 on a Windows 10 Home machine (Intel 64bit).  I successfully downloaded FaCT++ 1.6.5 and restarted Protege.  FaCT++ failed to start.  The log shows:

> Starting bundle uk.ac.manchester.cs.owl.factplusplus
> Error starting file:/C:/pfstd/Protege-5.5.0-beta-9/plugins/uk.ac.manchester.cs.owl.factplusplus-1.6.5.jar
> org.osgi.framework.BundleException: Unable to resolve uk.ac.manchester.cs.owl.factplusplus [32](R 32.0): missing requirement [uk.ac.manchester.cs.owl.factplusplus [32](R 32.0)] osgi.native; (|(&(|(osgi.native.osname~=win)(osgi.native.osname~=windowsnt)(osgi.native.osname~=windows nt)(osgi.native.osname~=winnt)(osgi.native.osname~=windowsxp)(osgi.native.osname~=windows xp)(osgi.native.osname~=winxp)(osgi.native.osname~=windowsvista)(osgi.native.osname~=windows vista)(osgi.native.osname~=windows2003)(osgi.native.osname~=windows2008)(osgi.native.osname~=windows7)(osgi.native.osname~=windows 7)(osgi.native.osname~=windows8)(osgi.native.osname~=windows 8)(osgi.native.osname~=windows8.1)(osgi.native.osname~=windows 8.1))(|(osgi.native.processor~=x86_64)(osgi.native.processor~=amd64)))(&(|(osgi.native.osname~=win)(osgi.native.osname~=windows95)(osgi.native.osname~=windows 95)(osgi.native.osname~=win95)(osgi.native.osname~=windows98)(osgi.native.osname~=windows 98)(osgi.native.osname~=win98)(osgi.native.osname~=windowsnt)(osgi.native.osname~=windows nt)(osgi.native.osname~=winnt)(osgi.native.osname~=windowsce)(osgi.native.osname~=winndows ce)(osgi.native.osname~=wince)(osgi.native.osname~=windowsxp)(osgi.native.osname~=windows xp)(osgi.native.osname~=winxp)(osgi.native.osname~=windowsvista)(osgi.native.osname~=windows vista)(osgi.native.osname~=windows2003)(osgi.native.osname~=windows2008)(osgi.native.osname~=windows7)(osgi.native.osname~=windows 7)(osgi.native.osname~=windows8)(osgi.native.osname~=windows 8)(osgi.native.osname~=windows8.1)(osgi.native.osname~=windows 8.1))(|(osgi.native.processor~=i386)(osgi.native.processor~=x86)))(&(osgi.native.osname~=linux)(|(osgi.native.processor~=x86_64)(osgi.native.processor~=amd64)))(&(osgi.native.osname~=linux)(osgi.native.processor~=i386))(&(|(osgi.native.osname~=macosx)(osgi.native.osname~=mac os x))(|(osgi.native.processor~=ppc64)(osgi.native.processor~=x86_64)))(&(|(osgi.native.osname~=macosx)(osgi.native.osname~=mac os x))(|(osgi.native.processor~=ppc)(osgi.native.processor~=i386)))) Unresolved requirements: [[uk.ac.manchester.cs.owl.factplusplus [32](R 32.0)] osgi.native; (|(&(|(osgi.native.osname~=win)(osgi.native.osname~=windowsnt)(osgi.native.osname~=windows nt)(osgi.native.osname~=winnt)(osgi.native.osname~=windowsxp)(osgi.native.osname~=windows xp)(osgi.native.osname~=winxp)(osgi.native.osname~=windowsvista)(osgi.native.osname~=windows vista)(osgi.native.osname~=windows2003)(osgi.native.osname~=windows2008)(osgi.native.osname~=windows7)(osgi.native.osname~=windows 7)(osgi.native.osname~=windows8)(osgi.native.osname~=windows 8)(osgi.native.osname~=windows8.1)(osgi.native.osname~=windows 8.1))(|(osgi.native.processor~=x86_64)(osgi.native.processor~=amd64)))(&(|(osgi.native.osname~=win)(osgi.native.osname~=windows95)(osgi.native.osname~=windows 95)(osgi.native.osname~=win95)(osgi.native.osname~=windows98)(osgi.native.osname~=windows 98)(osgi.native.osname~=win98)(osgi.native.osname~=windowsnt)(osgi.native.osname~=windows nt)(osgi.native.osname~=winnt)(osgi.native.osname~=windowsce)(osgi.native.osname~=winndows ce)(osgi.native.osname~=wince)(osgi.native.osname~=windowsxp)(osgi.native.osname~=windows xp)(osgi.native.osname~=winxp)(osgi.native.osname~=windowsvista)(osgi.native.osname~=windows vista)(osgi.native.osname~=windows2003)(osgi.native.osname~=windows2008)(osgi.native.osname~=windows7)(osgi.native.osname~=windows 7)(osgi.native.osname~=windows8)(osgi.native.osname~=windows 8)(osgi.native.osname~=windows8.1)(osgi.native.osname~=windows 8.1))(|(osgi.native.processor~=i386)(osgi.native.processor~=x86)))(&(osgi.native.osname~=linux)(|(osgi.native.processor~=x86_64)(osgi.native.processor~=amd64)))(&(osgi.native.osname~=linux)(osgi.native.processor~=i386))(&(|(osgi.native.osname~=macosx)(osgi.native.osname~=mac os x))(|(osgi.native.processor~=ppc64)(osgi.native.processor~=x86_64)))(&(|(osgi.native.osname~=macosx)(osgi.native.osname~=mac os x))(|(osgi.native.processor~=ppc)(osgi.native.processor~=i386))))]
>         at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111) ~[org.apache.felix.main.jar:na]
>         at org.apache.felix.framework.Felix.startBundle(Felix.java:2117) ~[org.apache.felix.main.jar:na]
>         at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371) ~[org.apache.felix.main.jar:na]
>         at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) [org.apache.felix.main.jar:na]
>         at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
> The OSGi framework has been started

Any suggestions on how to resolve this?  I have attached the full run log.

Thanks, Norbert
[run.log](https://github.com/protegeproject/protege/files/2968727/run.log)

**Comment by jpi-seb** [comment]
Hi,
I had the same problem with FaCT++ 1.6.5 with the Protege 5.5.0 release (not beta), and OS windows 10.
The problem is Fact++, not Protégé. There has been no new release of Fact++ since 2016, and Windows 10 is not declared in the JAR manifest as a supported OS.
Here is a workaround to make it compatible : you have to update the manifest in the JAR file, and add Windows 10 declaration.

Workaround steps:

- Prerequisite: you must have a JDK 8 installed (you need the `jar` command line tool to update the manifest)

- Download the last release of Fact++ Protégé Plugin 5.X (v1.6.5): https://bitbucket.org/dtsarkov/factplusplus/downloads/uk.ac.manchester.cs.owl.factplusplus-P5.x-v1.6.5.jar

- Put the JAR in Protégé's `plugins` dir

- Download the manifest fix file and put it in Protégé's `plugins` dir: [factplusplus-P5.x-v1.6.5-manifest-fix-win10.txt](https://gist.githubusercontent.com/jpi-seb/12627bba6509a85a9c75afd262e78469/raw/28016a4b292c94549623c71dff4028cbea274a29/factplusplus-P5.x-v1.6.5-manifest-fix-win10.txt)
  * This fix file contains the content of the `Bundle-NativeCode` key from the original `MANIFEST.MF` file of the JAR
  * It has been modified to add the new values:
```
os=Windows10 ;
os=Windows 10 ;
```

- Open a command line in this directory, and execute this command to update the manifest inside the JAR file:
```
jar umf factplusplus-P5.x-v1.6.5-manifest-fix-win10.txt uk.ac.manchester.cs.owl.factplusplus-P5.x-v1.6.5.jar
```

- Restart Protégé: Fact++ should be available in the Reasoner menu

**Comment by nh905** [comment]
@jpi-seb Hi, your instructions worked like a charm.  For some reason jar.exe was not in the path so I had to include the full path.

Thanks, Norbert
