### ISSUE TITLE
Display axioms count imports statement

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/protege#883]

**Comment by csnyulas** [comment]
I am not sure what you have in mind regarding this enhancement, but I was thinking that it would be maybe nice to show differentiate between imported and local axiom counts in the "Ontology metrics" view as well. We could do that either as a separate column, or show local (or imported) axiom counts in parenthesis, or have a switch to chose between showing local axiom counts only or include imported axiom counts as well, etc.
I realize that these numbers may be harder to calculate/access after the ontology is loaded and is being edited, but I though I mention if you think it would be an idea worth of consideration. I am thinking that people often are interested in the number of axioms that is in their local ontology, without counting all the axioms that were created as part of a different project.

**Comment by matthewhorridge** [comment]
Like this...

(The metrics view would be a separate issue)

<img width="662" alt="image" src="https://user-images.githubusercontent.com/488607/56590330-c753b980-659b-11e9-89ee-25c03133fe8e.png">

**Comment by csnyulas** [comment]
Cool! Just wondering if these numbers are shown for indirect imports as well, and weather the numbers shown for the direct imports include axiom counts coming from indirect imports.
