### ISSUE TITLE
Clicking on "Clear log" should clear the error/warning flag in the status bar

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#886]
When the Log view is open, the error/warning flag is cleared in the status bar (bottom right corner of the main Protege window), which is good. 
However, if we keep using Protege, and we generate some new exceptions/errors that are logged, the flag will be shown again. After clearing the logs by pressing on the "Clear log" button, the log text is deleted, but the flag stays on. The flag  should be also removed.

**Comment by csnyulas** [comment]
BTW, the flag should be cleared also when the Log view is closed (even if the log itself is not cleared), because we know that the user had a chance to look at the errors if he or she is manipulating that view.
Basically, we should not remove the error flag every time we provided the opportunity to the user to look at the errors, so that the flag can be set next time an error is happening "in the background".

**Comment by ykazakov** [comment]
The only problem is that if the log window remains open in the background and the user works in the main window then the warnings/errors remain unnoticed. Perhaps it makes sense to clear the icon only when the log window is closed or cleared.

**Comment by csnyulas** [comment]
Exactly @ykazakov 
I did precisely that, if I understand your suggestion correctly.
The flag is cleared when the user opens the log window. This was always like that. 
What I added is that the flag will be cleared also when the user closes the log window, or clears the logs.

**Comment by ykazakov** [comment]
@csnyulas OK, I misunderstood. I thought you have disabled changing the icon as long as the log window remains open.
