### ISSUE TITLE
TurtleOntologyParser breaks on legal Turtle 1.1 expression

### ISSUE THREAD

**Issue by wouterbeek** [protegeproject/protege#89]
The TurtleOntologyParser does not correctly handle the following Turtle triple, due to the occurrence of reserved character escaped round brackets in the object term's local name:

~~~{.ttl}
dbp:teaches rdfs:range dbpedia:Course_\(education\) .
~~~

Protégé incorrectly complains:
~~~{.txt}
uk.ac.manchester.cs.owl.owlapi.turtle.parser.ParseException: Encountered " <ERROR> "\\ "" at line ..., column 39.
Was expecting:
    "." ...
~~~

The relevant Turtle 1.1 syntax rules:
~~~{.abnf}
[136s] 	PrefixedName 	::= 	PNAME_LN | PNAME_NS
[140s] 	PNAME_LN 	::= 	PNAME_NS PN_LOCAL
[164s] 	PN_CHARS_U 	::= 	PN_CHARS_BASE | '_'
[168s] 	PN_LOCAL 	::= 	(PN_CHARS_U | ':' | [0-9] | PLX) ((PN_CHARS | '.' | ':' | PLX)* (PN_CHARS | ':' | PLX))?
~~~

Rule 164s says that the underscore is allowed to appear unescaped. However, the round brackets must appear in escaped form. Moreover, round brackets that appear in local names are **only** allowed with *reserved character escaping*, since both numeric and string escapes are disallowed. [See the table in section 6.4 of Turtle 1.1 recommendation for this.](http://www.w3.org/TR/turtle/#sec-escapes)

**Comment by matthewhorridge** [comment]
Closed.  We're on 4.2.5 now.
