### ISSUE TITLE
Improve rendering of equivalent class expressions

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#891]
Someone on the mailing list has pointed out that it is hard to make sense of complex equivalent class expressions.

For example, instead of showing: 
```
'Medicinal product (product)' and ('Has manufactured dose form (attribute)' some 'Conventional release oral suspension (dose form)') and ('Role group (attribute)' some

(('Has basis of strength substance (attribute)' some 'Loperamide hydrochloride (substance)') and ('Has concentration strength denominator unit (attribute)' some ML) and ('Has concentration strength denominator value (attribute)' some '1 (qualifier value)') and ('Has concentration strength numerator value (attribute)' some '133 (qualifier value)') and ('Has concentration strength numerator unit (attribute)' some MCG) and ('Has precise active ingredient (attribute)' some 'Loperamide hydrochloride (substance)'))) and ('Count of base of active ingredient (attribute)' some '1 (qualifier value)')
```
 
Something like this would be much easier to read:
```
'Medicinal product (product)' and ('Has manufactured dose form (attribute)' some 'Conventional release oral suspension (dose form)') and

          ('Role group (attribute)' some

                   (('Has basis of strength substance (attribute)' some 'Loperamide hydrochloride (substance)') and

                   ('Has concentration strength denominator unit (attribute)' some ML) and

                   ('Has concentration strength denominator value (attribute)' some '1 (qualifier value)') and

                   ('Has concentration strength numerator value (attribute)' some '133 (qualifier value)') and

                   ('Has concentration strength numerator unit (attribute)' some MCG) and

                   ('Has precise active ingredient (attribute)' some 'Loperamide hydrochloride (substance)'))) and

          ('Count of base of active ingredient (attribute)' some '1 (qualifier value)')
```

The original poster was wondering if something like this isn't (or couldn't be) provided as a formatting option or a plugin.

**Comment by matthewhorridge** [comment]
Protege should be pretty printing class expressions.  Do you have a sample ontology and class for which it isn't?

**Comment by rwynne** [comment]
@matthewhorridge These are from Build 5.5.0 beta 7.  I will upgrade to see if it makes any difference.

The sample ontology I'm working with is the SNOMED CT OWL produced by the snomed-owl-toolkit (https://github.com/IHTSDO/snomed-owl-toolkit).  It is in OWL2 EL++.

**Comment by rwynne** [comment]
OK, I would need to uninstall and reinstall and don't have the time since I'm just a Protege user.  Here is a screenshot.

![example](https://user-images.githubusercontent.com/6089714/58131018-8925d600-7beb-11e9-86b4-cca0fc971311.jpg)

**Comment by csnyulas** [comment]
This is what I see in Protege 5.5, on a different class (I have only access to an older version of SNOMED-CT, which does not have the class you show in your screen shot)

![image](https://user-images.githubusercontent.com/2441046/58206156-08231900-7c95-11e9-92a7-7bce9662742b.png)

This looks good to me.

@rwynne can you confirm that this is still an issue in Protege 5.5?

**Comment by samsontu** [comment]
I downloaded the most recent version of SNOMED CT and created an OWL file. Here is what I see in Protege 5.5
<img width="734" alt="image" src="https://user-images.githubusercontent.com/1760964/58213167-09a90d00-7ca6-11e9-8484-424f321ac4f3.png">

**Comment by csnyulas** [comment]
Nice, @samsontu !

So, this seems to have been fixed since (or was just a glitch in) P5.5-beta-7.

Unless @rwynne confirms that this is still an issue for him in **Protege 5.5**, we should be able to close this issue.

**Comment by rwynne** [comment]
@csnyulas @matthewhorridge I was able to install the official 5.5 release on a laptop for travel.  This display is exactly what I needed!  Thank you all.

**Comment by csnyulas** [comment]
Excellent! We will close the issue then.
