### ISSUE TITLE
Fix Auto Update entry for ELK

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#892]
The current update.properties file for the ELK reasoner plugin that is listed in [Protege 5.5 plugin repository](https://github.com/protegeproject/autoupdate/blob/master/update-info/5.0.0/plugins.repository#L22) (`http://elk.semanticweb.org/maven/latest/elk-distribution/resources/p5.update.properties`) is unreachable, and gives a "Connection timed out" error. This causes a long delay before Protege shows the window with the available plug-in versions whenever a "Check for plugins..." action is executed.

There was an issue filed for this on the ELK repository, which provides more details, and potential solutions: https://github.com/liveontologies/elk-reasoner/issues/58

Depending on how that issue will be resolved, we should fix the ELK entry in the plugins.repository file.

**Comment by matthewhorridge** [comment]
Temporary workaround in place now
