### ISSUE TITLE
Export inferred axioms with Elk reasoner with subproperty/equivalent property axiom types checked

### ISSUE THREAD

**Issue by samsontu** [protegeproject/protege#894]
With a trivial ontology consisting of a few classes, a few object properties, and one defined class, exporting inferred axioms with the default list of axiom types (including subproperty/equivalent property axioms), no annotation or asserted axioms, results in no error message and no exported ontology, although Protege is still responsive. The log is appended below. If the exported axiom types are limited to subclass and equivalent class axioms, an exported ontology is created. In the case of exporting inferred axioms of SNOMED CT, with subproperty/equivalent property axiom types, Protege hangs.

INFO  10:05:52  ------------------------------- Running Reasoner -------------------------------
   INFO  10:05:52  ELK reasoner was created
   INFO  10:05:52  Pre-computing inferences:
   INFO  10:05:52      - class hierarchy
   INFO  10:05:52      - object property hierarchy
   INFO  10:05:52      - data property hierarchy
   INFO  10:05:52      - class assertions
   INFO  10:05:52      - object property assertions
   INFO  10:05:52      - data property assertions
   INFO  10:05:52      - same individuals
   INFO  10:05:52  Loading of Axioms started
   INFO  10:05:52  Loading of Axioms using 8 workers
   INFO  10:05:52  Loading of Axioms took 12 ms
   INFO  10:05:52  Property Saturation Initialization started
   INFO  10:05:52  Property Saturation Initialization using 8 workers
   INFO  10:05:52  Property Saturation Initialization took 0 ms
   INFO  10:05:52  Reflexive Property Computation started
   INFO  10:05:52  Reflexive Property Computation using 8 workers
   INFO  10:05:52  Reflexive Property Computation took 7 ms
   INFO  10:05:52  Object Property Hierarchy and Composition Computation started
   INFO  10:05:52  Object Property Hierarchy and Composition Computation using 8 workers
   INFO  10:05:52  Object Property Hierarchy and Composition Computation took 3 ms
   INFO  10:05:52  Context Initialization started
   INFO  10:05:52  Context Initialization using 8 workers
   INFO  10:05:52  Context Initialization took 2 ms
   INFO  10:05:52  Consistency Checking started
   INFO  10:05:52  Consistency Checking using 8 workers
   INFO  10:05:52  Consistency Checking took 13 ms
   INFO  10:05:52  Class Taxonomy Computation started
   INFO  10:05:52  Class Taxonomy Computation using 8 workers
   INFO  10:05:52  Class Taxonomy Computation took 14 ms
   INFO  10:05:52  Instance Taxonomy Computation started
   INFO  10:05:52  Instance Taxonomy Computation using 8 workers
   INFO  10:05:52  Instance Taxonomy Computation took 5 ms
   INFO  10:05:52  Ontologies processed in 144 ms by ELK Reasoner
   INFO  10:05:52  
   WARN  10:06:56  [owlapi.unsupportedMethod]OWL API reasoner method is not implemented: getSuperObjectProperties(OWLObjectPropertyExpression, boolean).
   WARN  10:06:56  An error occurred whilst exporting the inferred ontology: {}
java.lang.NumberFormatException: For input string: "2016-01-11T13:41:15Z"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_121]
	at java.lang.Integer.parseInt(Integer.java:580) ~[na:1.8.0_121]
	at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_121]
	at org.semanticweb.elk.owlapi.ElkReasoner.getReasonerVersion(ElkReasoner.java:638) ~[na:na]
	at org.semanticweb.owlapi.util.InferredOntologyGenerator.fillOntology(InferredOntologyGenerator.java:139) ~[na:na]
	at org.protege.editor.owl.ui.action.export.inferred.ExportInferredOntologyAction$ExportTask.run(ExportInferredOntologyAction.java:99) ~[na:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]

**Comment by ykazakov** [comment]
I guess Protege should handle exceptions better.

@samsontu can you try the [latest development version of ELK](https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.semanticweb.elk&a=elk-distribution-protege&e=zip&v=LATEST)?
The support of object property classification has been added and the problem with the version info has been fixed (see liveontologies/elk-reasoner#49).
I tried the inferred axiom export with some old version fo Snomed CT (20150131) and it worked fine for me in Protege 5.5.

**Comment by samsontu** [comment]
The use of elk-protege-0.5.0-SNAPSHOT resolves the issue.
