### ISSUE TITLE
Merging two classes

### ISSUE THREAD

**Issue by cmungall** [protegeproject/protege#90]
(enhancement request)

OBO-Edit has a tool for merging two classes. This is described here:

http://oboedit.org/docs/html/Merging.htm

(this doesn't describe the effects of merging other axioms types, like equivalence axioms or disjoint axioms)

This is one of the features missed by OE users when I turn them to Protege; the steps must be performed manually.

A Protege merge tool would be more generic than the OE one - for example, Protege does not make any assumptions about specific annotation properties. I think OE users would be more than happy with a generic merge, i.e. essentially the same thing as using the EntityRenamer in the OWLAPI (with the source URI preserved somehow)

This functionality may belong in a plugin, e.g.
https://github.com/balhoff/obo-actions

(which performs the related 'obsoletion' operation)
cc: @dosumis

**Comment by matthewhorridge** [comment]
@cmungall has there been any progress on this elsewhere?  Just wondering whether to assign this to the 5.6.0 milestone or not.

**Comment by cmungall** [comment]
Not really. We have a command in owltools: https://github.com/owlcollab/owltools/commit/67c2aa1e40282df56e64e66b43a7ccc0bc1dba86

Not worth reusing the code though

**Comment by matthewhorridge** [comment]
Ok, thanks, then I'll add it to the 5.6.0 milestone.  (The plan is to get 5.0.0 asap, with just bug fixes for the 5.5.0 milestone).

**Comment by matthewhorridge** [comment]
p.s. assuming you still want this!

**Comment by cmungall** [comment]
Definitely! @ukemi do you have any particular preferences as to how this should operate?

**Comment by ukemi** [comment]
We should ping @pgaudet on this. She does the majority of merges in GO. I had envisioned a plug-in where the target term and the term-to-be-merged would be entered.

**Comment by matthewhorridge** [comment]
Just coming back to this @cmungall, @ukemi and @pgaudet

The link in the first comment on this issue is now broken, so I'm just wondering... If somebody was to merge term A into term B then this would mean that all occurrences of A are replaced with B right?  What should happen to special annotation assertions such as rdfs:label and the like?  Do these become synonyms?

**Comment by cmungall** [comment]
OboEdit would sometimes create a merged definition that you had to edit - but in other ontologies where people were less disciplined than GO, they would forget and you would see these kicking around...

in fact some still are:
https://www.ebi.ac.uk/ols/search?q=%22merged+definition%22&groupField=iri&start=0

I am OK with labels becoming exact syns in the OBO profile.

I think it's OK to temporarily have two text definitions and the curator to choose the desired one

We could also annotate any merged axioms with an annotation mergedFrom=<originalIRI>

**Comment by matthewhorridge** [comment]
Thanks @cmungall.  Very helpful.  Is there an IRI for "mergedFrom", or is this new?

**Comment by matthewhorridge** [comment]
Also, @cmungall, one thing that I'm wondering about, what's the main difference between a merge and a deprecation?  If, say I merge X into Y, how is this different from deprecating X and replacing it with Y?  I'm wondering this from both a technical point of view and from a process point of view.

**Comment by cmungall** [comment]
A merge is more extreme, and all that is left is a bare IRI (in fact in the obo, the stanza disappears altogether)

https://github.com/owlcs/owlapi/issues/317

http://wiki.geneontology.org/index.php/Merging_Ontology_Terms

**Comment by pgaudet** [comment]
What is confusing perhaps is that the IRI of the merged term shows up (at least in protege) as if it was obsolete. 

For example: GO_0004887 is merged (is a secondary ID for GO:0004879) 
but is also has the 'owl deprecated = true' tag:
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/4782928/54923866-73f23b00-4f0b-11e9-9951-b171792e0ee9.png">

Pascale

**Comment by matthewhorridge** [comment]
Hi @pgaudet and @cmungall 

I've implemented some merge functionality according to the discussion above and the GO editor's workflow docs.  I've built a snapshot build of 5.6.0-beta-1, which can be obtained here:

[macOS](https://oss.sonatype.org/content/repositories/snapshots/edu/stanford/protege/protege-desktop/5.6.0-beta-1-SNAPSHOT/protege-desktop-5.6.0-beta-1-20190405.224201-1-os-x.zip)

[Windows](https://oss.sonatype.org/content/repositories/snapshots/edu/stanford/protege/protege-desktop/5.6.0-beta-1-SNAPSHOT/protege-desktop-5.6.0-beta-1-20190405.224201-1-win.zip)

[Linux](https://oss.sonatype.org/content/repositories/snapshots/edu/stanford/protege/protege-desktop/5.6.0-beta-1-SNAPSHOT/protege-desktop-5.6.0-beta-1-20190405.224201-1-linux.tar.gz)

[Platform Independent](https://oss.sonatype.org/content/repositories/snapshots/edu/stanford/protege/protege-desktop/5.6.0-beta-1-SNAPSHOT/protege-desktop-5.6.0-beta-1-20190405.224201-1-platform-independent.zip)

When you get a moment, please would you have a look at the merge functionality and let me know whether you're happy with it or whether it needs improvements (of any kind)?  

You select a source entity and then choose "Edit -> Merge entity..." to select a target entity that the source entity will be merged into.

**Comment by matthewhorridge** [comment]
Hi @pgaudet Great!  Thanks for testing if for me.  I'll close this issue for now (as implemented), but please don't hesitate to let me know if this needs improvements.
