### ISSUE TITLE
Using Protege with OKTA

### ISSUE THREAD

**Issue by tccctc** [protegeproject/protege#902]
My company wold like to use Protege, but I have a question.  Can your application be incorporated into OKTA, LDAP, etc...

Chris

**Comment by csnyulas** [comment]
Protégé is a desktop application that runs in a Java virtual machine. It does not require user sign-in, just as your MS Office program or PDF viewer does not require you to log in when you open it. 

If your question refers to WebProtégé (https://github.com/protegeproject/webprotege), then the answer is that it does not support OKTA or LDAP.

BTW, this question should go to our support mailing lists (https://protege.stanford.edu/support.php), not as an issue for the software.
