### ISSUE TITLE
ELK plugin not availble from the Check for plugins menu in Protege 5.5

### ISSUE THREAD

**Issue by pgaudet** [protegeproject/protege#908]
Hello, 
The ELK plugin not availble from the Check for plugins menu in Protege 5.5 - it used to be, can this be added back ? GO editors would appreciate this. 

Thanks, Pascale

**Comment by matthewhorridge** [comment]
This is related to #892

**Comment by matthewhorridge** [comment]
I've temporarily redirected the ELK update settings.  You should now see ELK in the plugins menu when checking for updates

**Comment by pgaudet** [comment]
Thanks !
