### ISSUE TITLE
Small issue with the GO Deprecate entity function

### ISSUE THREAD

**Issue by pgaudet** [protegeproject/protege#909]
Hello, 

The new 'Deprecate entity' for GO is really great ! There is one small issue however: 
before description, we need to insert 'OBSOLETE.' The period is missing (it is currently inserting only 'OBSOLETE'). It'd be great if that could be fixed. 

Thanks, Pascale

**Comment by matthewhorridge** [comment]
Hi Pascale,

Please can you clarify whether the period should be inserted for rdfs:label as well (where the lowercase 'obsolete' is used)?

Thanks,

Matthew

**Comment by pgaudet** [comment]
No - just the 'definition'.

**Comment by matthewhorridge** [comment]
Okay thanks a lot for the clarification.

**Comment by matthewhorridge** [comment]
p.s. @pgaudet 

The fix will be available in the next release of Protege.  If you want a temporary fix in your local installation of Protege, you can edit the ```Protege/Java/Contents/conf/deprecation/go.yaml``` file (inside the Protege App – access it with __"Show Package Contents"__ by Ctrl + Clicking on the Protege Mac App).  

Change line 10 from 

```yaml
annotationValuePrefix: OBSOLETE
``` 
to 
```yaml
annotationValuePrefix: OBSOLETE.
```

**Comment by pgaudet** [comment]
Great ! Thanks for dealing with this so quickly.
