### ISSUE TITLE
How to add restriction for Classes in version5.5?

### ISSUE THREAD

**Issue by dwanboweb** [protegeproject/protege#917]
Very sorry to disturb you.I tried to imitate a blog on the Internet,and the author used version3.1.1.I found that I cannot find the view "Class Editor" that the author used to add restriction to Class.And I cannot find that view anyway.What should I do?
Thanks you.
(the img is copy from the blog)
![20171214135513715](https://user-images.githubusercontent.com/17172451/64010571-9dfbf900-cb4c-11e9-8912-40f2c6af8c6d.png)

**Comment by matthewhorridge** [comment]
Select the class and then use the "Class Description" view on the right hand side.  "Necessary" in Protege 3.x corresponds to "SubClassOf" in Protege 5.x.  "Necessary & Sufficient" in Protege 3.x corresponds to "Equivalent To" in Protege 5.x.  Use the + button to add new restrictions (or any class expression).  There's more documentation here:

http://protegeproject.github.io/protege/views/class-description/

**Comment by dwanboweb** [comment]
Thank you so much.
