### ISSUE TITLE
Cant write class expressions in render by label mode if label contains apostrophe

### ISSUE THREAD

**Issue by zoependlington** [protegeproject/protege#919]
Hello! 

Recently while editing EFO (https://www.ebi.ac.uk/ols/ontologies/efo), we noticed something peculiar regarding terms with apostrophes (e.g. Crohn's disease, Sezary's disease etc.). We are 1) not able to write class expressions in render by label mode if the label contains an apostrophe (see example below):

![image](https://user-images.githubusercontent.com/36990116/64972251-e0d60480-d8a0-11e9-9085-b9f4efecca82.png)

 and 2) if parent term with apostrophe in label was previously assigned, this now seems to point to only the latter part of the label for diseases (see attached screenshot for oral Crohn’s disease)

![image](https://user-images.githubusercontent.com/36990116/64972270-e9c6d600-d8a0-11e9-917e-fa546e93311f.png)

We switched to Protege version 5.5.0 in June and have only just noticed this issue so we are not sure if it is a recent problem or an existing one as EFO is very large and we may not have edited using these terms for quite some time. This was noticed in our EFO 3.10.0 file which can be found [here](https://github.com/EBISPOT/efo/releases/tag/v3.10.0).

There is an existing ticket in your tracker (https://github.com/protegeproject/protege/issues/578) that mentions apostrophes from 2016. Not sure if this is the same issue, but wanted to link anyway!

Thanks in advance,
Zoë (on behalf of the EFO team - @paolaroncaglia, @matentzn)

**Comment by matthewhorridge** [comment]
This is definitely a bug.  To edit the name you have to escape it like this

```'Chron\'s Disease'```

Protege should render this into the editor.
