### ISSUE TITLE
mapping ontologies and alignments

### ISSUE THREAD

**Issue by eliohb** [protegeproject/protege#921]
3,Dear, in protege version 3 you had a plugin (MapOnto.jar) that enable mapping ontologies.
However, this plugin only works on version 3 and I was wondering if you have another plugin for version 5 or any documentation/tools that help me to map multiple ontologies.
Thank you in advance 
Best Regards,
Elio HBEICH

**Comment by rsgoncalves** [comment]
There is currently no plugin for Protege 5.5 to achieve the same kind of functionality.
