### ISSUE TITLE
Question: plugin changes output file

### ISSUE THREAD

**Issue by drseb** [protegeproject/protege#926]
Hi,

after several hours of research I found the reason for an unintentional huge diff for an ontology that appears upon a minor change with a subsequent save in protege. I wonder if that is intentional? (I know nothing about this plugin, but assumed installing plugins would not affect the behaviour of protege during saving)

Simply installing the plugin with the name "Ontop OBDA Protége plugin" will change [our ontology](https://github.com/obophenotype/human-phenotype-ontology/raw/master/src/ontology/hp-edit.owl) very significantly.
Attached two screenshots of the most important changes, that leads to thousands of lines being modified, as the annotation property "layperson" is used extensively. 

<img width="1133" alt="top" src="https://user-images.githubusercontent.com/5172897/68991444-3f970a80-085f-11ea-9713-59c24ee849ca.png">

<img width="1156" alt="AP" src="https://user-images.githubusercontent.com/5172897/68991443-3f970a80-085f-11ea-88f2-8a23e00ae04f.png">

Thanks for any comments.
Best,
Seb

**Comment by nicolevasilevsky** [comment]
I had the same issue with the Mondo ontology, after I installed this plugin.

**Comment by nicolevasilevsky** [comment]
cc @matthewhorridge

**Comment by nicolevasilevsky** [comment]
The fix was to go back into our preferences in Protégé/New Entities tab and fix the Specified IRI.

![image](https://user-images.githubusercontent.com/6722114/69194802-ee954980-0ade-11ea-86fd-4af7ff93b4ec.png)

**Comment by drseb** [comment]
@nicolevasilevsky @matthewhorridge This fix is helping for me. The "Specified IRI" remains unchanged upon installation of said plugin. Only installing/uninstalling changes the behaviour for me.

**Comment by cmungall** [comment]
Yes it's not clear how the new entities tab can help, this is to do with the prefixes. You need to open the ontology prefixes window and edit there.

I think this issue should be filed here:
https://github.com/ontop/ontop/issues

It's not clear what Protege should do about plugins that choose to cryptically alter either the semantics or syntactic characteristics of ontologies, this would be a hard thing to guard against.

**Comment by cmungall** [comment]
One thing the OBO community could do is vet a minimal list of safe recommended plugins. This is good to do anyway, as people will not know of plugins that are helpful, and which to avoid.

**Comment by ghxiao** [comment]
Hi, thanks for reporting the issue. We have fixed the issue in the Ontop v3.0.1 release. Please give it a try.

**Comment by rsgoncalves** [comment]
The plugin Ontop v3.0.1 doesn't seem to be altering ontologies, either new or loaded from existing source. Thanks all for the input and the resolution.
