### ISSUE TITLE
swrlb:divide of xsd:float yields non-terminating decimal runtime exception

### ISSUE THREAD

**Issue by sbguthery** [protegeproject/protege#928]
I divide two xsd:float values using swrlb:divide and I get a "java.lang ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result" from SQWRL".  This seems to have to do with the use of Java's BigDecimal to do the division.  

Does the specification of swrlb:divide say that values are converted to xsd:decimal before division?

More to the point, is there a workaround?

Thanks in advance for any insight.

Cheers, Scott

**Comment by martinjoconnor** [comment]
Are you using the latest version of the SWRLAPI/SWRLTab? I think I fixed this issue quite a while ago.

**Comment by rsgoncalves** [comment]
@sbguthery is this still an issue (using the latest SWRLTab)?

**Comment by martinjoconnor** [comment]
This was fixed in the 2.0.7 SWRLTab release:

https://github.com/protegeproject/swrltab-plugin/releases/tag/release-2.0.7

**Comment by rsgoncalves** [comment]
Ok, closing this then.
