### ISSUE TITLE
"cannot be resolved to a type" in protege-editor-owl

### ISSUE THREAD

**Issue by sbguthery** [protegeproject/protege#929]
Rebuilding Protegy desktop according to the instructions in ...

https://github.com/protegeproject/protege/wiki/Setup-in-Eclipse-PDE

I find that many (all?) of the constructs of the form

return new AutoValue_XXX

throw a "cannot be resolved to a type" error.  I don't know AutoValue but a little sniffing around indicates that this might have something to do with annotations.  LangCode imports javax.annotation.Nonull but still throws the error.  

I'm way off the end of the pier here so this is just an FYI from a punter.

Cheers, Scott

- Windows 10
- jdk-13.0.1
- fresh clone of Protege

**Comment by sbguthery** [comment]
Adding jbosstools/m2e-apt from github  to Eclipse solves this problem.

**Comment by rsgoncalves** [comment]
It looks like you've figured it out, so I'm closing this issue. Feel free to reopen if the issue persists.

**Comment by matthias-samwald** [comment]
> Adding jbosstools/m2e-apt from github to Eclipse solves this problem.

I'm having the same problem, but unfortunately this does not fix it.
