### ISSUE TITLE
Equivalent class definition issue 

### ISSUE THREAD

**Issue by amin101** [protegeproject/protege#930]
I've simplified pizza.owl ontology to describe the issue. ontology can be downloaded from [here.](http://s000.tinyupload.com/index.php?file_id=14938680915246117107)

 if i define `RealItalianPizza` as equivalent class by `pizza` (in one line) and ` hasBase only PizzaBase` in another line as shown in below picture, i'd get a reasoning error.
(click on image to see it clear)
<a href="https://ibb.co/M2w2qRr"><img src="https://i.ibb.co/BzWz8gb/1.jpg" alt="1" border="0"></a>

if i define this class as ` Pizza and hasBase only PizzaBase` , every thing is right and there is no issue. 
<a href="https://ibb.co/FHcx5kR"><img src="https://i.ibb.co/tLnmqwV/2.jpg" alt="2" border="0"></a>
As i know defining class axiom in one line or separate it as multiple line has no difference once we need `and` junction between axioms. but here seems there is an issue

**Comment by rsgoncalves** [comment]
The two ontologies in the screenshots are logically very different. Protégé's behavior is correct and inline with the semantics of OWL, so this is not a tool issue. To understand the modeling problem it might help to look at the axioms written out, like so:

`RealItalianPizza EquivalentTo Pizza`
`RealItalianPizza EquivalentTo hasBase only PizzaBase` 

versus

`RealItalianPizza EquivalentTo Pizza and hasBase only PizzaBase`
