### ISSUE TITLE
Instance Tree for new Protege version

### ISSUE THREAD

**Issue by william-vw** [protegeproject/protege#945]
I was wondering whether anything like the old ["Instance Tree" plugin](https://protegewiki.stanford.edu/wiki/InstanceTree) is available for the current Protege version?

Essentially it could be seen as essentially showing the current individual-related navigation history

**Comment by rsgoncalves** [comment]
We don't know of a plugin analogous to InstanceTree for Protege 5 / OWL2. Perhaps other users in the protege-user mailing list might be able to help.
