### ISSUE TITLE
Collaboration with Protege 5.5.0

### ISSUE THREAD

**Issue by abdulzeedo** [protegeproject/protege#952]
I am trying to find the best way to create an ontology collaboratively with other people. What are your suggestions?

**Comment by matthewhorridge** [comment]
Take a look at https://webprotege.stanford.edu

**Comment by matthewhorridge** [comment]
p.s. This is an issue tracker for issues with Protege.  Not a general protege questions forum.  Please use the [protege-user](https://mailman.stanford.edu/mailman/listinfo/protege-user) mailing list for support and discussion like this.
