### ISSUE TITLE
Should changes be saved dialog

### ISSUE THREAD

**Issue by iamkoehler** [protegeproject/protege#96]
Hi,

when closing Protege and having unsaved changes, I am asked if I would like to save those changes. When I hit the Escape-Key on my keyboard Protege quits without saving, although my intention was to abort/cancel the "protege-closing". Is it possible to change this (for me unintuitive) behaviour?

Thanks,
Sebastian

I am on MacOS and use Protege 4.3.

**Comment by drseb** [comment]
Hi.

I have just downloaded and used Protege 5 beta and the behavior is still the same for me. 

Am I doing something wrong?

Best,
Sebastian

**Comment by matthewhorridge** [comment]
Sebastian,

It's fixed in the latest release which was made available this week (5.0.0-beta-16).

**Comment by csnyulas** [comment]
Note: In case Sebastian, or anyone else has problems downloading the latest version from the Protege web site (http://protege.stanford.edu/products.php#desktop-protege), please try to **reload the page** in your browser manually. We observed that some browsers don't load the updated content when there is change, and show the old (cached) content, unless you manually reload it.

You can also get the latest release directly from GitHub:
https://github.com/protegeproject/protege/releases
