### ISSUE TITLE
Not able to create turtle files

### ISSUE THREAD

**Issue by Tarun3679** [protegeproject/protege#969]
Hi, I tried to save the created ontology as a turtle file, however it is getting saved with .owl extension. I was wondering if there was a way to save it in the form of a turtle file. If you have any alternatives, Please let me know.

I am currently using protege version - 5.5.0

**Comment by jmkeil** [comment]
Protege actually writes a Turtle file. However, it erroneously uses always the file extension `.owl`. A workaround is, to manually set the file extension `.ttl`. However, this really should be solved. Also for the other formats:

Type | Extansion | Reference
---|---|---
RDF/XML |  `.rdf` | https://www.w3.org/TR/rdf-syntax-grammar/#h2_section-MIME-Type
Turtle |  `.ttl` | https://www.w3.org/TR/turtle/#h2_sec-mediaReg
OWL/XML |  `.owx` | https://www.w3.org/TR/owl2-xml-serialization/#Appendix:_Internet_Media_Type.2C_File_Extension.2C_and_Macintosh_File_Type
OWL Functional |  `.ofn` | https://www.w3.org/TR/owl2-syntax/#Appendix:_Internet_Media_Type.2C_File_Extension.2C_and_Macintosh_File_Type
Manchester |  `.omn` | https://www.w3.org/TR/2012/NOTE-owl2-manchester-syntax-20121211/#Appendix:_Internet_Media_Type.2C_File_Extension_and_Macintosh_File_Type
OBO |  `.obo` | 
LaTeX |  `.tex` | 
JSON-LD |  `.jsonld` | https://www.w3.org/TR/json-ld/#iana-considerations

**Comment by jmkeil** [comment]
This might be related to #867.

**Comment by matthewhorridge** [comment]
Closed by #1016

**Comment by mf093087** [comment]
May  I ask, how to use .ttl ontology in protege? I can't import that.
