### ISSUE TITLE
Protege 5.5.0 deletes ! full-line comments in obo files

### ISSUE THREAD

**Issue by Clare72** [protegeproject/protege#971]
I wanted to temporarily stop loading a couple of imports, so I commented them out in my obo file (with ! at the start of the line). When I checked my diff, the whole commented out lines had been removed by saving the file in Protege 5.5.0.

I can get around the issue by using 'remark: ' instead of '! ' so that Protege interprets the lines as comment annotations, but I think that Protege should not be deleting comments from files.

**Comment by cmungall** [comment]
This is actually the intended behavior of the OBO parser. This is part of the OWLAPI, and not Protege. You can blame me for this behavior! There isn't a lot the Protege team can do here.

**Comment by Clare72** [comment]
@cmungall - I saw [here](https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_4.html) that ! was supposed to allow a full line comment that would be ignored by parsers, I guess this is out of date(?)

Closing ticket, as this is not a protege bug.

**Comment by cmungall** [comment]
Yep - it is ignored (as in ignored and discarded)
