### ISSUE TITLE
Consider tooltip for Property Characteristics

### ISSUE THREAD

**Issue by zwelz3** [protegeproject/protege#972]
New users need to constantly refer to the docs to determine if a created property has certain Property Characteristics (e.g. transitive, functional, etc.). This would be an easy tooltip (on hover) that provides just enough context to remind users of what each characteristic means. 

Something like:
- Functional: at most one individual/datatype related to the property [e.g. hasBirthMother]
- Inverse functional: all inverse properties are functional [e.g. isBirthMotherOf]
- Transitive: properties shared by parent/child also relate parent to child (chainable) [e.g. hasAncestor]
- Symmetric: property relating A to B also relates B to A [e.g. hasSibling]
- Asymmetric: property relating A to B cannot relate B to A [e.g. isChildOf]
- Reflexive: property must relate A to itself [e.g. knows]
- Irreflexive: property relates A to B, but cannot relate A to itself [e.g. motherOf]

This is not necessary, but would be a nice QoL enhancement.

**Comment by zwelz3** [comment]
Looks like the tool panel help (the question mark) directs to a webpage with this info. Probably unnecessary to add as tooltip.

**Comment by matthewhorridge** [comment]
Closing because the help page seems sufficient
