### ISSUE TITLE
My Annotations in Protege 5.5（or other versions）can‘t work

### ISSUE THREAD

**Issue by Rena-Yang-cell** [protegeproject/protege#978]
When I import the file into Protege in my computer(MacBook Pro 13,ios MacOS 10.15.4 Catalina), it shows like this
<img width="1266" alt="截屏2020-09-28 下午3 31 00" src="https://user-images.githubusercontent.com/68352495/94488646-f9197880-01b0-11eb-9e03-ce067613deee.png">The part of  Annotations is in a different color, and nothing in it. When I click the ➕(beside the annotations), there is no reaction. When I open the file in other computer's Protege and Protege website in my computer, the part of Annotation is fine.
Then I downloaded different versions of Protege and I got the same results. And I found the Java environment required, so I tried to download Java versions and settle down its environment and variable parameters in my computer. However, I can't launch my .jar file, so I still can't use my Protege. Could you help me to figure it out? My email is yangwa@umich.edu.
<img width="316" alt="截屏2020-09-28 下午3 49 54" src="https://user-images.githubusercontent.com/68352495/94488925-88269080-01b1-11eb-9017-c035eeda5014.png">
<img width="560" alt="截屏2020-09-28 下午3 49 32" src="https://user-images.githubusercontent.com/68352495/94489036-c754e180-01b1-11eb-9248-7c02d287f456.png">
<img width="421" alt="截屏2020-09-28 下午3 49 20" src="https://user-images.githubusercontent.com/68352495/94489045-c9b73b80-01b1-11eb-9718-365422ea7c5d.png">
<img width="417" alt="截屏2020-09-28 下午3 49 06" src="https://user-images.githubusercontent.com/68352495/94489048-cb80ff00-01b1-11eb-9aaa-558e3119fc68.png">

**Comment by matthewhorridge** [comment]
Hi,

Please can you try “Window” -> “Reset selected tab to default state”?  This should fix the view.  Please let us know if this works…. or doesn’t.

Cheers,

Matthew

On Sep 28, 2020, at 14:42, Rena Wang <notifications@github.com<mailto:notifications@github.com>> wrote:



When I import the file into Protege in my computer(MacBook Pro 13,ios MacOS 10.15.4 Catalina), it shows like this
[截屏2020-09-28 下午3 31 00]<https://user-images.githubusercontent.com/68352495/94488646-f9197880-01b0-11eb-9e03-ce067613deee.png>The part of Annotations is in a different color, and nothing in it. When I click the ➕(beside the annotations), there is no reaction. When I open the file in other computer's Protege and Protege website in my computer, the part of Annotation is fine.
Then I downloaded different versions of Protege and I got the same results. And I found the Java environment required, so I tried to download Java versions and settle down its environment and variable parameters in my computer. However, I can't launch my .jar file, so I still can't use my Protege. Could you help me to figure it out? My email is yangwa@umich.edu<mailto:yangwa@umich.edu>.
[截屏2020-09-28 下午3 49 54]<https://user-images.githubusercontent.com/68352495/94488925-88269080-01b1-11eb-9017-c035eeda5014.png>
[截屏2020-09-28 下午3 49 32]<https://user-images.githubusercontent.com/68352495/94489036-c754e180-01b1-11eb-9248-7c02d287f456.png>
[截屏2020-09-28 下午3 49 20]<https://user-images.githubusercontent.com/68352495/94489045-c9b73b80-01b1-11eb-9718-365422ea7c5d.png>
[截屏2020-09-28 下午3 49 06]<https://user-images.githubusercontent.com/68352495/94489048-cb80ff00-01b1-11eb-9aaa-558e3119fc68.png>

**Comment by Rena-Yang-cell** [comment]
Thank you so much😭, I've been confused for this question for a long time. I'm sorry to reply late.
It does work.Thank you, Matthew!
<img width="1275" alt="截屏2020-09-29 上午3 15 44" src="https://user-images.githubusercontent.com/68352495/94525426-11fe4a00-0202-11eb-83ce-d771254b9521.png">

**Comment by matthewhorridge** [comment]
Great! :)
