### ISSUE TITLE
ontology (ttl) does not show in the UI

### ISSUE THREAD

**Issue by meerapatelmd** [protegeproject/protege#988]
I am attempting to convert controlled vocabularies stored in a relational database format at athena.ohdsi.org to OWL. I first tried d2rq, but it appears to convert the entity-relationships into OWL and I want the actual vocabulary content. I figured the best alternative is to load all the concepts and organize them into Class, Properties, and Data manually, but to have them and their properties enumerated at least.

I am approaching this problem by using the R package `rdflib` to create triples from the source data and writing them to an rdf or turtle file. However, when opening this file in Protege, there isn't any visible information. It is a blank ontology. I also tried importing the ontology instead with no luck. The log does not show any errors with either rdf or turtle. 

I am not sure if I'm doing something wrong or if there is a bug in Protege for this.

**Comment by matthewhorridge** [comment]
The RFD graph (tripes) that you generate needs to represent an OWL ontology.  Not all RDF graphs represent OWL ontologies and these graphs cannot be parsed into OWL ontologies.  I think that this may be the case here.  You might start off by making sure that each IRI is typed as either an owl:Class, owl:ObjectProperty, owl:DataProperty, owl:AnnotationProperty or an owl:NamedIndividual.  If you do this then Protege should at least load the vocabulary.  Hope this helps.

**Comment by meerapatelmd** [comment]
@matthewhorridge this explains... A lot. Thanks so much!

**Comment by matthewhorridge** [comment]
@meerapatelmd great!  I'll close this issue.
